<a id='top'></a>
# How to slice and dice the data
Below are a series of examples on how to slice and dice the data that is stored in the *.sqlite* file generated by the [MorningStar.com](https://www.morningstar.com) web scraper. 

##### NOTE: 
- The data used in the code below come from the *.sqlite* file that is automatically generated by the web scraper once it has been installed and ran locally on your machine. See [README]() for instructions on how to run install and run the scraper.
- Navigation links only work with [Jupyter](https://jupyter.org/).


**Content** 

1. [Required modules and matplotlib backend](#modules)
1. [Creating a master (bridge table) DataFrame instance using the DataFrames class](#master)
1. [Methods for creating DataFrame instances](#methods)
    1. `quoteheader` - [MorningStar (MS) Quote Header](#quote)
    1. `valuation` - [MS Valuation table with Price Ratios (P/E, P/S, P/B, P/C) for the past 10 yrs](#val)
    1. `keyratios` - [MS Ratio - Key Financial Ratios & Values](#keyratios)
    1. `finhealth` - [MS Ratio - Financial Health](#finhealth)
    1. `profitability` - [MS Ratio - Profitability](#prof)
    1. `growth` - [MS Ratio - Growth](#growth)
    1. `cfhealth` - [MS Ratio - Cash Flow Health](#cfh)
    1. `efficiency` - [MS Ratio - Efficiency](#eff)
    1. `annualIS` - [MS Annual Income Statements](#isa)
    1. `quarterlyIS` - [MS Quarterly Income Statements](#isq)
    1. `annualBS` - [MS Annual Balance Sheets](#bsa)
    1. `quarterlyBS` - [MS Quarterly Balance Sheets](#bsq)
    1. `annualCF` - [MS Annual Cash Flow Statements](#cfa)
    1. `quarterlyCF` - [MS Quarterly Cash Flow Statements](#cfq)
1. [Performing statistical analysis](#stats)
    1. [Count of database records](#stats)
    1. [Last updated dates](#lastupdate)
    1. [Number of records by security type](#type)
    1. [Number of records by country, based on the location of exchanges](#country)
    1. [Number of records per exchange](#exchange)
    1. [Number of stocks by sector](#sector)
    1. [Number of stocks by industry](#industry)
    1. [Mean price ratios (P/E, P/S, P/B, P/CF) of stocks by sectors](#meanpr)
1. [Applying various criteria to filter common stocks](#value) *(in progress)*
1. [Additional sample / test code](#additional) *(in progress)*

<a id="modules"></a>
## Required modules and matplotlib backend

In [1]:
%matplotlib notebook

In [2]:
import matplotlib.pyplot as plt
import matplotlib

In [3]:
from importlib import reload
import pandas as pd
import numpy as np

# Import dataframes module from project folder.
# This module contains a class that reads the database tables and assigns the data to pandas.DataFrame objects
import dataframes
reload(dataframes) #reload if changes have been made to module file

[return to the top](#top)
<a id="master"></a>
## Creating a master DataFrame instance using the dataframes class
The DataFrames class is part of the [dataframes module](dataframes.py)

In [4]:
db_file_name = 'mstables' # Change the file name here as needed
df = dataframes.DataFrames('db/{}.sqlite'.format(db_file_name))

Creating intial DataFrames from file db/mstables.sqlite...
Creating DataFrame 'colheaders' ...
Creating DataFrame 'timerefs' ...
Creating DataFrame 'urls' ...
Creating DataFrame 'securitytypes' ...
Creating DataFrame 'tickers' ...
Creating DataFrame 'sectors' ...
Creating DataFrame 'industries' ...
Creating DataFrame 'stockstyles' ...
Creating DataFrame 'exchanges' ...
Creating DataFrame 'countries' ...
Creating DataFrame 'companies' ...
Creating DataFrame 'currencies' ...
Creating DataFrame 'stocktypes' ...
Creating DataFrame 'master' ...
Initial DataFrames created.

### Creating Master DataFrame instance from reference tables
By merging `df.master` (*Master* bridge table) with other reference tables (e.g. `df.tickers`, `df.exchanges`, etc.)
##### DataFrame Instance

In [5]:
# Create df_master and apply filters
df_master = df.master.copy()

df_master[['lastprice', 'day_hi', 'day_lo', '_52wk_hi', '_52wk_lo', 'yield', 'aprvol', 'avevol']] = (
    df_master[['lastprice', 'day_hi', 'day_lo', '_52wk_hi', '_52wk_lo', 'yield', 'aprvol', 'avevol']]
    .fillna(value=0.0))

df_master = (df_master.where((df_master['openprice'] > 0.0) & (df_master['lastprice'] > 0.0))
             .dropna(axis=0, how='all'))

In [6]:
df_master.head()

,ticker_id,exchange_id,ticker,company,exchange,exchange_sym,industry,sector,country,country_c2,...,aprvol,avevol,Forward_PE,pb,ps,pc,currency,currency_code,fy_end,updated_date
0,1.0,374.0,OGCP,Empire State Realty OP LP Operating Partnershi...,NYSE ARCA,ARCX,REIT - Diversified,Real Estate,United States,US,...,11.0,3498.0,NaN,2.4,6.4,16.7,United States Dollar,USD,2019-12-31,2019-04-11
1,2.0,374.0,FISK,Empire State Realty OP LP Operating Partnershi...,NYSE ARCA,ARCX,REIT - Diversified,Real Estate,United States,US,...,1300.0,3014.0,NaN,2.4,6.4,16.8,United States Dollar,USD,2019-12-31,2019-04-11
2,3.0,374.0,ESBA,Empire State Realty OP LP Operating Partnershi...,NYSE ARCA,ARCX,REIT - Diversified,Real Estate,United States,US,...,4243.0,17288.0,NaN,2.4,6.4,16.8,United States Dollar,USD,2019-12-31,2019-04-11
3,18686.0,302.0,ARE,Alexandria Real Estate Equities Inc,"NEW YORK STOCK EXCHANGE, INC.",XNYS,REIT - Office,Real Estate,United States,US,...,417090.0,695255.0,57.1,2.2,11.2,26.1,United States Dollar,USD,2019-12-31,2019-04-11
4,19275.0,302.0,LPT,Liberty Property Trust,"NEW YORK STOCK EXCHANGE, INC.",XNYS,REIT - Office,Real Estate,United States,US,...,432637.0,843316.0,NaN,2.2,10.3,18.9,United States Dollar,USD,2019-12-31,2019-04-11

##### DataFrame Length

In [7]:
print('Master DataFrame contains {:,.0f} records.'.format(len(df_master)))

Master DataFrame contains 103,490 records.

##### DataFrame Columns

In [8]:
df_master.columns

Index(['ticker_id', 'exchange_id', 'ticker', 'company', 'exchange',
       'exchange_sym', 'industry', 'sector', 'country', 'country_c2',
       'country_c3', 'security_type_code', 'security_type', 'stock_type',
       'style', 'openprice', 'lastprice', 'day_hi', 'day_lo', '_52wk_hi',
       '_52wk_lo', 'yield', 'aprvol', 'avevol', 'Forward_PE', 'pb', 'ps', 'pc',
       'currency', 'currency_code', 'fy_end', 'updated_date'],
      dtype='object')

<br></br>
[return to the top](#top)
<a id='methods'></a>
## Creating DataFrame instances with dataframes methods
Class DataFrames from [dataframe.py](dataframe.py) contains the following methods that return a pd.DataFrame object for the specified database table:

- `quoteheader` - [MorningStar (MS) Quote Header](#quote)
- `valuation` - [MS Valuation table with Price Ratios (P/E, P/S, P/B, P/C) for the past 10 yrs](#val)
- `keyratios` - [MS Ratio - Key Financial Ratios & Values](#keyratios)
- `finhealth` - [MS Ratio - Financial Health](#finhealth)
- `profitability` - [MS Ratio - Profitability](#prof)
- `growth` - [MS Ratio - Growth](#growth)
- `cfhealth` - [MS Ratio - Cash Flow Health](#cfh)
- `efficiency` - [MS Ratio - Efficiency](#eff)
- `annualIS` - [MS Annual Income Statements](#isa)
- `quarterlyIS` - [MS Quarterly Income Statements](#isq)
- `annualBS` - [MS Annual Balance Sheets](#bsa)
- `quarterlyBS` - [MS Quarterly Balance Sheets](#bsq)
- `annualCF` - [MS Annual Cash Flow Statements](#cfa)
- `quarterlyCF` - [MS Quarterly Cash Flow Statements](#cfq)

<a id='quote'></a>
### Quote Header 
##### DataFrame Instance

In [9]:
df_quote = df.quoteheader()

In [10]:
df_quote.head()

,ticker_id,exchange_id,openprice,lastprice,day_hi,day_lo,_52wk_hi,_52wk_lo,yield,aprvol,avevol,fpe,pb,ps,pc,currency_id
0,1,374,15.73,15.72,15.73,15.72,17.72,12.16,2.67,11.0,3498.0,NaN,2.4,6.4,16.7,104.0
1,2,374,15.75,15.77,15.78,15.73,17.68,13.68,2.66,1300.0,3014.0,NaN,2.4,6.4,16.8,104.0
2,3,374,15.76,15.71,15.76,15.63,17.79,11.99,2.67,4243.0,17288.0,NaN,2.4,6.4,16.8,104.0
3,4,482,96.19,95.9,96.48,95.35,115.11,87.87,1.25,192854.0,804691.0,19.8,3.3,3.9,20.1,104.0
4,5,1,0.00,0,0,0,0,0,NaN,184.0,184.0,NaN,NaN,NaN,NaN,104.0

##### DataFrame Length

In [12]:
print('DataFrame contains {:,.0f} records.'.format(len(df_quote)))

DataFrame contains 118,338 records.

<a id='val'></a>
[return to the top](#top)
### Price Ratios (P/E, P/S, P/B, P/C)
##### DataFrame Instance

In [11]:
df_vals = df.valuation().reset_index()

In [12]:
df_vals.head()

,exchange_id,ticker_id,PE_2009,PE_2010,PE_2011,PE_2012,PE_2013,PE_2014,PE_2015,PE_2016,...,PC_2010,PC_2011,PC_2012,PC_2013,PC_2014,PC_2015,PC_2016,PC_2017,PC_2018,PC_TTM
0,374,1,NaN,NaN,NaN,NaN,NaN,18.6,69.0,57.8,...,NaN,NaN,NaN,48.3,-153.8,24.3,25.8,26.3,21.5,16.7
1,374,2,NaN,NaN,NaN,NaN,NaN,18.2,69.0,58.8,...,NaN,NaN,NaN,50.5,-151.5,24.3,26.2,26.4,20.3,16.8
2,374,3,NaN,NaN,NaN,NaN,NaN,18.3,69.4,58.8,...,NaN,NaN,NaN,48.3,-153.8,24.4,26.2,26.7,20.6,16.8
3,482,4,NaN,22.2,17.4,16.6,27.0,29.7,26.6,31.7,...,16.2,11.1,12.9,19.6,23.1,19.9,26.8,52.9,21.8,20.1
4,1,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

##### DataFrame Length

In [13]:
print('DataFrame contains {:,.0f} records.'.format(len(df_vals)))

DataFrame contains 80,567 records.

##### DataFrame Columnns

In [14]:
df_vals.columns

Index(['exchange_id', 'ticker_id', 'PE_2009', 'PE_2010', 'PE_2011', 'PE_2012',
       'PE_2013', 'PE_2014', 'PE_2015', 'PE_2016', 'PE_2017', 'PE_2018',
       'PE_TTM', 'PS_2009', 'PS_2010', 'PS_2011', 'PS_2012', 'PS_2013',
       'PS_2014', 'PS_2015', 'PS_2016', 'PS_2017', 'PS_2018', 'PS_TTM',
       'PB_2009', 'PB_2010', 'PB_2011', 'PB_2012', 'PB_2013', 'PB_2014',
       'PB_2015', 'PB_2016', 'PB_2017', 'PB_2018', 'PB_TTM', 'PC_2009',
       'PC_2010', 'PC_2011', 'PC_2012', 'PC_2013', 'PC_2014', 'PC_2015',
       'PC_2016', 'PC_2017', 'PC_2018', 'PC_TTM'],
      dtype='object')

<a id='keyratios'></a>
[return to the top](#top)
### Key Ratios
##### DataFrame Instance

In [18]:
df_keyratios = (df_master.merge(df.keyratios(), on=['ticker_id', 'exchange_id']))

In [19]:
df_keyratios.head()

,ticker_id,exchange_id,ticker,company,exchange,exchange_sym,industry,sector,country,country_c2,...,Y1,Y2,Y3,Y4,Y5,Y6,Y7,Y8,Y9,Y10
0,1.0,374.0,OGCP,Empire State Realty OP LP Operating Partnershi...,NYSE ARCA,ARCX,REIT - Diversified,Real Estate,United States,US,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
1,2.0,374.0,FISK,Empire State Realty OP LP Operating Partnershi...,NYSE ARCA,ARCX,REIT - Diversified,Real Estate,United States,US,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
2,3.0,374.0,ESBA,Empire State Realty OP LP Operating Partnershi...,NYSE ARCA,ARCX,REIT - Diversified,Real Estate,United States,US,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
3,18686.0,302.0,ARE,Alexandria Real Estate Equities Inc,"NEW YORK STOCK EXCHANGE, INC.",XNYS,REIT - Office,Real Estate,United States,US,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
4,19275.0,302.0,LPT,Liberty Property Trust,"NEW YORK STOCK EXCHANGE, INC.",XNYS,REIT - Office,Real Estate,United States,US,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM

##### DataFrame Length

In [20]:
print('DataFrame contains {:,.0f} records.'.format(len(df_keyratios)))

DataFrame contains 68,394 records.

##### DataFrame Columnns

In [31]:
df_keyratios_cols = (df_keyratios
                     .loc[0, [col for col in df_keyratios.columns if 'Y' not in col and col.startswith('i')]]
                     .replace(df.colheaders['header']))
df_keyratios_cols

industry          REIT - Diversified
i0                           Revenue
i1                      Gross_Margin
i2                  Operating_Income
i3                  Operating_Margin
i4                        Net_Income
i5                Earnings_Per_Share
i6                         Dividends
i91                     Payout_Ratio
i7                            Shares
i8              Book_Value_Per_Share
i9               Operating_Cash_Flow
i10                     Cap_Spending
i11                   Free_Cash_Flow
i90         Free_Cash_Flow_Per_Share
i80                  Working_Capital
Name: 0, dtype: object

<a id='finhealth'></a>
[return to the top](#top)
### Financial Health
##### DataFrame Instance

In [22]:
df_finhealth = df.finhealth()

In [23]:
df_finhealth.head()

,ticker_id,exchange_id,fh_balsheet,i45,i45_fh_Y0,i45_fh_Y1,i45_fh_Y2,i45_fh_Y3,i45_fh_Y4,i45_fh_Y5,...,fh_Y1,fh_Y2,fh_Y3,fh_Y4,fh_Y5,fh_Y6,fh_Y7,fh_Y8,fh_Y9,fh_Y10
0,1,374,324,325,NaN,NaN,NaN,4.89,2.45,1.39,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,Latest Qtr
1,2,374,324,325,NaN,NaN,NaN,4.89,2.45,1.39,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,Latest Qtr
2,3,374,324,325,NaN,NaN,NaN,4.89,2.45,1.39,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,Latest Qtr
3,4,482,324,325,67.09,21.17,41.16,40.02,50.12,38.53,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,Latest Qtr
4,23,1,324,325,37.05,83.93,79.97,86.32,99.22,22.23,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,Latest Qtr

In [24]:
print('DataFrame contains {:,.0f} records.'.format(len(df_finhealth)))

DataFrame contains 77,855 records.

##### DataFrame Columns

In [32]:
df_finhealth_cols = (df_finhealth.loc[0, [col for col in df_finhealth.columns 
                                          if 'Y' not in col and '_id' not in col]]
                     .replace(df.colheaders['header']))
df_finhealth_cols

fh_balsheet         Balance Sheet Items (in %)
i45              Cash & Short-Term Investments
i46                        Accounts Receivable
i47                                  Inventory
i48                       Other Current Assets
i49                       Total Current Assets
i50                                   Net PP&E
i51                                Intangibles
i52                     Other Long-Term Assets
i53                               Total Assets
i54                           Accounts Payable
i55                            Short-Term Debt
i56                              Taxes Payable
i57                        Accrued Liabilities
i58               Other Short-Term Liabilities
i59                  Total Current Liabilities
i60                             Long-Term Debt
i61                Other Long-Term Liabilities
i62                          Total Liabilities
i63                  Total Stockholders Equity
i64                 Total Liabilities & Equity
lfh_liquidity       Liquidity/Financial Health
i65                              Current Ratio
i66                                Quick Ratio
i67                         Financial Leverage
i68                                Debt/Equity
Name: 0, dtype: object

<a id='prof'></a>
[return to the top](#top)
### Profitability
##### DataFrame Instance

In [33]:
df_profitab = df.profitability()

In [34]:
df_profitab.head()

,ticker_id,exchange_id,pr_margins,i12,i12_pr_Y0,i12_pr_Y1,i12_pr_Y2,i12_pr_Y3,i12_pr_Y4,i12_pr_Y5,...,pr_Y1,pr_Y2,pr_Y3,pr_Y4,pr_Y5,pr_Y6,pr_Y7,pr_Y8,pr_Y9,pr_Y10
0,1,374,279,202,NaN,NaN,100.0,100.0,100.0,100.0,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
1,2,374,279,202,NaN,NaN,100.0,100.0,100.0,100.0,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
2,3,374,279,202,NaN,NaN,100.0,100.0,100.0,100.0,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
3,4,482,279,202,100.0,100.0,100.0,100.0,100.0,100.0,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
4,23,1,279,202,100.0,100.0,100.0,100.0,100.0,100.0,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM

##### DataFrame Length

In [35]:
print('DataFrame contains {:,.0f} records.'.format(len(df_profitab)))

DataFrame contains 77,855 records.

##### DataFrame Columns

In [37]:
# Financial Health DataFrame Columns
df_profitab_cols = (df_profitab.loc[0, [col for col in df_profitab.columns 
                                        if 'Y' not in col and '_id' not in col]]
                    .replace(df.colheaders['header']))
df_profitab_cols

pr_margins              Margins % of Sales
i12                                Revenue
i13                                   COGS
i14                           Gross Margin
i15                                   SG&A
i16                                    R&D
i17                                  Other
i18                       Operating Margin
i19                    Net Int Inc & Other
i20                             EBT Margin
pr_profit                    Profitability
i21                             Tax Rate %
i22                           Net Margin %
i23               Asset Turnover (Average)
i24                     Return on Assets %
i25           Financial Leverage (Average)
i26                     Return on Equity %
i27           Return on Invested Capital %
i95                      Interest Coverage
Name: 0, dtype: object

<a id='growth'></a>
[return to the top](#top)
### Growth
##### DataFrame Instance

In [27]:
df_growth = df.growth()

In [28]:
df_growth.head()

,ticker_id,exchange_id,gr_revenue,i28,i28_gr_Y0,i28_gr_Y1,i28_gr_Y2,i28_gr_Y3,i28_gr_Y4,i28_gr_Y5,...,gr_Y1,gr_Y2,gr_Y3,gr_Y4,gr_Y5,gr_Y6,gr_Y7,gr_Y8,gr_Y9,gr_Y10
0,1,374,298,299,NaN,NaN,NaN,-11.70,19.81,103.73,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,Latest Qtr
1,2,374,298,299,NaN,NaN,NaN,-11.70,19.81,103.73,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,Latest Qtr
2,3,374,298,299,NaN,NaN,NaN,-11.70,19.81,103.73,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,Latest Qtr
3,4,482,298,299,2.23,2.59,16.25,0.83,11.65,7.90,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,Latest Qtr
4,23,1,298,299,238.49,16.43,16.43,NaN,NaN,NaN,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,Latest Qtr

##### DataFrame Length

In [29]:
print('DataFrame contains {:,.0f} records.'.format(len(df_growth)))

DataFrame contains 77,855 records.

##### DataFrame Columns

In [38]:
# Financial Health DataFrame Columns
df_growth_cols = (df_growth.loc[0, [col for col in df_growth.columns if 'Y' not in col and '_id' not in col]]
                  .replace(df.colheaders['header']))
df_growth_cols

gr_revenue               Revenue %
i28                 Year over Year
i29                 3-Year Average
i30                 5-Year Average
i31                10-Year Average
gr_operating    Operating Income %
i32                 Year over Year
i33                 3-Year Average
i34                 5-Year Average
i35                10-Year Average
gr_ni                 Net Income %
i81                 Year over Year
i82                 3-Year Average
i83                 5-Year Average
i84                10-Year Average
gr_eps                       EPS %
i36                 Year over Year
i37                 3-Year Average
i38                 5-Year Average
i39                10-Year Average
Name: 0, dtype: object

<a id='cfh'></a>
[return to the top](#top)
### Cash Flow Health
##### DataFrame Instance

In [33]:
df_cfhealth = df.cfhealth()

In [34]:
df_cfhealth.head()

,ticker_id,exchange_id,cf_cashflow,i40,i40_cf_Y0,i40_cf_Y1,i40_cf_Y2,i40_cf_Y3,i40_cf_Y4,i40_cf_Y5,...,cf_Y1,cf_Y2,cf_Y3,cf_Y4,cf_Y5,cf_Y6,cf_Y7,cf_Y8,cf_Y9,cf_Y10
0,1,374,318,319,NaN,NaN,NaN,97.88,NaN,NaN,...,2010-12,2011-12,2012-12,2013-12,2014-12,2015-12,2016-12,2017-12,2018-12,TTM
1,2,374,318,319,NaN,NaN,NaN,97.88,NaN,NaN,...,2010-12,2011-12,2012-12,2013-12,2014-12,2015-12,2016-12,2017-12,2018-12,TTM
2,3,374,318,319,NaN,NaN,NaN,97.88,NaN,NaN,...,2010-12,2011-12,2012-12,2013-12,2014-12,2015-12,2016-12,2017-12,2018-12,TTM
3,4,482,318,319,-31.63,19.64,50.56,-1.28,11.89,17.06,...,2010-12,2011-12,2012-12,2013-12,2014-12,2015-12,2016-12,2017-12,2018-12,TTM
4,23,1,318,319,NaN,51.78,51.78,NaN,NaN,NaN,...,2010-12,2011-12,2012-12,2013-12,2014-12,2015-12,2016-12,2017-12,2018-12,TTM

##### DataFrame Length

In [35]:
print('DataFrame contains {:,.0f} records.'.format(len(df_cfhealth)))

DataFrame contains 77,855 records.

##### DataFrame Columns

In [36]:
# Financial Health DataFrame Columns
(df_cfhealth.loc[0, [col for col in df_cfhealth.columns if 'Y' not in col and '_id' not in col]]
 .replace(df.colheaders['header']))

cf_cashflow                    Cash Flow Ratios
i40            Operating Cash Flow Growth % YOY
i41                 Free Cash Flow Growth % YOY
i42                      Cap Ex as a % of Sales
i43                      Free Cash Flow/Sales %
i44                   Free Cash Flow/Net Income
Name: 0, dtype: object

<a id='eff'></a>
[return to the top](#top)
### Efficiency
##### DataFrame Instance

In [37]:
df_efficiency = df.efficiency()

In [38]:
df_efficiency.head()

,ticker_id,exchange_id,ef_efficiency,i69,i69_ef_Y0,i69_ef_Y1,i69_ef_Y2,i69_ef_Y3,i69_ef_Y4,i69_ef_Y5,...,ef_Y1,ef_Y2,ef_Y3,ef_Y4,ef_Y5,ef_Y6,ef_Y7,ef_Y8,ef_Y9,ef_Y10
0,1,374,350,351,NaN,NaN,NaN,82.34,85.86,61.96,...,2010-12,2011-12,2012-12,2013-12,2014-12,2015-12,2016-12,2017-12,2018-12,TTM
1,2,374,350,351,NaN,NaN,NaN,82.34,85.86,61.96,...,2010-12,2011-12,2012-12,2013-12,2014-12,2015-12,2016-12,2017-12,2018-12,TTM
2,3,374,350,351,NaN,NaN,NaN,82.34,85.86,61.96,...,2010-12,2011-12,2012-12,2013-12,2014-12,2015-12,2016-12,2017-12,2018-12,TTM
3,4,482,350,351,25.66,28.47,27.05,29.65,30.48,32.01,...,2010-12,2011-12,2012-12,2013-12,2014-12,2015-12,2016-12,2017-12,2018-12,TTM
4,23,1,350,351,93.87,58.87,58.87,11.21,11.21,84.13,...,2010-12,2011-12,2012-12,2013-12,2014-12,2015-12,2016-12,2017-12,2018-12,TTM

##### DataFrame Length

In [39]:
print('DataFrame contains {:,.0f} records.'.format(len(df_efficiency)))

DataFrame contains 77,855 records.

##### DataFrame Columns

In [40]:
# Financial Health DataFrame Columns
(df_efficiency.loc[0, [col for col in df_efficiency.columns if 'Y' not in col and '_id' not in col]]
 .replace(df.colheaders['header']))

ef_efficiency                Efficiency
i69              Days Sales Outstanding
i70                      Days Inventory
i71                     Payables Period
i72               Cash Conversion Cycle
i73                Receivables Turnover
i74                  Inventory Turnover
i75               Fixed Assets Turnover
i76                      Asset Turnover
Name: 0, dtype: object

<a id='isa'></a>
[return to the top](#top)
### Annual Income Statement
##### DataFrame Instance

In [41]:
df_annualIS0 = df.annualIS()

In [42]:
df_annualIS = (df_master 
 .merge(df_annualIS0, on=['ticker_id', 'exchange_id']))

In [43]:
df_annualIS.head()

,ticker_id,exchange_id,ticker,company,exchange,exchange_sym,industry,sector,country,country_c2,...,label_tts4,label_tts5,currency_id,fye_month,Year_Y_1,Year_Y_2,Year_Y_3,Year_Y_4,Year_Y_5,Year_Y_6
0,1.0,374.0,OGCP,Empire State Realty OP LP Operating Partnershi...,NYSE ARCA,ARCX,REIT - Diversified,Real Estate,United States,US,...,NaN,NaN,104.0,12.0,2014-12,2015-12,2016-12,2017-12,2018-12,TTM
1,2.0,374.0,FISK,Empire State Realty OP LP Operating Partnershi...,NYSE ARCA,ARCX,REIT - Diversified,Real Estate,United States,US,...,NaN,NaN,104.0,12.0,2014-12,2015-12,2016-12,2017-12,2018-12,TTM
2,3.0,374.0,ESBA,Empire State Realty OP LP Operating Partnershi...,NYSE ARCA,ARCX,REIT - Diversified,Real Estate,United States,US,...,NaN,NaN,104.0,12.0,2014-12,2015-12,2016-12,2017-12,2018-12,TTM
3,18686.0,302.0,ARE,Alexandria Real Estate Equities Inc,"NEW YORK STOCK EXCHANGE, INC.",XNYS,REIT - Office,Real Estate,United States,US,...,NaN,NaN,104.0,12.0,2014-12,2015-12,2016-12,2017-12,2018-12,TTM
4,19275.0,302.0,LPT,Liberty Property Trust,"NEW YORK STOCK EXCHANGE, INC.",XNYS,REIT - Office,Real Estate,United States,US,...,NaN,NaN,104.0,12.0,2014-12,2015-12,2016-12,2017-12,2018-12,TTM

##### DataFrame Length

In [44]:
print('DataFrame contains {:,.0f} records.'.format(len(df_annualIS)))

DataFrame contains 68,393 records.

##### DataFrame Columns

In [45]:
labels = [col for col in df_annualIS if 'label' in col]
labels = [[label, header] for label in labels 
          for header in df_annualIS[label].unique().tolist() if pd.notna(header)]

df_labels_aIS = (pd.DataFrame(labels, columns=['header', 'value'])
                 .set_index('header')
                 .astype('int')
                )

df_labels_aIS['value'] = df_labels_aIS['value'].replace(df.colheaders['header'])
df_labels_aIS[df_labels_aIS['value'].astype('str').str.contains('ncome')].sort_values(by='value')

sorted(list(zip(df_labels_aIS.values.tolist(), df_labels_aIS.index)))

[(['Advertising and market...'], 'label_i36'),
 (['Advertising and market...'], 'label_i46'),
 (['Advertising and promot...'], 'label_i15'),
 (['Amortization of intang...'], 'label_i47'),
 (['Asset impairment'], 'label_i24'),
 (['Asset mgmt and securit...'], 'label_i4'),
 (['Basic'], 'label_i83'),
 (['Basic'], 'label_i85'),
 (['Benefits, claims and e...'], 'label_s2'),
 (['Borrowed funds'], 'label_i14'),
 (['Commissions and fees'], 'label_i22'),
 (['Compensation and benef...'], 'label_i13'),
 (['Compensation and benef...'], 'label_i32'),
 (['Compensation and benef...'], 'label_i42'),
 (['Cost of revenue'], 'label_i6'),
 (['Costs and expenses'], 'label_g3'),
 (['Credit card income'], 'label_i27'),
 (['Cumulative effect of a...'], 'label_i43'),
 (['Cumulative effect of a...'], 'label_i66'),
 (['Cumulative effect of a...'], 'label_i73'),
 (['Deposits'], 'label_i12'),
 (['Deposits with banks'], 'label_i3'),
 (['Depreciation and amort...'], 'label_i12'),
 (['Depreciation and amort...'], 'label_i13'),
 (['Depreciation and amort...'], 'label_i16'),
 (['Depreciation and amort...'], 'label_i18'),
 (['Depreciation and amort...'], 'label_i25'),
 (['Depreciation and amort...'], 'label_i26'),
 (['Depreciation and amort...'], 'label_i37'),
 (['Diluted'], 'label_i84'),
 (['Diluted'], 'label_i86'),
 (['Dividend income'], 'label_i7'),
 (['EBITDA'], 'label_i90'),
 (['Earnings per share'], 'label_g9'),
 (['Equity investment inco...'], 'label_i24'),
 (['Expenses'], 'label_g2'),
 (['Extraordinary items'], 'label_i42'),
 (['Extraordinary items'], 'label_i65'),
 (['Extraordinary items'], 'label_i72'),
 (['Federal funds purchase...'], 'label_i13'),
 (['Federal funds sold'], 'label_i4'),
 (['Gain on sale of equity...'], 'label_i25'),
 (['Gross profit'], 'label_i10'),
 (['Income (loss) from con...'], 'label_i61'),
 (['Income before income t...'], 'label_i30'),
 (['Income before income t...'], 'label_i41'),
 (['Income before income t...'], 'label_i60'),
 (['Income before income t...'], 'label_i61'),
 (['Income before taxes'], 'label_i60'),
 (['Income before taxes'], 'label_i61'),
 (['Income from discontinu...'], 'label_i64'),
 (['Income tax (expense) b...'], 'label_i62'),
 (['Income taxes'], 'label_i62'),
 (['Insurance commissions'], 'label_i28'),
 (['Insurance premium'], 'label_i28'),
 (['Interest Expense'], 'label_i31'),
 (['Interest Expense'], 'label_i51'),
 (['Interest and dividend ...'], 'label_s1'),
 (['Interest credited to p...'], 'label_i16'),
 (['Interest expense'], 'label_g2'),
 (['Interest expense'], 'label_i15'),
 (['Interest expense'], 'label_i24'),
 (['Interest expense'], 'label_i28'),
 (['Interest expense'], 'label_s2'),
 (['Interest expenses'], 'label_i23'),
 (['Interest income'], 'label_g1'),
 (['Interest income'], 'label_i11'),
 (['Interest income'], 'label_i22'),
 (['Investment banking'], 'label_i2'),
 (['Investment income, net'], 'label_i4'),
 (['Lending and deposit-re...'], 'label_i25'),
 (['Loans and Leases'], 'label_i2'),
 (['Long-term debt'], 'label_i15'),
 (['Merger, acquisition an...'], 'label_i19'),
 (['Merger, acquisition an...'], 'label_i39'),
 (['Merger, acquisition an...'], 'label_i49'),
 (['Minority interest'], 'label_i62'),
 (['Net income'], 'label_i50'),
 (['Net income'], 'label_i70'),
 (['Net income'], 'label_i80'),
 (['Net income available t...'], 'label_i82'),
 (['Net income from contin...'], 'label_i40'),
 (['Net income from contin...'], 'label_i70'),
 (['Net income from discon...'], 'label_i41'),
 (['Net income from discon...'], 'label_i71'),
 (['Net interest inc after...'], 'label_i37'),
 (['Net interest income'], 'label_i20'),
 (['Noninterest expenses'], 'label_s3'),
 (['Noninterest expenses'], 'label_s5'),
 (['Noninterest revenue'], 'label_g3'),
 (['Noninterest revenue'], 'label_s4'),
 (['Nonoperating income'], 'label_s4'),
 (['Nonrecurring expense'], 'label_i19'),
 (['Occupancy expense'], 'label_i33'),
 (['Occupancy expense'], 'label_i43'),
 (['Operating expenses'], 'label_g3'),
 (['Operating expenses'], 'label_i15'),
 (['Operating expenses'], 'label_s2'),
 (['Operating expenses'], 'label_s3'),
 (['Operating income'], 'label_i20'),
 (['Operating income'], 'label_i21'),
 (['Operating income'], 'label_i30'),
 (['Operation and maintena...'], 'label_i11'),
 (['Other'], 'label_i44'),
 (['Other'], 'label_i74'),
 (['Other assets'], 'label_i9'),
 (['Other distributions'], 'label_i63'),
 (['Other expense'], 'label_i19'),
 (['Other expenses'], 'label_i20'),
 (['Other expenses'], 'label_i41'),
 (['Other expenses'], 'label_i51'),
 (['Other income'], 'label_i12'),
 (['Other income'], 'label_i35'),
 (['Other income'], 'label_i39'),
 (['Other income'], 'label_i69'),
 (['Other income (expense)'], 'label_i23'),
 (['Other income (expense)'], 'label_i29'),
 (['Other income (expense)'], 'label_i32'),
 (['Other income (expense)'], 'label_i52'),
 (['Other income (expense)'], 'label_i63'),
 (['Other income (loss)'], 'label_i10'),
 (['Other operating expens...'], 'label_i29'),
 (['Other special charges'], 'label_i40'),
 (['Other special charges'], 'label_i50'),
 (['Policy acquisition and...'], 'label_i13'),
 (['Policyholder benefits ...'], 'label_i12'),
 (['Policyholder dividends'], 'label_i17'),
 (['Preferred distribution...'], 'label_i62'),
 (['Preferred dividend'], 'label_i81'),
 (['Preferred dividends'], 'label_i81'),
 (['Premiums'], 'label_i2'),
 (['Principal transactions'], 'label_i23'),
 (['Professional and outsi...'], 'label_i35'),
 (['Professional and outsi...'], 'label_i45'),
 (['Provision (benefit) fo...'], 'label_i62'),
 (['Provision for income t...'], 'label_i38'),
 (['Provision for income t...'], 'label_i61'),
 (['Provision for income t...'], 'label_i62'),
 (['Provision for loan los...'], 'label_i36'),
 (['Provisions for credit ...'], 'label_i36'),
 (['Realized capital gains...'], 'label_i5'),
 (['Research and developme...'], 'label_i11'),
 (['Restructuring, merger ...'], 'label_i25'),
 (['Restructuring, merger ...'], 'label_i26'),
 (['Restructuring, merger ...'], 'label_i27'),
 (['Revenue'], 'label_i1'),
 (['Revenue'], 'label_s1'),
 (['Revenues'], 'label_s1'),
 (['Revenues, net of inter...'], 'label_i20'),
 (['Sales, General and adm...'], 'label_i12'),
 (['Sales, General and adm...'], 'label_i14'),
 (['Securities'], 'label_i3'),
 (['Securities'], 'label_i5'),
 (['Securities gains (loss...'], 'label_i26'),
 (['Selling, general and a...'], 'label_i14'),
 (['Service fees and commi...'], 'label_i3'),
 (['Short-term borrowing'], 'label_i14'),
 (['Tech, communication an...'], 'label_i34'),
 (['Tech, communication an...'], 'label_i44'),
 (['Technology and occupan...'], 'label_i14'),
 (['Total benefits, claims...'], 'label_tts2'),
 (['Total costs and expens...'], 'label_ttg3'),
 (['Total expenses'], 'label_ttg2'),
 (['Total interest and div...'], 'label_tts1'),
 (['Total interest expense'], 'label_ttg2'),
 (['Total interest expense'], 'label_tts2'),
 (['Total interest income'], 'label_ttg1'),
 (['Total interest income'], 'label_tts1'),
 (['Total net revenue'], 'label_tts1'),
 (['Total noninterest expe...'], 'label_tts3'),
 (['Total noninterest expe...'], 'label_tts5'),
 (['Total noninterest reve...'], 'label_ttg3'),
 (['Total noninterest reve...'], 'label_tts4'),
 (['Total nonoperating inc...'], 'label_tts4'),
 (['Total operating expens...'], 'label_ttg3'),
 (['Total operating expens...'], 'label_tts2'),
 (['Total revenues'], 'label_tts1'),
 (['Trading assets'], 'label_i6'),
 (['Underwriting and distr...'], 'label_i12'),
 (['Weighted average share...'], 'label_g10')]

<a id='isq'></a>
[return to the top](#top)
### Quarterly Income Statements
##### DataFrame Instance

In [46]:
df_quarterlyIS = df.quarterlyIS()

In [47]:
df_quarterlyIS.head()

,ticker_id,exchange_id,data_g1_Y_1,data_g1_Y_2,data_g1_Y_3,data_g1_Y_4,data_g1_Y_5,data_g1_Y_6,data_g2_Y_1,data_g2_Y_2,...,label_tts4,label_tts5,currency_id,fye_month,Year_Y_1,Year_Y_2,Year_Y_3,Year_Y_4,Year_Y_5,Year_Y_6
0,1,374,NaN,NaN,NaN,NaN,NaN,NaN,124910000.0,133107000.0,...,NaN,NaN,104.0,12.0,2017-12,2018-03,2018-06,2018-09,2018-12,TTM
1,2,374,NaN,NaN,NaN,NaN,NaN,NaN,124910000.0,133107000.0,...,NaN,NaN,104.0,12.0,2017-12,2018-03,2018-06,2018-09,2018-12,TTM
2,3,374,NaN,NaN,NaN,NaN,NaN,NaN,124910000.0,133107000.0,...,NaN,NaN,104.0,12.0,2017-12,2018-03,2018-06,2018-09,2018-12,TTM
3,4,482,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1213.0,NaN,104.0,12.0,2017-12,2018-03,2018-06,2018-09,2018-12,TTM
4,23,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1213.0,NaN,19.0,12.0,2017-12,2018-03,2018-06,2018-09,2018-12,TTM

##### DataFrame Length

In [48]:
print('DataFrame contains {:,.0f} records.'.format(len(df_quarterlyIS)))

DataFrame contains 57,725 records.

##### DataFrame Columns

In [49]:
labels = [col for col in df_annualIS if 'label' in col]
labels = [[label, header] for label in labels 
          for header in df_annualIS[label].unique().tolist() if pd.notna(header)]

df_labels_aIS = (pd.DataFrame(labels, columns=['header', 'value'])
                 .set_index('header')
                 .astype('int')
                )

df_labels_aIS['value'] = df_labels_aIS['value'].replace(df.colheaders['header'])
df_labels_aIS[df_labels_aIS['value'].astype('str').str.contains('ncome')].sort_values(by='value')

sorted(list(zip(df_labels_aIS.values.tolist(), df_labels_aIS.index)))

[(['Advertising and market...'], 'label_i36'),
 (['Advertising and market...'], 'label_i46'),
 (['Advertising and promot...'], 'label_i15'),
 (['Amortization of intang...'], 'label_i47'),
 (['Asset impairment'], 'label_i24'),
 (['Asset mgmt and securit...'], 'label_i4'),
 (['Basic'], 'label_i83'),
 (['Basic'], 'label_i85'),
 (['Benefits, claims and e...'], 'label_s2'),
 (['Borrowed funds'], 'label_i14'),
 (['Commissions and fees'], 'label_i22'),
 (['Compensation and benef...'], 'label_i13'),
 (['Compensation and benef...'], 'label_i32'),
 (['Compensation and benef...'], 'label_i42'),
 (['Cost of revenue'], 'label_i6'),
 (['Costs and expenses'], 'label_g3'),
 (['Credit card income'], 'label_i27'),
 (['Cumulative effect of a...'], 'label_i43'),
 (['Cumulative effect of a...'], 'label_i66'),
 (['Cumulative effect of a...'], 'label_i73'),
 (['Deposits'], 'label_i12'),
 (['Deposits with banks'], 'label_i3'),
 (['Depreciation and amort...'], 'label_i12'),
 (['Depreciation and amort...'], 'label_i13'),
 (['Depreciation and amort...'], 'label_i16'),
 (['Depreciation and amort...'], 'label_i18'),
 (['Depreciation and amort...'], 'label_i25'),
 (['Depreciation and amort...'], 'label_i26'),
 (['Depreciation and amort...'], 'label_i37'),
 (['Diluted'], 'label_i84'),
 (['Diluted'], 'label_i86'),
 (['Dividend income'], 'label_i7'),
 (['EBITDA'], 'label_i90'),
 (['Earnings per share'], 'label_g9'),
 (['Equity investment inco...'], 'label_i24'),
 (['Expenses'], 'label_g2'),
 (['Extraordinary items'], 'label_i42'),
 (['Extraordinary items'], 'label_i65'),
 (['Extraordinary items'], 'label_i72'),
 (['Federal funds purchase...'], 'label_i13'),
 (['Federal funds sold'], 'label_i4'),
 (['Gain on sale of equity...'], 'label_i25'),
 (['Gross profit'], 'label_i10'),
 (['Income (loss) from con...'], 'label_i61'),
 (['Income before income t...'], 'label_i30'),
 (['Income before income t...'], 'label_i41'),
 (['Income before income t...'], 'label_i60'),
 (['Income before income t...'], 'label_i61'),
 (['Income before taxes'], 'label_i60'),
 (['Income before taxes'], 'label_i61'),
 (['Income from discontinu...'], 'label_i64'),
 (['Income tax (expense) b...'], 'label_i62'),
 (['Income taxes'], 'label_i62'),
 (['Insurance commissions'], 'label_i28'),
 (['Insurance premium'], 'label_i28'),
 (['Interest Expense'], 'label_i31'),
 (['Interest Expense'], 'label_i51'),
 (['Interest and dividend ...'], 'label_s1'),
 (['Interest credited to p...'], 'label_i16'),
 (['Interest expense'], 'label_g2'),
 (['Interest expense'], 'label_i15'),
 (['Interest expense'], 'label_i24'),
 (['Interest expense'], 'label_i28'),
 (['Interest expense'], 'label_s2'),
 (['Interest expenses'], 'label_i23'),
 (['Interest income'], 'label_g1'),
 (['Interest income'], 'label_i11'),
 (['Interest income'], 'label_i22'),
 (['Investment banking'], 'label_i2'),
 (['Investment income, net'], 'label_i4'),
 (['Lending and deposit-re...'], 'label_i25'),
 (['Loans and Leases'], 'label_i2'),
 (['Long-term debt'], 'label_i15'),
 (['Merger, acquisition an...'], 'label_i19'),
 (['Merger, acquisition an...'], 'label_i39'),
 (['Merger, acquisition an...'], 'label_i49'),
 (['Minority interest'], 'label_i62'),
 (['Net income'], 'label_i50'),
 (['Net income'], 'label_i70'),
 (['Net income'], 'label_i80'),
 (['Net income available t...'], 'label_i82'),
 (['Net income from contin...'], 'label_i40'),
 (['Net income from contin...'], 'label_i70'),
 (['Net income from discon...'], 'label_i41'),
 (['Net income from discon...'], 'label_i71'),
 (['Net interest inc after...'], 'label_i37'),
 (['Net interest income'], 'label_i20'),
 (['Noninterest expenses'], 'label_s3'),
 (['Noninterest expenses'], 'label_s5'),
 (['Noninterest revenue'], 'label_g3'),
 (['Noninterest revenue'], 'label_s4'),
 (['Nonoperating income'], 'label_s4'),
 (['Nonrecurring expense'], 'label_i19'),
 (['Occupancy expense'], 'label_i33'),
 (['Occupancy expense'], 'label_i43'),
 (['Operating expenses'], 'label_g3'),
 (['Operating expenses'], 'label_i15'),
 (['Operating expenses'], 'label_s2'),
 (['Operating expenses'], 'label_s3'),
 (['Operating income'], 'label_i20'),
 (['Operating income'], 'label_i21'),
 (['Operating income'], 'label_i30'),
 (['Operation and maintena...'], 'label_i11'),
 (['Other'], 'label_i44'),
 (['Other'], 'label_i74'),
 (['Other assets'], 'label_i9'),
 (['Other distributions'], 'label_i63'),
 (['Other expense'], 'label_i19'),
 (['Other expenses'], 'label_i20'),
 (['Other expenses'], 'label_i41'),
 (['Other expenses'], 'label_i51'),
 (['Other income'], 'label_i12'),
 (['Other income'], 'label_i35'),
 (['Other income'], 'label_i39'),
 (['Other income'], 'label_i69'),
 (['Other income (expense)'], 'label_i23'),
 (['Other income (expense)'], 'label_i29'),
 (['Other income (expense)'], 'label_i32'),
 (['Other income (expense)'], 'label_i52'),
 (['Other income (expense)'], 'label_i63'),
 (['Other income (loss)'], 'label_i10'),
 (['Other operating expens...'], 'label_i29'),
 (['Other special charges'], 'label_i40'),
 (['Other special charges'], 'label_i50'),
 (['Policy acquisition and...'], 'label_i13'),
 (['Policyholder benefits ...'], 'label_i12'),
 (['Policyholder dividends'], 'label_i17'),
 (['Preferred distribution...'], 'label_i62'),
 (['Preferred dividend'], 'label_i81'),
 (['Preferred dividends'], 'label_i81'),
 (['Premiums'], 'label_i2'),
 (['Principal transactions'], 'label_i23'),
 (['Professional and outsi...'], 'label_i35'),
 (['Professional and outsi...'], 'label_i45'),
 (['Provision (benefit) fo...'], 'label_i62'),
 (['Provision for income t...'], 'label_i38'),
 (['Provision for income t...'], 'label_i61'),
 (['Provision for income t...'], 'label_i62'),
 (['Provision for loan los...'], 'label_i36'),
 (['Provisions for credit ...'], 'label_i36'),
 (['Realized capital gains...'], 'label_i5'),
 (['Research and developme...'], 'label_i11'),
 (['Restructuring, merger ...'], 'label_i25'),
 (['Restructuring, merger ...'], 'label_i26'),
 (['Restructuring, merger ...'], 'label_i27'),
 (['Revenue'], 'label_i1'),
 (['Revenue'], 'label_s1'),
 (['Revenues'], 'label_s1'),
 (['Revenues, net of inter...'], 'label_i20'),
 (['Sales, General and adm...'], 'label_i12'),
 (['Sales, General and adm...'], 'label_i14'),
 (['Securities'], 'label_i3'),
 (['Securities'], 'label_i5'),
 (['Securities gains (loss...'], 'label_i26'),
 (['Selling, general and a...'], 'label_i14'),
 (['Service fees and commi...'], 'label_i3'),
 (['Short-term borrowing'], 'label_i14'),
 (['Tech, communication an...'], 'label_i34'),
 (['Tech, communication an...'], 'label_i44'),
 (['Technology and occupan...'], 'label_i14'),
 (['Total benefits, claims...'], 'label_tts2'),
 (['Total costs and expens...'], 'label_ttg3'),
 (['Total expenses'], 'label_ttg2'),
 (['Total interest and div...'], 'label_tts1'),
 (['Total interest expense'], 'label_ttg2'),
 (['Total interest expense'], 'label_tts2'),
 (['Total interest income'], 'label_ttg1'),
 (['Total interest income'], 'label_tts1'),
 (['Total net revenue'], 'label_tts1'),
 (['Total noninterest expe...'], 'label_tts3'),
 (['Total noninterest expe...'], 'label_tts5'),
 (['Total noninterest reve...'], 'label_ttg3'),
 (['Total noninterest reve...'], 'label_tts4'),
 (['Total nonoperating inc...'], 'label_tts4'),
 (['Total operating expens...'], 'label_ttg3'),
 (['Total operating expens...'], 'label_tts2'),
 (['Total revenues'], 'label_tts1'),
 (['Trading assets'], 'label_i6'),
 (['Underwriting and distr...'], 'label_i12'),
 (['Weighted average share...'], 'label_g10')]

<a id='bsa'></a>
[return to the top](#top)
### Annual Balance Sheet
##### DataFrame Instance

In [50]:
df_annualBS = df.annualBS()

In [51]:
df_annualBS.head()

,ticker_id,exchange_id,data_g1_Y_1,data_g1_Y_2,data_g1_Y_3,data_g1_Y_4,data_g1_Y_5,data_g2_Y_1,data_g2_Y_2,data_g2_Y_3,...,label_ttgg6,label_tts1,label_tts2,currency_id,fye_month,Year_Y_1,Year_Y_2,Year_Y_3,Year_Y_4,Year_Y_5
0,1,374,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,10.0,29,104.0,12.0,2014-12,2015-12,2016-12,2017-12,2018-12
1,2,374,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,10.0,29,104.0,12.0,2014-12,2015-12,2016-12,2017-12,2018-12
2,3,374,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,10.0,29,104.0,12.0,2014-12,2015-12,2016-12,2017-12,2018-12
3,4,482,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,10.0,29,104.0,12.0,2014-12,2015-12,2016-12,2017-12,2018-12
4,23,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,10.0,29,19.0,12.0,2014-12,2015-12,2016-12,2017-12,2018-12

##### DataFrame Length

In [52]:
print('DataFrame contains {:,.0f} records.'.format(len(df_annualBS)))

DataFrame contains 77,984 records.

##### DataFrame Columns

In [53]:
labels = [col for col in df_annualBS if 'label' in col]
labels = [[label, header] for label in labels 
          for header in df_annualBS[label].unique().tolist() if pd.notna(header)]

df_labels_aBS = (pd.DataFrame(labels, columns=['header', 'value'])
                 .set_index('header')
                 .astype('int')
                )

df_labels_aBS['value'] = df_labels_aBS['value'].replace(df.colheaders['header'])
df_labels_aBS[df_labels_aBS['value'].astype('str').str.contains('ncome')].sort_values(by='value')

sorted(list(zip(df_labels_aBS.values.tolist(), df_labels_aBS.index)))

[(['Accounts payable'], 'label_i41'),
 (['Accounts payable'], 'label_i42'),
 (['Accounts payable'], 'label_i43'),
 (['Accrued expenses and l...'], 'label_i46'),
 (['Accrued expenses and l...'], 'label_i47'),
 (['Accrued investment inc...'], 'label_i8'),
 (['Accrued liabilities'], 'label_i45'),
 (['Accrued liabilities'], 'label_i46'),
 (['Accrued liabilities'], 'label_i53'),
 (['Accumulated Depreciati...'], 'label_i10'),
 (['Accumulated Depreciati...'], 'label_i14'),
 (['Accumulated depreciati...'], 'label_i2'),
 (['Accumulated other comp...'], 'label_i89'),
 (['Additional paid-in cap...'], 'label_i84'),
 (['Allowance for loan los...'], 'label_i12'),
 (['Allowance for loan los...'], 'label_i9'),
 (['Assets'], 'label_g1'),
 (['Assets'], 'label_s1'),
 (['Buildings and improvem...'], 'label_i10'),
 (['Capital leases'], 'label_i42'),
 (['Capital leases'], 'label_i43'),
 (['Capital leases'], 'label_i51'),
 (['Cash'], 'label_gg1'),
 (['Cash and cash equivale...'], 'label_i1'),
 (['Cash and cash equivale...'], 'label_i4'),
 (['Cash and cash equivale...'], 'label_i7'),
 (['Cash and due from bank...'], 'label_i1'),
 (['Commercial loans'], 'label_i8'),
 (['Common stock'], 'label_i82'),
 (['Consumer loans'], 'label_i10'),
 (['Current assets'], 'label_g1'),
 (['Current liabilities'], 'label_gg5'),
 (['Debt securities'], 'label_i7'),
 (['Deferred income tax as...'], 'label_i11'),
 (['Deferred income taxes'], 'label_i14'),
 (['Deferred income taxes'], 'label_i15'),
 (['Deferred income taxes'], 'label_i18'),
 (['Deferred income taxes'], 'label_i43'),
 (['Deferred income taxes'], 'label_i44'),
 (['Deferred income taxes'], 'label_i46'),
 (['Deferred income taxes'], 'label_i5'),
 (['Deferred income taxes'], 'label_i6'),
 (['Deferred policy acquis...'], 'label_i10'),
 (['Deferred revenues'], 'label_i46'),
 (['Deferred revenues'], 'label_i47'),
 (['Deferred revenues'], 'label_i54'),
 (['Deferred tax liabiliti...'], 'label_i52'),
 (['Deferred taxes'], 'label_i46'),
 (['Deferred taxes liabili...'], 'label_i52'),
 (['Deposits'], 'label_gg5'),
 (['Deposits'], 'label_i41'),
 (['Deposits'], 'label_i45'),
 (['Deposits with banks'], 'label_i2'),
 (['Derivative assets'], 'label_i6'),
 (['Derivative liabilities'], 'label_i44'),
 (['Dividends payable'], 'label_i47'),
 (['Equity and other inves...'], 'label_i11'),
 (['Equity and other inves...'], 'label_i12'),
 (['Equity and other inves...'], 'label_i15'),
 (['Equity securities'], 'label_i2'),
 (['Federal Home Loan Bank...'], 'label_i6'),
 (['Federal funds purchase...'], 'label_i42'),
 (['Federal funds sold'], 'label_i10'),
 (['Federal funds sold'], 'label_i3'),
 (['Fixed maturity securit...'], 'label_i1'),
 (['Fixtures and equipment'], 'label_i11'),
 (['Foreclosed real estate...'], 'label_i30'),
 (['Future policy benefits'], 'label_i41'),
 (['General Partner'], 'label_i87'),
 (['Goodwill'], 'label_i12'),
 (['Goodwill'], 'label_i13'),
 (['Goodwill'], 'label_i16'),
 (['Goodwill'], 'label_i7'),
 (['Goodwill'], 'label_i8'),
 (['Gross property, plant ...'], 'label_i9'),
 (['Income taxes payable'], 'label_i45'),
 (['Intangible assets'], 'label_i13'),
 (['Intangible assets'], 'label_i14'),
 (['Intangible assets'], 'label_i17'),
 (['Intangible assets'], 'label_i9'),
 (['Interest receivable'], 'label_i14'),
 (['Interest-bearing'], 'label_i42'),
 (['Inventories'], 'label_i4'),
 (['Investments'], 'label_i3'),
 (['Land'], 'label_i9'),
 (['Liabilities'], 'label_g5'),
 (['Liabilities and stockh...'], 'label_s2'),
 (['Loans'], 'label_gg3'),
 (['Loans'], 'label_i30'),
 (['Loans'], 'label_i4'),
 (['Loans'], 'label_i8'),
 (['Loans, total'], 'label_i4'),
 (['Long-term debt'], 'label_i42'),
 (['Long-term debt'], 'label_i44'),
 (['Long-term debt'], 'label_i45'),
 (['Long-term debt'], 'label_i46'),
 (['Long-term debt'], 'label_i47'),
 (['Long-term debt'], 'label_i50'),
 (['Minority Interest'], 'label_i47'),
 (['Minority interest'], 'label_i56'),
 (['Net loans'], 'label_i10'),
 (['Net property, plant an...'], 'label_ttgg2'),
 (['Non-current assets'], 'label_g2'),
 (['Non-current liabilitie...'], 'label_gg6'),
 (['Non-interest-bearing'], 'label_i41'),
 (['Other Equity'], 'label_i83'),
 (['Other assets'], 'label_i11'),
 (['Other assets'], 'label_i16'),
 (['Other assets'], 'label_i19'),
 (['Other assets'], 'label_i40'),
 (['Other assets'], 'label_i8'),
 (['Other current assets'], 'label_i8'),
 (['Other current liabilit...'], 'label_i49'),
 (['Other equity'], 'label_i83'),
 (['Other intangible asset...'], 'label_i14'),
 (['Other intangible asset...'], 'label_i8'),
 (['Other intangibles'], 'label_i17'),
 (['Other liabilities'], 'label_i49'),
 (['Other liabilities'], 'label_i50'),
 (['Other liabilities'], 'label_i80'),
 (['Other liabilities and ...'], 'label_i95'),
 (['Other long-term assets'], 'label_i17'),
 (['Other long-term assets'], 'label_i18'),
 (['Other long-term assets'], 'label_i21'),
 (['Other long-term liabil...'], 'label_i58'),
 (['Other properties'], 'label_i13'),
 (['Payables'], 'label_i43'),
 (['Payables'], 'label_i45'),
 (['Payables and accrued e...'], 'label_i43'),
 (['Payables and accrued e...'], 'label_i44'),
 (['Pensions and other ben...'], 'label_i55'),
 (['Pensions and other pos...'], 'label_i55'),
 (['Policyholder funds'], 'label_i42'),
 (['Preferred stock'], 'label_i81'),
 (['Premises and equipment'], 'label_i12'),
 (['Premises and equipment'], 'label_i7'),
 (['Premises and equipment...'], 'label_i15'),
 (['Premiums and other rec...'], 'label_i9'),
 (['Prepaid expenses'], 'label_i6'),
 (['Prepaid pension benefi...'], 'label_i15'),
 (['Prepaid pension costs'], 'label_i16'),
 (['Prepaid pension costs'], 'label_i19'),
 (['Property and equipment'], 'label_i12'),
 (['Property and equipment'], 'label_i5'),
 (['Property and equipment...'], 'label_i12'),
 (['Property, plant and eq...'], 'label_gg2'),
 (['Property, plant and eq...'], 'label_ttgg2'),
 (['Real estate'], 'label_i5'),
 (['Real estate properties'], 'label_i1'),
 (['Real estate properties...'], 'label_i3'),
 (['Receivables'], 'label_i11'),
 (['Receivables'], 'label_i2'),
 (['Receivables'], 'label_i3'),
 (['Receivables'], 'label_i6'),
 (['Regulatory assets'], 'label_i30'),
 (['Regulatory liabilities'], 'label_i70'),
 (['Repurchase agreement'], 'label_i43'),
 (['Residential loans'], 'label_i9'),
 (['Restricted cash'], 'label_i30'),
 (['Restricted cash'], 'label_i5'),
 (['Restricted cash'], 'label_i9'),
 (['Restricted cash and ca...'], 'label_i2'),
 (['Retained earnings'], 'label_i85'),
 (['Securities'], 'label_gg2'),
 (['Securities and investm...'], 'label_i4'),
 (['Securities available f...'], 'label_i4'),
 (['Securities borrowed'], 'label_i4'),
 (['Securities borrowed'], 'label_i5'),
 (['Securities held to mat...'], 'label_i5'),
 (['Securities purchased u...'], 'label_i7'),
 (['Separate account asset...'], 'label_i14'),
 (['Separate account liabi...'], 'label_i48'),
 (['Short-term borrowing'], 'label_i41'),
 (['Short-term borrowing'], 'label_i42'),
 (['Short-term borrowing'], 'label_i45'),
 (['Short-term borrowing'], 'label_i46'),
 (['Short-term debt'], 'label_i41'),
 (['Short-term debt'], 'label_i42'),
 (['Short-term debt'], 'label_i44'),
 (['Short-term investments'], 'label_i2'),
 (['Short-term investments'], 'label_i6'),
 (['Stockholders equity'], 'label_g8'),
 (['Taxes payable'], 'label_i44'),
 (['Taxes payable'], 'label_i45'),
 (['Taxes payable'], 'label_i47'),
 (['Total Stockholders eq...'], 'label_ttg8'),
 (['Total assets'], 'label_ttg1'),
 (['Total assets'], 'label_tts1'),
 (['Total cash'], 'label_ttgg1'),
 (['Total cash and cash eq...'], 'label_ttgg1'),
 (['Total current assets'], 'label_ttg1'),
 (['Total current liabilit...'], 'label_ttgg5'),
 (['Total deposits'], 'label_ttgg5'),
 (['Total liabilities'], 'label_ttg5'),
 (['Total liabilities and ...'], 'label_tts2'),
 (['Total loans'], 'label_i11'),
 (['Total loans, net'], 'label_ttgg3'),
 (['Total non-current asse...'], 'label_ttg2'),
 (['Total non-current liab...'], 'label_ttgg6'),
 (['Total securities'], 'label_ttgg2'),
 (['Total stockholders eq...'], 'label_ttg8'),
 (['Trading account securi...'], 'label_i3'),
 (['Trading assets'], 'label_i5'),
 (['Trading liabilities'], 'label_i43'),
 (['Trading liabilities'], 'label_i44'),
 (['Trading securities'], 'label_i3'),
 (['Treasury stock'], 'label_i86'),
 (['Unearned premiums'], 'label_i43'),
 (['stockholders equity'], 'label_g8')]

<a id='bsq'></a>
[return to the top](#top)
### Quarterly Balance Sheet
##### DataFrame Instance

In [54]:
df_quarterlyBS = df.quarterlyBS()

In [55]:
df_quarterlyBS.head()

,ticker_id,exchange_id,data_g1_Y_1,data_g1_Y_2,data_g1_Y_3,data_g1_Y_4,data_g1_Y_5,data_g2_Y_1,data_g2_Y_2,data_g2_Y_3,...,label_ttgg6,label_tts1,label_tts2,currency_id,fye_month,Year_Y_1,Year_Y_2,Year_Y_3,Year_Y_4,Year_Y_5
0,1,374,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,10.0,29,104.0,12.0,2017-12,2018-03,2018-06,2018-09,2018-12
1,2,374,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,10.0,29,104.0,12.0,2017-12,2018-03,2018-06,2018-09,2018-12
2,3,374,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,10.0,29,104.0,12.0,2017-12,2018-03,2018-06,2018-09,2018-12
3,4,482,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,10.0,29,104.0,12.0,2017-12,2018-03,2018-06,2018-09,2018-12
4,23,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,10.0,29,19.0,12.0,2017-12,2018-03,2018-06,2018-09,2018-12

##### DataFrame Length

In [56]:
print('DataFrame contains {:,.0f} records.'.format(len(df_quarterlyBS)))

DataFrame contains 77,753 records.

##### DataFrame Columns

In [70]:
labels = [col for col in df_quarterlyBS if 'label' in col]
labels = [[label, header] for label in labels 
          for header in df_quarterlyBS[label].unique().tolist() if pd.notna(header)]

df_labels_qBS = (pd.DataFrame(labels, columns=['header', 'value'])
                 .set_index('header')
                 .astype('int')
                )

df_labels_qBS['value'] = df_labels_qBS['value'].replace(df.colheaders['header'])
df_labels_qBS[df_labels_qBS['value'].astype('str').str.contains('ncome')].sort_values(by='value')

sorted(list(zip(df_labels_qBS.values.tolist(), df_labels_qBS.index)))

[(['Accounts payable'], 'label_i41'),
 (['Accounts payable'], 'label_i42'),
 (['Accounts payable'], 'label_i43'),
 (['Accrued expenses and l...'], 'label_i46'),
 (['Accrued expenses and l...'], 'label_i47'),
 (['Accrued investment inc...'], 'label_i8'),
 (['Accrued liabilities'], 'label_i45'),
 (['Accrued liabilities'], 'label_i46'),
 (['Accrued liabilities'], 'label_i53'),
 (['Accumulated Depreciati...'], 'label_i10'),
 (['Accumulated Depreciati...'], 'label_i14'),
 (['Accumulated depreciati...'], 'label_i2'),
 (['Accumulated other comp...'], 'label_i89'),
 (['Additional paid-in cap...'], 'label_i84'),
 (['Allowance for loan los...'], 'label_i12'),
 (['Allowance for loan los...'], 'label_i9'),
 (['Assets'], 'label_g1'),
 (['Assets'], 'label_s1'),
 (['Buildings and improvem...'], 'label_i10'),
 (['Capital leases'], 'label_i42'),
 (['Capital leases'], 'label_i43'),
 (['Capital leases'], 'label_i51'),
 (['Cash'], 'label_gg1'),
 (['Cash and cash equivale...'], 'label_i1'),
 (['Cash and cash equivale...'], 'label_i4'),
 (['Cash and cash equivale...'], 'label_i7'),
 (['Cash and due from bank...'], 'label_i1'),
 (['Commercial loans'], 'label_i8'),
 (['Common stock'], 'label_i82'),
 (['Consumer loans'], 'label_i10'),
 (['Current assets'], 'label_g1'),
 (['Current liabilities'], 'label_gg5'),
 (['Debt securities'], 'label_i7'),
 (['Deferred income tax as...'], 'label_i11'),
 (['Deferred income taxes'], 'label_i14'),
 (['Deferred income taxes'], 'label_i15'),
 (['Deferred income taxes'], 'label_i18'),
 (['Deferred income taxes'], 'label_i43'),
 (['Deferred income taxes'], 'label_i44'),
 (['Deferred income taxes'], 'label_i46'),
 (['Deferred income taxes'], 'label_i5'),
 (['Deferred income taxes'], 'label_i6'),
 (['Deferred policy acquis...'], 'label_i10'),
 (['Deferred revenues'], 'label_i46'),
 (['Deferred revenues'], 'label_i47'),
 (['Deferred revenues'], 'label_i54'),
 (['Deferred tax liabiliti...'], 'label_i52'),
 (['Deferred taxes'], 'label_i46'),
 (['Deferred taxes liabili...'], 'label_i52'),
 (['Deposits'], 'label_gg5'),
 (['Deposits'], 'label_i41'),
 (['Deposits'], 'label_i45'),
 (['Deposits with banks'], 'label_i2'),
 (['Derivative assets'], 'label_i6'),
 (['Derivative liabilities'], 'label_i44'),
 (['Dividends payable'], 'label_i47'),
 (['Equity and other inves...'], 'label_i11'),
 (['Equity and other inves...'], 'label_i12'),
 (['Equity and other inves...'], 'label_i15'),
 (['Equity securities'], 'label_i2'),
 (['Federal Home Loan Bank...'], 'label_i6'),
 (['Federal funds purchase...'], 'label_i42'),
 (['Federal funds sold'], 'label_i10'),
 (['Federal funds sold'], 'label_i3'),
 (['Fixed maturity securit...'], 'label_i1'),
 (['Fixtures and equipment'], 'label_i11'),
 (['Foreclosed real estate...'], 'label_i30'),
 (['Future policy benefits'], 'label_i41'),
 (['General Partner'], 'label_i87'),
 (['Goodwill'], 'label_i12'),
 (['Goodwill'], 'label_i13'),
 (['Goodwill'], 'label_i16'),
 (['Goodwill'], 'label_i7'),
 (['Goodwill'], 'label_i8'),
 (['Gross property, plant ...'], 'label_i9'),
 (['Income taxes payable'], 'label_i45'),
 (['Intangible assets'], 'label_i13'),
 (['Intangible assets'], 'label_i14'),
 (['Intangible assets'], 'label_i17'),
 (['Intangible assets'], 'label_i9'),
 (['Interest receivable'], 'label_i14'),
 (['Interest-bearing'], 'label_i42'),
 (['Inventories'], 'label_i4'),
 (['Investments'], 'label_i3'),
 (['Land'], 'label_i9'),
 (['Liabilities'], 'label_g5'),
 (['Liabilities and stockh...'], 'label_s2'),
 (['Loans'], 'label_gg3'),
 (['Loans'], 'label_i30'),
 (['Loans'], 'label_i4'),
 (['Loans'], 'label_i8'),
 (['Loans, total'], 'label_i4'),
 (['Long-term debt'], 'label_i42'),
 (['Long-term debt'], 'label_i44'),
 (['Long-term debt'], 'label_i45'),
 (['Long-term debt'], 'label_i46'),
 (['Long-term debt'], 'label_i47'),
 (['Long-term debt'], 'label_i50'),
 (['Minority Interest'], 'label_i47'),
 (['Minority interest'], 'label_i56'),
 (['Net loans'], 'label_i10'),
 (['Net property, plant an...'], 'label_ttgg2'),
 (['Non-current assets'], 'label_g2'),
 (['Non-current liabilitie...'], 'label_gg6'),
 (['Non-interest-bearing'], 'label_i41'),
 (['Other Equity'], 'label_i83'),
 (['Other assets'], 'label_i11'),
 (['Other assets'], 'label_i16'),
 (['Other assets'], 'label_i19'),
 (['Other assets'], 'label_i40'),
 (['Other assets'], 'label_i8'),
 (['Other current assets'], 'label_i8'),
 (['Other current liabilit...'], 'label_i49'),
 (['Other equity'], 'label_i83'),
 (['Other intangible asset...'], 'label_i14'),
 (['Other intangible asset...'], 'label_i8'),
 (['Other intangibles'], 'label_i17'),
 (['Other liabilities'], 'label_i49'),
 (['Other liabilities'], 'label_i50'),
 (['Other liabilities'], 'label_i80'),
 (['Other liabilities and ...'], 'label_i95'),
 (['Other long-term assets'], 'label_i17'),
 (['Other long-term assets'], 'label_i18'),
 (['Other long-term assets'], 'label_i21'),
 (['Other long-term liabil...'], 'label_i58'),
 (['Other properties'], 'label_i13'),
 (['Payables'], 'label_i43'),
 (['Payables'], 'label_i45'),
 (['Payables and accrued e...'], 'label_i43'),
 (['Payables and accrued e...'], 'label_i44'),
 (['Pensions and other ben...'], 'label_i55'),
 (['Pensions and other pos...'], 'label_i55'),
 (['Policyholder funds'], 'label_i42'),
 (['Preferred stock'], 'label_i81'),
 (['Premises and equipment'], 'label_i12'),
 (['Premises and equipment'], 'label_i7'),
 (['Premises and equipment...'], 'label_i15'),
 (['Premiums and other rec...'], 'label_i9'),
 (['Prepaid expenses'], 'label_i6'),
 (['Prepaid pension benefi...'], 'label_i15'),
 (['Prepaid pension costs'], 'label_i16'),
 (['Prepaid pension costs'], 'label_i19'),
 (['Property and equipment'], 'label_i12'),
 (['Property and equipment'], 'label_i5'),
 (['Property and equipment...'], 'label_i12'),
 (['Property, plant and eq...'], 'label_gg2'),
 (['Property, plant and eq...'], 'label_ttgg2'),
 (['Real estate'], 'label_i5'),
 (['Real estate properties'], 'label_i1'),
 (['Real estate properties...'], 'label_i3'),
 (['Receivables'], 'label_i11'),
 (['Receivables'], 'label_i2'),
 (['Receivables'], 'label_i3'),
 (['Receivables'], 'label_i6'),
 (['Regulatory assets'], 'label_i30'),
 (['Regulatory liabilities'], 'label_i70'),
 (['Repurchase agreement'], 'label_i43'),
 (['Residential loans'], 'label_i9'),
 (['Restricted cash'], 'label_i30'),
 (['Restricted cash'], 'label_i5'),
 (['Restricted cash'], 'label_i9'),
 (['Restricted cash and ca...'], 'label_i2'),
 (['Retained earnings'], 'label_i85'),
 (['Securities'], 'label_gg2'),
 (['Securities and investm...'], 'label_i4'),
 (['Securities available f...'], 'label_i4'),
 (['Securities borrowed'], 'label_i4'),
 (['Securities borrowed'], 'label_i5'),
 (['Securities held to mat...'], 'label_i5'),
 (['Securities purchased u...'], 'label_i7'),
 (['Separate account asset...'], 'label_i14'),
 (['Separate account liabi...'], 'label_i48'),
 (['Short-term borrowing'], 'label_i41'),
 (['Short-term borrowing'], 'label_i42'),
 (['Short-term borrowing'], 'label_i45'),
 (['Short-term borrowing'], 'label_i46'),
 (['Short-term debt'], 'label_i41'),
 (['Short-term debt'], 'label_i42'),
 (['Short-term debt'], 'label_i44'),
 (['Short-term investments'], 'label_i2'),
 (['Short-term investments'], 'label_i6'),
 (['Stockholders equity'], 'label_g8'),
 (['Taxes payable'], 'label_i44'),
 (['Taxes payable'], 'label_i45'),
 (['Taxes payable'], 'label_i47'),
 (['Total Stockholders eq...'], 'label_ttg8'),
 (['Total assets'], 'label_ttg1'),
 (['Total assets'], 'label_tts1'),
 (['Total cash'], 'label_ttgg1'),
 (['Total cash and cash eq...'], 'label_ttgg1'),
 (['Total current assets'], 'label_ttg1'),
 (['Total current liabilit...'], 'label_ttgg5'),
 (['Total deposits'], 'label_ttgg5'),
 (['Total liabilities'], 'label_ttg5'),
 (['Total liabilities and ...'], 'label_tts2'),
 (['Total loans'], 'label_i11'),
 (['Total loans, net'], 'label_ttgg3'),
 (['Total non-current asse...'], 'label_ttg2'),
 (['Total non-current liab...'], 'label_ttgg6'),
 (['Total securities'], 'label_ttgg2'),
 (['Total stockholders eq...'], 'label_ttg8'),
 (['Trading account securi...'], 'label_i3'),
 (['Trading assets'], 'label_i5'),
 (['Trading liabilities'], 'label_i43'),
 (['Trading liabilities'], 'label_i44'),
 (['Trading securities'], 'label_i3'),
 (['Treasury stock'], 'label_i86'),
 (['Unearned premiums'], 'label_i43'),
 (['stockholders equity'], 'label_g8')]

<a id='cfa'></a>
[return to the top](#top)
### Annual Cash Flow Statement
##### DataFrame Instance

In [58]:
df_annualCF = df.annualCF()

In [59]:
df_annualCF.head()

,ticker_id,exchange_id,data_i1_Y_1,data_i1_Y_2,data_i1_Y_3,data_i1_Y_4,data_i1_Y_5,data_i1_Y_6,data_i10_Y_1,data_i10_Y_2,...,label_tts2,label_tts3,currency_id,fye_month,Year_Y_1,Year_Y_2,Year_Y_3,Year_Y_4,Year_Y_5,Year_Y_6
0,1,374,NaN,NaN,NaN,NaN,NaN,NaN,3720000.0,5483000.0,...,120,133,104.0,12.0,2014-12,2015-12,2016-12,2017-12,2018-12,TTM
1,2,374,NaN,NaN,NaN,NaN,NaN,NaN,3720000.0,5483000.0,...,120,133,104.0,12.0,2014-12,2015-12,2016-12,2017-12,2018-12,TTM
2,3,374,NaN,NaN,NaN,NaN,NaN,NaN,3720000.0,5483000.0,...,120,133,104.0,12.0,2014-12,2015-12,2016-12,2017-12,2018-12,TTM
3,4,482,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,120,133,104.0,12.0,2014-12,2015-12,2016-12,2017-12,2018-12,TTM
4,23,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,227000.0,...,120,133,19.0,12.0,2014-12,2015-12,2016-12,2017-12,2018-12,TTM

##### DataFrame Length

In [60]:
print('DataFrame contains {:,.0f} records.'.format(len(df_annualCF)))

DataFrame contains 77,444 records.

##### DataFrame Columns

In [72]:
labels = [col for col in df_annualCF if 'label' in col]
labels = [[label, header] for label in labels 
          for header in df_annualCF[label].unique().tolist() if pd.notna(header)]

df_labels_aCF = (pd.DataFrame(labels, columns=['header', 'value'])
                 .set_index('header')
                 .astype('int')
                )

df_labels_aCF['value'] = df_labels_aCF['value'].replace(df.colheaders['header'])
df_labels_aCF[df_labels_aCF['value'].astype('str').str.contains('ncome')].sort_values(by='value')

sorted(list(zip(df_labels_aCF.values.tolist(), df_labels_aCF.index)))

[(['(Gain) Loss from disco...'], 'label_i3'),
 (['(Gain) Loss from disco...'], 'label_i7'),
 (['(Gains) loss on dispos...'], 'label_i11'),
 (['(Gains) loss on dispos...'], 'label_i12'),
 (['Accounts payable'], 'label_i19'),
 (['Accounts payable'], 'label_i20'),
 (['Accounts receivable'], 'label_i16'),
 (['Accrued liabilities'], 'label_i20'),
 (['Accrued liabilities'], 'label_i21'),
 (['Accrued liabilities'], 'label_i30'),
 (['Acquisitions and dispo...'], 'label_i33'),
 (['Acquisitions and dispo...'], 'label_i36'),
 (['Acquisitions and dispo...'], 'label_i43'),
 (['Acquisitions, net'], 'label_i33'),
 (['Amortization of debt a...'], 'label_i7'),
 (['Amortization of debt d...'], 'label_i10'),
 (['Amortization of debt d...'], 'label_i3'),
 (['Amortization of debt d...'], 'label_i7'),
 (['Capital expenditure'], 'label_i96'),
 (['Capitalization of defe...'], 'label_i24'),
 (['Cash Flows From Financ...'], 'label_s3'),
 (['Cash Flows From Invest...'], 'label_s2'),
 (['Cash Flows From Operat...'], 'label_s1'),
 (['Cash at beginning of p...'], 'label_i94'),
 (['Cash at end of period'], 'label_i95'),
 (['Cash dividends paid'], 'label_i69'),
 (['Cash dividends paid'], 'label_i70'),
 (['Cash dividends paid'], 'label_i72'),
 (['Cash paid for income t...'], 'label_i98'),
 (['Cash paid for interest'], 'label_i99'),
 (['Change in deposits'], 'label_i61'),
 (['Change in deposits wit...'], 'label_i31'),
 (['Change in federal fund...'], 'label_i32'),
 (['Change in federal fund...'], 'label_i62'),
 (['Change in short-term b...'], 'label_i61'),
 (['Change in short-term b...'], 'label_i63'),
 (['Change in working capi...'], 'label_i15'),
 (['Changes in loans, net'], 'label_i35'),
 (['Common stock issued'], 'label_i64'),
 (['Common stock issued'], 'label_i65'),
 (['Common stock issued'], 'label_i66'),
 (['Common stock issued'], 'label_i67'),
 (['Common stock repurchas...'], 'label_i67'),
 (['Cumulative effect of a...'], 'label_i5'),
 (['Cumulative effect of a...'], 'label_i9'),
 (['Debt issued'], 'label_i61'),
 (['Debt issued'], 'label_i63'),
 (['Debt repayment'], 'label_i62'),
 (['Debt repayment'], 'label_i64'),
 (['Deferred charges'], 'label_i23'),
 (['Deferred income taxes'], 'label_i6'),
 (['Deferred tax (benefit)...'], 'label_i11'),
 (['Deferred tax (benefit)...'], 'label_i9'),
 (['Deferred tax(benefit) ...'], 'label_i6'),
 (['Depreciation & amortiz...'], 'label_i2'),
 (['Depreciation & amortiz...'], 'label_i5'),
 (['Depreciation & amortiz...'], 'label_i6'),
 (['Dividend paid'], 'label_i69'),
 (['Dividend paid'], 'label_i71'),
 (['Dividend payable'], 'label_i70'),
 (['Dividend payable'], 'label_i71'),
 (['Dividend payable'], 'label_i72'),
 (['Dividend payable'], 'label_i73'),
 (['Effect of exchange rat...'], 'label_i91'),
 (['Equity in (income) los...'], 'label_i4'),
 (['Excess tax benefit fro...'], 'label_i63'),
 (['Excess tax benefit fro...'], 'label_i64'),
 (['Excess tax benefit fro...'], 'label_i65'),
 (['Excess tax benefit fro...'], 'label_i66'),
 (['Excess tax benefit fro...'], 'label_i68'),
 (['Extraordinary items'], 'label_i4'),
 (['Extraordinary items'], 'label_i8'),
 (['Free Cash Flow'], 'label_g7'),
 (['Free cash flow'], 'label_i97'),
 (['Fund held under reinsu...'], 'label_i26'),
 (['Income taxes payable'], 'label_i22'),
 (['Income taxes payable'], 'label_i23'),
 (['Income taxes payable'], 'label_i32'),
 (['Interest payable'], 'label_i21'),
 (['Interest payable'], 'label_i22'),
 (['Interest payable'], 'label_i31'),
 (['Inventory'], 'label_i17'),
 (['Investment income due ...'], 'label_i25'),
 (['Investment/asset impai...'], 'label_i4'),
 (['Investment/asset impai...'], 'label_i6'),
 (['Investment/asset impai...'], 'label_i8'),
 (['Investments (gains) lo...'], 'label_i10'),
 (['Investments (gains) lo...'], 'label_i3'),
 (['Investments (gains) lo...'], 'label_i5'),
 (['Investments in propert...'], 'label_i31'),
 (['Investments in technol...'], 'label_i36'),
 (['Investments losses (ga...'], 'label_i5'),
 (['Loans'], 'label_i17'),
 (['Loans issued'], 'label_i45'),
 (['Long-term debt issued'], 'label_i62'),
 (['Long-term debt issued'], 'label_i64'),
 (['Long-term debt repayme...'], 'label_i63'),
 (['Long-term debt repayme...'], 'label_i65'),
 (['Net cash provided by (...'], 'label_i92'),
 (['Net cash provided by (...'], 'label_tts3'),
 (['Net cash provided by o...'], 'label_tts1'),
 (['Net cash used for inve...'], 'label_tts2'),
 (['Net change in cash'], 'label_i93'),
 (['Net income'], 'label_i1'),
 (['Operating cash flow'], 'label_i100'),
 (['Other assets and liabi...'], 'label_i24'),
 (['Other assets and liabi...'], 'label_i34'),
 (['Other current assets'], 'label_i19'),
 (['Other current liabilit...'], 'label_i24'),
 (['Other financing activi...'], 'label_i90'),
 (['Other investing activi...'], 'label_i60'),
 (['Other investing charge...'], 'label_i60'),
 (['Other non-cash items'], 'label_i30'),
 (['Other operating activi...'], 'label_i30'),
 (['Other operating activi...'], 'label_i40'),
 (['Other operating gain (...'], 'label_i12'),
 (['Other working capital'], 'label_i23'),
 (['Other working capital'], 'label_i25'),
 (['Payables'], 'label_i19'),
 (['Payables'], 'label_i29'),
 (['Payments from loans'], 'label_i42'),
 (['Preferred stock issued'], 'label_i63'),
 (['Preferred stock issued'], 'label_i65'),
 (['Preferred stock issued'], 'label_i66'),
 (['Preferred stock issued'], 'label_i67'),
 (['Preferred stock issued'], 'label_i68'),
 (['Preferred stock repaid'], 'label_i64'),
 (['Premiums and insurance...'], 'label_i23'),
 (['Prepaid expenses'], 'label_i18'),
 (['Prepaid expenses'], 'label_i28'),
 (['Property, and equipmen...'], 'label_i35'),
 (['Property, and equipmen...'], 'label_i38'),
 (['Property, and equipmen...'], 'label_i46'),
 (['Property, plant, and e...'], 'label_i32'),
 (['Provision for credit l...'], 'label_i2'),
 (['Purchases of intangibl...'], 'label_i37'),
 (['Purchases of intangibl...'], 'label_i38'),
 (['Purchases of intangibl...'], 'label_i47'),
 (['Purchases of investmen...'], 'label_i34'),
 (['Purchases of investmen...'], 'label_i44'),
 (['Receivable'], 'label_i16'),
 (['Receivable'], 'label_i27'),
 (['Redemption of preferre...'], 'label_i67'),
 (['Redemption of preferre...'], 'label_i68'),
 (['Redemption of preferre...'], 'label_i69'),
 (['Redemption of preferre...'], 'label_i70'),
 (['Repurchases of treasur...'], 'label_i68'),
 (['Repurchases of treasur...'], 'label_i69'),
 (['Repurchases of treasur...'], 'label_i70'),
 (['Repurchases of treasur...'], 'label_i71'),
 (['Reserves for claims an...'], 'label_i22'),
 (['Sales of intangibles'], 'label_i39'),
 (['Sales of technologies'], 'label_i37'),
 (['Sales/Maturities of in...'], 'label_i35'),
 (['Sales/maturities of fi...'], 'label_i41'),
 (['Sales/maturity of inve...'], 'label_i33'),
 (['Short-term borrowing'], 'label_i61'),
 (['Stock based compensati...'], 'label_i10'),
 (['Stock based compensati...'], 'label_i12'),
 (['Stock based compensati...'], 'label_i13'),
 (['Supplemental schedule ...'], 'label_g8'),
 (['Trading securities'], 'label_i33'),
 (['Unrealized (gains) los...'], 'label_i2'),
 (['Warrant issued'], 'label_i65'),
 (['Warrant issued'], 'label_i66'),
 (['Warrant issued'], 'label_i67'),
 (['Warrant issued'], 'label_i68'),
 (['Warrant issued'], 'label_i69')]

<a id='cfq'></a>
[return to the top](#top)
### Quarterly Cash Flow Statement
##### DataFrame Instance

In [62]:
df_quarterlyCF = df.quarterlyCF()

In [63]:
df_quarterlyCF.head()

,ticker_id,exchange_id,data_i1_Y_1,data_i1_Y_2,data_i1_Y_3,data_i1_Y_4,data_i1_Y_5,data_i1_Y_6,data_i10_Y_1,data_i10_Y_2,...,label_tts2,label_tts3,currency_id,fye_month,Year_Y_1,Year_Y_2,Year_Y_3,Year_Y_4,Year_Y_5,Year_Y_6
0,1,374,NaN,NaN,NaN,NaN,NaN,NaN,3292000.0,4555000.0,...,120,133,104.0,12.0,2017-12,2018-03,2018-06,2018-09,2018-12,TTM
1,2,374,NaN,NaN,NaN,NaN,NaN,NaN,3292000.0,4555000.0,...,120,133,104.0,12.0,2017-12,2018-03,2018-06,2018-09,2018-12,TTM
2,3,374,NaN,NaN,NaN,NaN,NaN,NaN,3292000.0,4555000.0,...,120,133,104.0,12.0,2017-12,2018-03,2018-06,2018-09,2018-12,TTM
3,4,482,NaN,NaN,NaN,NaN,NaN,NaN,0.0,400000.0,...,120,133,104.0,12.0,2017-12,2018-03,2018-06,2018-09,2018-12,TTM
4,23,1,NaN,NaN,NaN,NaN,NaN,NaN,-84000.0,-128000.0,...,120,133,19.0,12.0,2017-12,2018-03,2018-06,2018-09,2018-12,TTM

##### DataFrame Length

In [64]:
print('DataFrame contains {:,.0f} records.'.format(len(df_quarterlyCF)))

DataFrame contains 77,919 records.

##### DataFrame Columns

In [73]:
labels = [col for col in df_quarterlyCF if 'label' in col]
labels = [[label, header] for label in labels 
          for header in df_quarterlyCF[label].unique().tolist() if pd.notna(header)]

df_labels_qCF = (pd.DataFrame(labels, columns=['header', 'value'])
                 .set_index('header')
                 .astype('int'))

df_labels_qCF['value'] = df_labels_qCF['value'].replace(df.colheaders['header'])
df_labels_qCF[df_labels_qCF['value'].astype('str').str.contains('ncome')].sort_values(by='value')

sorted(list(zip(df_labels_qCF.values.tolist(), df_labels_qCF.index)))

[(['(Gain) Loss from disco...'], 'label_i3'),
 (['(Gain) Loss from disco...'], 'label_i7'),
 (['(Gains) loss on dispos...'], 'label_i11'),
 (['(Gains) loss on dispos...'], 'label_i12'),
 (['Accounts payable'], 'label_i19'),
 (['Accounts payable'], 'label_i20'),
 (['Accounts receivable'], 'label_i16'),
 (['Accrued liabilities'], 'label_i20'),
 (['Accrued liabilities'], 'label_i21'),
 (['Accrued liabilities'], 'label_i30'),
 (['Acquisitions and dispo...'], 'label_i33'),
 (['Acquisitions and dispo...'], 'label_i36'),
 (['Acquisitions and dispo...'], 'label_i43'),
 (['Acquisitions, net'], 'label_i33'),
 (['Amortization of debt a...'], 'label_i7'),
 (['Amortization of debt d...'], 'label_i10'),
 (['Amortization of debt d...'], 'label_i3'),
 (['Amortization of debt d...'], 'label_i7'),
 (['Capital expenditure'], 'label_i96'),
 (['Capitalization of defe...'], 'label_i24'),
 (['Cash Flows From Financ...'], 'label_s3'),
 (['Cash Flows From Invest...'], 'label_s2'),
 (['Cash Flows From Operat...'], 'label_s1'),
 (['Cash at beginning of p...'], 'label_i94'),
 (['Cash at end of period'], 'label_i95'),
 (['Cash dividends paid'], 'label_i69'),
 (['Cash dividends paid'], 'label_i70'),
 (['Cash dividends paid'], 'label_i72'),
 (['Cash paid for income t...'], 'label_i98'),
 (['Cash paid for interest'], 'label_i99'),
 (['Change in deposits'], 'label_i61'),
 (['Change in deposits wit...'], 'label_i31'),
 (['Change in federal fund...'], 'label_i32'),
 (['Change in federal fund...'], 'label_i62'),
 (['Change in short-term b...'], 'label_i61'),
 (['Change in short-term b...'], 'label_i63'),
 (['Change in working capi...'], 'label_i15'),
 (['Changes in loans, net'], 'label_i35'),
 (['Common stock issued'], 'label_i64'),
 (['Common stock issued'], 'label_i65'),
 (['Common stock issued'], 'label_i66'),
 (['Common stock issued'], 'label_i67'),
 (['Common stock repurchas...'], 'label_i67'),
 (['Cumulative effect of a...'], 'label_i5'),
 (['Cumulative effect of a...'], 'label_i9'),
 (['Debt issued'], 'label_i61'),
 (['Debt issued'], 'label_i63'),
 (['Debt repayment'], 'label_i62'),
 (['Debt repayment'], 'label_i64'),
 (['Deferred charges'], 'label_i23'),
 (['Deferred income taxes'], 'label_i6'),
 (['Deferred tax (benefit)...'], 'label_i11'),
 (['Deferred tax (benefit)...'], 'label_i9'),
 (['Deferred tax(benefit) ...'], 'label_i6'),
 (['Depreciation & amortiz...'], 'label_i2'),
 (['Depreciation & amortiz...'], 'label_i5'),
 (['Depreciation & amortiz...'], 'label_i6'),
 (['Dividend paid'], 'label_i69'),
 (['Dividend paid'], 'label_i71'),
 (['Dividend payable'], 'label_i70'),
 (['Dividend payable'], 'label_i71'),
 (['Dividend payable'], 'label_i72'),
 (['Dividend payable'], 'label_i73'),
 (['Effect of exchange rat...'], 'label_i91'),
 (['Equity in (income) los...'], 'label_i4'),
 (['Excess tax benefit fro...'], 'label_i63'),
 (['Excess tax benefit fro...'], 'label_i64'),
 (['Excess tax benefit fro...'], 'label_i65'),
 (['Excess tax benefit fro...'], 'label_i66'),
 (['Excess tax benefit fro...'], 'label_i68'),
 (['Extraordinary items'], 'label_i4'),
 (['Extraordinary items'], 'label_i8'),
 (['Free Cash Flow'], 'label_g7'),
 (['Free cash flow'], 'label_i97'),
 (['Fund held under reinsu...'], 'label_i26'),
 (['Income taxes payable'], 'label_i22'),
 (['Income taxes payable'], 'label_i23'),
 (['Income taxes payable'], 'label_i32'),
 (['Interest payable'], 'label_i21'),
 (['Interest payable'], 'label_i22'),
 (['Interest payable'], 'label_i31'),
 (['Inventory'], 'label_i17'),
 (['Investment income due ...'], 'label_i25'),
 (['Investment/asset impai...'], 'label_i4'),
 (['Investment/asset impai...'], 'label_i6'),
 (['Investment/asset impai...'], 'label_i8'),
 (['Investments (gains) lo...'], 'label_i10'),
 (['Investments (gains) lo...'], 'label_i3'),
 (['Investments (gains) lo...'], 'label_i5'),
 (['Investments in propert...'], 'label_i31'),
 (['Investments in technol...'], 'label_i36'),
 (['Investments losses (ga...'], 'label_i5'),
 (['Loans'], 'label_i17'),
 (['Loans issued'], 'label_i45'),
 (['Long-term debt issued'], 'label_i62'),
 (['Long-term debt issued'], 'label_i64'),
 (['Long-term debt repayme...'], 'label_i63'),
 (['Long-term debt repayme...'], 'label_i65'),
 (['Net cash provided by (...'], 'label_i92'),
 (['Net cash provided by (...'], 'label_tts3'),
 (['Net cash provided by o...'], 'label_tts1'),
 (['Net cash used for inve...'], 'label_tts2'),
 (['Net change in cash'], 'label_i93'),
 (['Net income'], 'label_i1'),
 (['Operating cash flow'], 'label_i100'),
 (['Other assets and liabi...'], 'label_i24'),
 (['Other assets and liabi...'], 'label_i34'),
 (['Other current assets'], 'label_i19'),
 (['Other current liabilit...'], 'label_i24'),
 (['Other financing activi...'], 'label_i90'),
 (['Other investing activi...'], 'label_i60'),
 (['Other investing charge...'], 'label_i60'),
 (['Other non-cash items'], 'label_i30'),
 (['Other operating activi...'], 'label_i30'),
 (['Other operating activi...'], 'label_i40'),
 (['Other operating gain (...'], 'label_i12'),
 (['Other working capital'], 'label_i23'),
 (['Other working capital'], 'label_i25'),
 (['Payables'], 'label_i19'),
 (['Payables'], 'label_i29'),
 (['Payments from loans'], 'label_i42'),
 (['Preferred stock issued'], 'label_i63'),
 (['Preferred stock issued'], 'label_i65'),
 (['Preferred stock issued'], 'label_i66'),
 (['Preferred stock issued'], 'label_i67'),
 (['Preferred stock issued'], 'label_i68'),
 (['Preferred stock repaid'], 'label_i64'),
 (['Premiums and insurance...'], 'label_i23'),
 (['Prepaid expenses'], 'label_i18'),
 (['Prepaid expenses'], 'label_i28'),
 (['Property, and equipmen...'], 'label_i35'),
 (['Property, and equipmen...'], 'label_i38'),
 (['Property, and equipmen...'], 'label_i46'),
 (['Property, plant, and e...'], 'label_i32'),
 (['Provision for credit l...'], 'label_i2'),
 (['Purchases of intangibl...'], 'label_i37'),
 (['Purchases of intangibl...'], 'label_i38'),
 (['Purchases of intangibl...'], 'label_i47'),
 (['Purchases of investmen...'], 'label_i34'),
 (['Purchases of investmen...'], 'label_i44'),
 (['Receivable'], 'label_i16'),
 (['Receivable'], 'label_i27'),
 (['Redemption of preferre...'], 'label_i67'),
 (['Redemption of preferre...'], 'label_i68'),
 (['Redemption of preferre...'], 'label_i69'),
 (['Redemption of preferre...'], 'label_i70'),
 (['Repurchases of treasur...'], 'label_i68'),
 (['Repurchases of treasur...'], 'label_i69'),
 (['Repurchases of treasur...'], 'label_i70'),
 (['Repurchases of treasur...'], 'label_i71'),
 (['Reserves for claims an...'], 'label_i22'),
 (['Sales of intangibles'], 'label_i39'),
 (['Sales of technologies'], 'label_i37'),
 (['Sales/Maturities of in...'], 'label_i35'),
 (['Sales/maturities of fi...'], 'label_i41'),
 (['Sales/maturity of inve...'], 'label_i33'),
 (['Short-term borrowing'], 'label_i61'),
 (['Stock based compensati...'], 'label_i10'),
 (['Stock based compensati...'], 'label_i12'),
 (['Stock based compensati...'], 'label_i13'),
 (['Supplemental schedule ...'], 'label_g8'),
 (['Trading securities'], 'label_i33'),
 (['Unrealized (gains) los...'], 'label_i2'),
 (['Warrant issued'], 'label_i65'),
 (['Warrant issued'], 'label_i66'),
 (['Warrant issued'], 'label_i67'),
 (['Warrant issued'], 'label_i68'),
 (['Warrant issued'], 'label_i69')]

<a id="stats"></a>
[return to the top](#top)
## Performing statistical analysis
### Count of database records
**1.** Total number of records **before** merging reference tables *(length of `df.master`)*

In [74]:
print('DataFrame df.master contains {:,.0f} records.'.format(len(df.master)))

DataFrame df.master contains 117,989 records.

**2.** Total number of records **after** merging reference tables *(length of `df_master`)*

In [75]:
print('DataFrame df_master0 contains {:,.0f} records.'.format(len(df_master0)))

DataFrame df_master0 contains 112,085 records.

**3.** Total number of records **after** merging reference tables where the following filters apply:
- $openprice > 0$
- $lastprice > 0$

In [76]:
print('DataFrame df_master contains {:,.0f} records.'.format(len(df_master)))

DataFrame df_master contains 103,490 records.

<a id="lastupdate"></a>
[return to the top](#top)
### Last updated dates
List of dates (as a pd.Series object) of when the database records were last updated. 
The values indicate the number of records updated on each date.

In [77]:
(df_master[['updated_date', 'ticker']].groupby(by='updated_date').count().sort_index(ascending=False)
 .rename(columns={'ticker':'ticker_count'}))

              ticker_count
updated_date
2019-04-12               1
2019-04-11           50341
2019-04-10           40590
2019-04-09           12496
2019-04-08              62

<a id="type"></a>
[return to the top](#top)
### Number of records by Security Type

In [78]:
(df_master[['security_type', 'ticker']].groupby(by='security_type').count()
 .rename(columns={'ticker':'ticker_count'}))

                      ticker_count
security_type
Closed-End Fund               1209
Exchange-Traded Fund          6207
Index                          502
Money Market Fund              194
Open-End Fund                25680
Stock                        69698

<a id="country"></a>
[return to the top](#top)
### Number of records by Country, based on the location of exchanges

In [79]:
(df_master[['country', 'country_c3', 'ticker']]
 .groupby(by=['country', 'country_c3']).count().rename(columns={'ticker':'ticker_count'})
)

                           ticker_count
country        country_c3
Australia      AUS                 2147
Belgium        BEL                  169
Canada         CAN                 4179
China          CHN                 3823
France         FRA                 1195
Germany        DEU                35433
Hong Kong      HKG                 2370
Ireland        IRL                 1753
Italy          ITA                  630
Luxembourg     LUX                   23
Netherlands    NLD                  225
Norway         NOR                    1
Portugal       PRT                   57
United Kingdom GBR                 5751
United States  USA                45734

<a id="exchange"></a>
[return to the top](#top)
### Number of records per exchange
Where $ticker\_count > 100$

In [81]:
cols = ['country', 'country_c3', 'exchange', 'exchange_sym', 'ticker']
df_exchanges = df_master[cols].groupby(by=cols[:-1]).count().rename(columns={'ticker':'ticker_count'})
df_exchanges[df_exchanges['ticker_count'] > 100]

                                                                             ticker_count
country        country_c3 exchange                             exchange_sym
Australia      AUS        ASX - ALL MARKETS                    XASX                  2147
Belgium        BEL        EURONEXT - EURONEXT BRUSSELS         XBRU                   169
Canada         CAN        CANADIAN NATIONAL STOCK EXCHANGE     XCNQ                   419
                          TORONTO STOCK EXCHANGE               XTSE                  2017
                          TSX VENTURE EXCHANGE                 XTSX                  1683
China          CHN        SHANGHAI STOCK EXCHANGE              XSHG                  1596
                          SHENZHEN STOCK EXCHANGE              XSHE                  2227
France         FRA        EURONEXT - EURONEXT PARIS            XPAR                  1195
Germany        DEU        BOERSE BERLIN                        XBER                  8140
                          BOERSE DUESSELDORF                   XDUS                  2162
                          BOERSE HAMBURG                       XHAM                  1266
                          BOERSE HANNOVER                      XHAN                   462
                          BOERSE MUENCHEN                      XMUN                  4730
                          BOERSE STUTTGART                     XSTU                  8193
                          DEUTSCHE BOERSE AG                   XFRA                 10480
Hong Kong      HKG        HONG KONG EXCHANGES AND CLEARING LTD XHKG                  2370
Ireland        IRL        SIX SWISS EXCHANGE                   XSWX                   292
                          XETRA                                XETR                  1461
Italy          ITA        BORSA ITALIANA S.P.A.                XMIL                   630
Netherlands    NLD        EURONEXT - EURONEXT AMSTERDAM        XAMS                   201
United Kingdom GBR        LONDON STOCK EXCHANGE                XLON                  3327
                          LSE International Trading Service    LTS                   2423
United States  USA        BATS Z-EXCHANGE                      BATS                   299
                          Dow Jones Indices                    DJI                    130
                          NASDAQ                               XNAS                 29143
                          NEW YORK STOCK EXCHANGE, INC.        XNYS                  2882
                          NYSE ARCA                            ARCX                  1595
                          NYSE MKT LLC                         XASE                   298
                          OTC GREY MARKET                      GREY                  3038
                          OTC MARKETS                          PINX                  8092
                          S&P Indices                          SPI                    170


[return to the top](#top)
### Number of Stocks by Country of Exchange

In [82]:
(df_master
 .where(df_master['security_type'] == 'Stock').dropna(axis=0, how='all')[['country', 'country_c3', 'ticker']]
 .groupby(by=['country', 'country_c3']).count().rename(columns={'ticker':'ticker_count'})
 .sort_values(by='ticker_count', ascending=False))

                           ticker_count
country        country_c3
Germany        DEU                35403
United States  USA                16586
United Kingdom GBR                 4145
China          CHN                 3623
Canada         CAN                 3365
Hong Kong      HKG                 2275
Australia      AUS                 1836
Ireland        IRL                  839
France         FRA                  833
Italy          ITA                  451
Belgium        BEL                  168
Netherlands    NLD                  121
Portugal       PRT                   53

<a id="sector"></a>
[return to the top](#top)
### Number of stocks by sector

In [83]:
(df_master
 .where((df_master['security_type'] == 'Stock') & (df_master['sector'] != '—')).dropna(axis=0, how='all')
 .groupby(by='sector').count()
 .rename(columns={'ticker':'stock_count'}))['stock_count'].sort_values(ascending=False)

sector
Basic Materials           11494
Industrials                9830
Technology                 9556
Consumer Cyclical          8783
Financial Services         7898
Healthcare                 7602
Energy                     3825
Consumer Defensive         3710
Real Estate                3600
Utilities                  1931
Communication Services     1468
Name: stock_count, dtype: int64

<a id="industry"></a>
[return to the top](#top)
### Number of stocks by industry

In [84]:
(df_master[['sector', 'industry', 'ticker']]
 .where((df_master['security_type'] == 'Stock') & (df_master['industry'] != '—')).dropna(axis=0, how='all')
 .groupby(by=['sector', 'industry']).count().rename(columns={'ticker':'stock_count'}))

                                                                stock_count
sector                 industry
Basic Materials        Agricultural Inputs                              286
                       Aluminum                                         139
                       Building Materials                               813
                       Chemicals                                        724
                       Coal                                             382
                       Copper                                           298
                       Gold                                            1930
                       Industrial Metals & Minerals                    5087
                       Lumber & Wood Production                         141
                       Paper & Paper Products                           292
                       Silver                                           178
                       Specialty Chemicals                              697
                       Steel                                            527
Communication Services Pay TV                                            95
                       Telecom Services                                1373
Consumer Cyclical      Advertising Agencies                             203
                       Apparel Manufacturing                            427
                       Apparel Stores                                   295
                       Auto & Truck Dealerships                         160
                       Auto Manufacturers                               443
                       Auto Parts                                       734
                       Broadcasting - Radio                              39
                       Broadcasting - TV                                265
                       Department Stores                                333
                       Footwear & Accessories                           214
                       Gambling                                         232
                       Home Furnishings & Fixtures                      344
                       Home Improvement Stores                           71
                       Leisure                                          675
                       Lodging                                          250
...                                                                     ...
Real Estate            REIT - Industrial                                158
                       REIT - Office                                    193
                       REIT - Residential                               167
                       REIT - Retail                                    294
                       Real Estate - General                           1006
                       Real Estate Services                            1149
Technology             Communication Equipment                          850
                       Computer Distribution                             32
                       Computer Systems                                 315
                       Consumer Electronics                             475
                       Contract Manufacturers                           121
                       Data Storage                                      61
                       Electronic Components                           1028
                       Electronic Gaming & Multimedia                   403
                       Electronics Distribution                         132
                       Health Information Services                      299
                       Information Technology Services                  899
                       Internet Content & Information                   755
                       Scientific & Technical Instruments               388
                       Semiconductor Equipment & Materials              376
                       Semiconductor Memory                              56
                       Semiconductors                                   507
                       Software - Application                          1955
                       Software - Infrastructure                        687
                       Solar                                            217
Utilities              Utilities - Diversified                          421
                       Utilities - Independent Power Producers          442
                       Utilities - Regulated Electric                   663
                       Utilities - Regulated Gas                        237
                       Utilities - Regulated Water                      168

[148 rows x 1 columns]

<a id="meanpr"></a>
[return to the top](#top)
### Mean price ratios (P/E, P/S, P/B, P/CF) of stocks by sectors

Merge *Master* and *Valuation* DataFrames

In [203]:
df_valuation = (df_master
                .where((df_master['security_type'] == 'Stock') & (df_master['sector'] != '—'))
                .dropna(axis=0, how='all')
                .merge(df_vals, on=['ticker_id', 'exchange_id'])
                .drop(['ticker_id', 'exchange_id'], axis=1))

#### Mean Price Ratios for all stocks:

In [201]:
df_valuation_mean = (df_valuation[['sector', 'company']].groupby('sector').count()
                     .rename(columns={'company':'count'})
                     .merge(df_valuation.groupby('sector').mean().round(1), on='sector')
                     .drop(['aprvol', 'avevol'], axis=1))
#df_valuation_mean.columns

In [21]:
print('For a total of {:,.0f} stock records:'.format(len(df_valuation)))
df_pratios_TTM = df_valuation_mean[['count', 'Forward_PE', 'PE_TTM', 'PB_TTM', 'PS_TTM', 'PC_TTM']]
df_pratios_TTM

For a total of 69,696 stock records:

                        count  Forward_PE  PE_TTM  PB_TTM  PS_TTM  PC_TTM
sector
Basic Materials         11494        18.1    29.6   495.0   366.2    27.2
Communication Services   1468        31.3    42.8     3.7     5.3    21.0
Consumer Cyclical        8783        25.3    38.7     5.5    31.4    29.1
Consumer Defensive       3710        22.7    36.0     6.0    27.5    47.3
Energy                   3825        49.5    35.3     5.0   192.3    12.9
Financial Services       7898        14.6    32.0    41.7   414.6   280.8
Healthcare               7602        44.1    68.2    97.5   927.9    84.4
Industrials              9829        22.5    43.9    13.5  7432.9    33.0
Real Estate              3600        25.0    36.6     6.8    13.1    76.5
Technology               9556        43.5    62.6     8.9   177.8   149.8
Utilities                1931        19.3    36.9     3.3    11.5   140.8

#### Mean Price Ratios for USA stocks:

In [22]:
df_valuation_usa = df_valuation[df_valuation['country_c3'] == 'USA']

In [24]:
df_valuation_mean_usa = (df_valuation_usa[['sector', 'company']].groupby('sector').count()
                         .rename(columns={'company':'count'})
                         .merge(df_valuation_usa.groupby('sector').mean().round(1), on='sector')
                         .drop(['aprvol', 'avevol'], axis=1))
#df_valuation_mean_usa.columns

In [25]:
print('For a total of {:,.0f} stock records:'.format(len(df_valuation_usa)))
df_pratios_TTM_USA = df_valuation_mean_usa[['count', 'Forward_PE', 'PE_TTM', 'PB_TTM', 'PS_TTM', 'PC_TTM']]
df_pratios_TTM_USA

For a total of 16,586 stock records:

                        count  Forward_PE  PE_TTM  PB_TTM  PS_TTM  PC_TTM
sector
Basic Materials          2314        18.0    23.9  2692.3   378.4    33.8
Communication Services    321        35.7    39.2     6.4    11.6    27.8
Consumer Cyclical        1848        24.0    33.9     8.6   124.7    22.2
Consumer Defensive        891        22.1    37.3    13.7    96.7    41.9
Energy                    985        26.3    43.0     5.5   172.8    20.9
Financial Services       2504        15.3    29.9     4.9   266.6    35.3
Healthcare               1978        50.8    68.4   377.0  1943.8    36.2
Industrials              2260        26.2    45.7    43.5    54.6    37.0
Real Estate               938        26.9    44.0     2.0    14.0    37.6
Technology               2066        43.3    67.9    15.8   653.3    88.3
Utilities                 481        19.8    39.7     6.3    13.1   558.4

#### Mean Price Ratios for DEU (Germany) stocks:

In [27]:
df_valuation_deu = df_valuation[df_valuation['country_c3'] == 'DEU']

In [28]:
df_valuation_mean_deu = (df_valuation_deu[['sector', 'company']].groupby('sector').count()
                         .rename(columns={'company':'count'})
                         .merge(df_valuation_deu.groupby('sector').mean().round(1), on='sector')
                         .drop(['aprvol', 'avevol'], axis=1))
#df_valuation_mean_deu.columns

In [29]:
print('For a total of {:,.0f} stock records:'.format(len(df_valuation_deu)))
df_pratios_TTM_DEU = df_valuation_mean_deu[['count', 'Forward_PE', 'PE_TTM', 'PB_TTM', 'PS_TTM', 'PC_TTM']]
df_pratios_TTM_DEU

For a total of 35,403 stock records:

                        count  Forward_PE  PE_TTM  PB_TTM  PS_TTM  PC_TTM
sector
Basic Materials          5807        18.2    22.8     4.7   149.0    18.5
Communication Services    873        28.9    40.6     3.0     4.0    18.7
Consumer Cyclical        4470        27.9    37.6     4.4    10.1    20.7
Consumer Defensive       1909        23.0    29.1     3.7     8.1    34.9
Energy                   2015        52.8    27.7     3.4   168.1     9.5
Financial Services       3567        14.0    31.6     2.1     8.8    53.9
Healthcare               4179        44.2    74.3     8.5   693.0    38.9
Industrials              4896        21.1    40.2     6.4   152.6    22.4
Real Estate              1684        26.3    33.7     1.6    12.5    95.1
Technology               5012        44.7    52.9     6.5    52.7   161.8
Utilities                 991        19.1    29.1     2.1     7.5    22.9

#### Plots of TTM P/E by Sectors
*All Stocks*

In [204]:
fig_pe, (ax_pe, ax_pe_usa, ax_pe_deu) = plt.subplots(3, 1, sharex=True, sharey=True, figsize=(8, 5))

In [205]:
plt.subplots_adjust(bottom=0.4)
plt.xticks(ticks=x, labels=y.index.tolist(), fontsize=9)
plt.axis([-3, len(x)*3, 0, 80])
plt.suptitle('Average TTM P/E of Stocks by Sector', fontsize=11, fontweight='bold')
plt.yticks([])
ax_pe.set_title('All Stocks', loc='left', fontsize=9)
ax_pe_usa.set_title('USA', loc='left', fontsize=9)
ax_pe_deu.set_title('DEU', loc='left', fontsize=9)
fig_pe.subplots_adjust(hspace=1)

In [194]:
pe = df_valuation_mean['PE_TTM']
pe_usa = df_valuation_mean_usa['PE_TTM']
pe_deu = df_valuation_mean_deu['PE_TTM']

In [206]:
x = [x*3 for x in range(len(pe))]
y = pe#.sort_values(ascending=True)
bars = ax_pe.bar(x, y, width=2)
for bar in bars:
    ax_pe.text(bar.get_x()+1, bar.get_height()+1.5, '{:.1f}'.format(bar.get_height()), 
               color='black', ha='center', fontsize=9)
ax_pe.get_children()[22].set_color(None)
ax_pe.get_children()[23].set_color(None)
ax_pe.get_children()[25].set_color(None)

*USA*

In [207]:
x = [x*3 for x in range(len(pe_usa))]
y = pe_usa#.sort_values(ascending=True)
bars = ax_pe_usa.bar(x, y, width=2)
for bar in bars:
    ax_pe_usa.text(bar.get_x()+1, bar.get_height()+1.5, '{:.1f}'.format(bar.get_height()), 
               color='black', ha='center', fontsize=9)
ax_pe_usa.get_children()[22].set_color(None)
ax_pe_usa.get_children()[23].set_color(None)
ax_pe_usa.get_children()[25].set_color(None)

*DEU*

In [208]:
x = [x*3 for x in range(len(pe_deu))]
y = pe_deu#.sort_values(ascending=True)
bars = ax_pe_deu.bar(x, y, width=2)
for bar in bars:
    ax_pe_deu.text(bar.get_x()+1, bar.get_height()+1.5, '{:.1f}'.format(bar.get_height()), 
               color='black', ha='center', fontsize=9)
ax_pe_deu.get_children()[22].set_color(None)
ax_pe_deu.get_children()[23].set_color(None)
ax_pe_deu.get_children()[25].set_color(None)
for tick in ax_pe_deu.xaxis.get_ticklabels():
    tick.set_rotation(90)

### Stocks in the Cannabis Industry
Using stocks listed on [marijuanaindex.com](http://marijuanaindex.com/stock-quotes/north-american-marijuana-index/) under North America

In [73]:
import json

with open('input/pot_stocks.json') as file:
    pot_symbols = json.loads(file.read())
    
pot_stocks = (pd.DataFrame(pot_symbols, columns=['ticker', 'country_c3'])
               .merge(df_master, how='left', on=['ticker', 'country_c3']).drop('country', axis=1)
               .rename(columns={'country_c3':'country', 'exchange_sym':'exch'}))

pot_stocks = (pot_stocks.where(((pot_stocks['country'] == 'USA') | 
                                (pot_stocks['country'] == 'CAN')) &
                               (pot_stocks['sector'] != '—'))
              .dropna(axis=0, how='all').sort_values(by='company'))

In [74]:
msg = 'Below are the {} stocks listed on marijuanaindex.com for North America.'
print(msg.format(len(pot_stocks['company'].unique())))

pot_stocks[['country', 'ticker', 'exch', 'company', 'sector', 'industry']]

Below are the 46 stocks listed on marijuanaindex.com for North America.

,country,ticker,exch,company,sector,industry
29,CAN,TGIF,XCNQ,1933 Industries Inc,Healthcare,Drug Manufacturers - Specialty & Generic
1,USA,ACRGF,PINX,Acreage Holdings Inc Ordinary Shares (Sub Voting),Healthcare,Drug Manufacturers - Specialty & Generic
2,CAN,ACRG.U,XCNQ,Acreage Holdings Inc Ordinary Shares (Sub Voting),Healthcare,Drug Manufacturers - Specialty & Generic
37,USA,APHA,XNYS,Aphria Inc,Healthcare,Drug Manufacturers - Specialty & Generic
0,CAN,ACB,XTSE,Aurora Cannabis Inc,Healthcare,Drug Manufacturers - Specialty & Generic
36,CAN,XLY,XTSX,Auxly Cannabis Group Inc,Healthcare,Drug Manufacturers - Specialty & Generic
40,USA,CVSI,PINX,CV Sciences Inc,Healthcare,Drug Manufacturers - Specialty & Generic
32,CAN,TRST,XTSE,CannTrust Holdings Inc,Healthcare,Drug Manufacturers - Specialty & Generic
4,CAN,CNNX,XCNQ,Cannex Capital Holdings Inc,Healthcare,Drug Manufacturers - Specialty & Generic
38,USA,CGC,XNYS,Canopy Growth Corp,Healthcare,Drug Manufacturers - Specialty & Generic
26,CAN,RIV,XTSX,Canopy Rivers Inc,Healthcare,Drug Manufacturers - Specialty & Generic
6,CAN,CWEB,XCNQ,Charlottes Web Holdings Inc Ordinary Shares,Healthcare,Drug Manufacturers - Specialty & Generic
3,CAN,CL,XCNQ,Cresco Labs Inc,Healthcare,Drug Manufacturers - Specialty & Generic
39,USA,CRON,XNAS,Cronos Group Inc,Healthcare,Drug Manufacturers - Specialty & Generic
5,CAN,CURA,XCNQ,Curaleaf Holdings Inc,Healthcare,Drug Manufacturers - Specialty & Generic
7,CAN,EMH,XTSX,Emerald Health Therapeutics Inc,Healthcare,Biotechnology
42,USA,GWPH,XNAS,GW Pharmaceuticals PLC ADR,Healthcare,Drug Manufacturers - Major
10,CAN,GLH,XCNQ,Golden Leaf Holdings Ltd,Healthcare,Drug Manufacturers - Specialty & Generic
9,CAN,GGB,XCNQ,Green Growth Brands Inc,Healthcare,Drug Manufacturers - Specialty & Generic
11,CAN,GTII,XCNQ,Green Thumb Industries Inc,Healthcare,Drug Manufacturers - Specialty & Generic
41,USA,GRWG,PINX,GrowGeneration Corp,Industrials,Industrial Distribution
13,CAN,HEXO,XTSE,HEXO Corp,Healthcare,Drug Manufacturers - Specialty & Generic
12,CAN,HARV,XCNQ,Harvest Health & Recreation Inc,Healthcare,Drug Manufacturers - Specialty & Generic
43,USA,IIPR,XNYS,Innovative Industrial Properties Inc Registere...,Real Estate,REIT - Industrial
16,CAN,ISOL,XCNQ,Isodiol International Inc,Healthcare,Drug Manufacturers - Specialty & Generic
44,USA,KSHB,PINX,KushCo Holdings Inc,Consumer Cyclical,Packaging & Containers
17,CAN,LHS,XCNQ,Liberty Health Sciences Inc,Healthcare,Drug Manufacturers - Specialty & Generic
18,CAN,MJAR,XCNQ,MJardin Group Inc,Healthcare,Drug Manufacturers - Specialty & Generic
21,USA,MPXOF,PINX,MPX International Corp,Healthcare,Drug Manufacturers - Specialty & Generic
20,CAN,MPXI,XCNQ,MPX International Corp,Healthcare,Drug Manufacturers - Specialty & Generic
45,USA,MRMD,PINX,MariMed Inc,Healthcare,Biotechnology
19,CAN,MMEN,XCNQ,MedMen Enterprises Inc,Healthcare,Drug Manufacturers - Specialty & Generic
22,CAN,N,XTSX,Namaste Technologies Inc,Consumer Cyclical,Specialty Retail
14,CAN,HIP,XTSX,Newstrike Brands Ltd,Healthcare,Drug Manufacturers - Specialty & Generic
23,CAN,OGI,XTSX,OrganiGram Holdings Inc,Healthcare,Drug Manufacturers - Specialty & Generic
24,CAN,OH,XCNQ,Origin House,Healthcare,Drug Manufacturers - Specialty & Generic
25,CAN,PLTH,XCNQ,Planet 13 Holdings Inc Ordinary Shares,Healthcare,Drug Manufacturers - Specialty & Generic
27,CAN,SNN,XCNQ,Sunniva Inc Ordinary Shares,Healthcare,Drug Manufacturers - Specialty & Generic
31,CAN,TILT,XCNQ,TILT Holdings Inc,Healthcare,Drug Manufacturers - Specialty & Generic
28,CAN,TER,XCNQ,TerrAscend Corp,Healthcare,Drug Manufacturers - Specialty & Generic
47,USA,TRTC,PINX,Terra Tech Corp,Industrials,Farm & Construction Equipment
30,CAN,TGOD,XTSE,The Green Organic Dutchman Holdings Ltd Ordina...,Healthcare,Drug Manufacturers - Specialty & Generic
8,CAN,FIRE,XTSE,The Supreme Cannabis Co Inc,Healthcare,Drug Manufacturers - Specialty & Generic
46,USA,TLRY,XNAS,Tilray Inc,Healthcare,Drug Manufacturers - Specialty & Generic
33,CAN,TRUL,XCNQ,Trulieve Cannabis Corp Ordinary Shares (Sub Vo...,Healthcare,Drug Manufacturers - Specialty & Generic
34,CAN,VIVO,XTSX,VIVO Cannabis Inc,Healthcare,Drug Manufacturers - Specialty & Generic
35,CAN,WAYL,XCNQ,Wayland Group Corp,Healthcare,Drug Manufacturers - Specialty & Generic
15,CAN,IAN,XCNQ,iAnthus Capital Holdings Inc,Healthcare,Drug Manufacturers - Specialty & Generic

<a id="value"></a>
[return to the top](#top)

## Applying various criteria to filter common stocks

Below is a list of different rules that can be applied to the data to screen stocks (development of *italicized rules* is still in progress)

- *[Rule 1](#rule1): No earnings deficit (loss) for past 5 or 7 years*
- **[Rule 2](#rule2): Uniterrupted and increasing Dividends for past 5 yrs**
- **[Rule 3](#rule3): P/E Ratio of 25 or less for the past 7 yrs and less then 20 for TTM**
- *[Rule 4](#rule4): P/B Ratio of 1.2 or less for TTM*
- *[Rule 5](#rule5): Filter for "bargain issues"*
- *[Rule 6](#rule6): Operating Cash Flow growth for the past 7 yr*
- *[Rule 7](#rule7): Owner earnings growth rate > 6% over past 7 years*
- *[Rule 8](#rule8): Long-term debt < 50% of total capital*
- *[Rule 9](#rule9): NAV per share > Stock Price*
- *[Rule 10](#rule10): Growth Stocks as described by Benjamin Graham in _The Intelligent Investor_*
- *[Rule 11](#rule11): Positive ratio of earnings to fixed charge*
- *[Rule 12](#rule12): CAN SLIM*
- *[Rule 13](#rule13):*
- *[Rule 14](#rule14):*
- *[Rule 15](#rule15):*

*[Merge DataFrames](#mergerules) created for different rules to screen stocks.*
<a id="rule1"></a>

### Rule 1. No earnings deficit (loss) for past 5 or 7 years
Criteria: Find companies with positive earnings per share growth during the past five years with no earnings deficits. Earnings need to be higher in the most recent year than five years ago. Avoiding companies with earnings deficits during the past five years will help you stay clear of high-risk companies. [(Source)](https://cabotwealth.com/daily/value-investing/benjamin-grahams-value-stock-criteria/)

#### 5 Years:
*a. Identify Net Income column labels in* `df_annualIS`

In [105]:
data = 'Net income'
df_labels = df_labels_aIS[df_labels_aIS['value'] == data].sort_values(by='value')
df_labels

                value
header
label_i50  Net income
label_i70  Net income
label_i80  Net income

*b. Get column headers for 'Net income' values for the past 5 yrs*

In [106]:
i_ids = [(label[-3:] + '_') for label in df_labels.index]

def get_icols(col):
    for i_id in i_ids:
        if i_id in col:
            return True
    return False

main_cols1 = ['ticker_id', 'exchange_id', 
             'country', 'exchange_sym', 'ticker', 'company', 
             'sector', 'industry', 'stock_type', 'style', 
             'Year_Y_6', 'Year_Y_5', 'Year_Y_4', 'Year_Y_3', 'Year_Y_2', 'Year_Y_1']
data_cols = sorted(list(filter(get_icols, df_annualIS.columns)), key=lambda r: (r[-1], r[5:8]), reverse=True)
print('The following columns contain \'{}\' values:\n{}'.format(data, data_cols))

The following columns contain 'Net income' values:
['data_i80_Y_6', 'data_i70_Y_6', 'data_i50_Y_6', 'data_i80_Y_5', 'data_i70_Y_5', 'data_i50_Y_5', 'data_i80_Y_4', 'data_i70_Y_4', 'data_i50_Y_4', 'data_i80_Y_3', 'data_i70_Y_3', 'data_i50_Y_3', 'data_i80_Y_2', 'data_i70_Y_2', 'data_i50_Y_2', 'data_i80_Y_1', 'data_i70_Y_1', 'data_i50_Y_1']

*c. Create 'Net Income' DataFrame*

In [107]:
df_annualIS['Year_Y_5'] = pd.to_datetime(df_annualIS['Year_Y_5'])

In [126]:
df_netinc5 = (df_annualIS
              .where((df_annualIS['security_type'] == 'Stock') & 
                     (df_annualIS['Year_Y_5'] >= pd.to_datetime('2018-01')))
              .dropna(axis=0, how='all')
              .drop(['country'], axis=1)
              .rename(columns={'country_c3':'country'})
             )[main_cols1 + data_cols]

np_netinc = df_netinc5[data_cols].values
netinc_cols = [('Net_Income_Y' + data_cols[i * 3][-1], (i * 3, i * 3 + 1, i * 3 + 2))
               for i in range(int(len(data_cols)/3))]

vals = []
for row in np_netinc:
    row_vals = []
    for i in range(len(netinc_cols)):
        val = None
        for col in netinc_cols[i][1]:
            if not np.isnan(row[col]):
                val = row[col]
                break
        row_vals.append(val)
    vals.append(row_vals)
    
df_netinc_vals = pd.DataFrame(vals, columns=list(zip(*netinc_cols))[0])
df_netinc5 = df_netinc5[main_cols1].join(df_netinc_vals)

In [127]:
df_rule1_5 = df_netinc5.where((df_netinc5['Net_Income_Y6'] > 0) & 
                            ((df_netinc5['Net_Income_Y5'] > 0) | (df_netinc5['Net_Income_Y5'].isna())) & 
                            ((df_netinc5['Net_Income_Y4'] > 0) | (df_netinc5['Net_Income_Y4'].isna())) & 
                            ((df_netinc5['Net_Income_Y3'] > 0) | (df_netinc5['Net_Income_Y3'].isna())) & 
                            ((df_netinc5['Net_Income_Y2'] > 0) | (df_netinc5['Net_Income_Y2'].isna())) & 
                            ((df_netinc5['Net_Income_Y1'] > 0) | (df_netinc5['Net_Income_Y1'].isna()))
                           ).dropna(axis=0, how='all')

In [128]:
df_rule1_5

,ticker_id,exchange_id,country,exchange_sym,ticker,company,sector,industry,stock_type,style,...,Year_Y_4,Year_Y_3,Year_Y_2,Year_Y_1,Net_Income_Y6,Net_Income_Y5,Net_Income_Y4,Net_Income_Y3,Net_Income_Y2,Net_Income_Y1
0,1.0,374.0,USA,ARCX,OGCP,Empire State Realty OP LP Operating Partnershi...,Real Estate,REIT - Diversified,Hard Asset,Mid Core,...,2017-12,2016-12,2015-12,2014-12,1.164020e+08,1.164020e+08,1.182530e+08,1.072500e+08,7.992800e+07,7.021000e+07
1,2.0,374.0,USA,ARCX,FISK,Empire State Realty OP LP Operating Partnershi...,Real Estate,REIT - Diversified,Hard Asset,Mid Core,...,2017-12,2016-12,2015-12,2014-12,1.164020e+08,1.164020e+08,1.182530e+08,1.072500e+08,7.992800e+07,7.021000e+07
2,3.0,374.0,USA,ARCX,ESBA,Empire State Realty OP LP Operating Partnershi...,Real Estate,REIT - Diversified,Hard Asset,Mid Core,...,2017-12,2016-12,2015-12,2014-12,1.164020e+08,1.164020e+08,1.182530e+08,1.072500e+08,7.992800e+07,7.021000e+07
4,19275.0,302.0,USA,XNYS,LPT,Liberty Property Trust,Real Estate,REIT - Office,Hard Asset,Mid Core,...,2017-12,2016-12,2015-12,2014-12,4.796070e+08,4.796070e+08,2.823400e+08,3.568170e+08,2.380390e+08,2.179100e+08
5,19727.0,302.0,USA,XNYS,VNO,Vornado Realty Trust,Real Estate,REIT - Office,Hard Asset,Mid Core,...,2017-12,2016-12,2015-12,2011-12,4.499540e+08,4.499540e+08,2.274160e+08,9.069170e+08,7.604340e+08,6.623020e+08
7,19849.0,302.0,USA,XNYS,DEI,Douglas Emmett Inc,Real Estate,REIT - Office,Hard Asset,Mid Core,...,2017-12,2016-12,2015-12,2014-12,1.160860e+08,1.160860e+08,9.444300e+07,8.539700e+07,5.838400e+07,4.462100e+07
8,19335.0,302.0,USA,XNYS,MAA,Mid-America Apartment Communities Inc,Real Estate,REIT - Residential,Hard Asset,Mid Core,...,2017-12,2016-12,2015-12,2014-12,2.228990e+08,2.228990e+08,3.283790e+08,2.122220e+08,3.322870e+08,1.479800e+08
9,19694.0,302.0,USA,XNYS,UDR,UDR Inc,Real Estate,REIT - Residential,Hard Asset,Mid Core,...,2017-12,2016-12,2015-12,2014-12,2.031060e+08,2.031060e+08,1.215580e+08,2.927180e+08,3.403830e+08,1.543340e+08
10,19021.0,302.0,USA,XNYS,EGP,EastGroup Properties Inc,Real Estate,REIT - Industrial,Hard Asset,Mid Core,...,2017-12,2016-12,2015-12,2014-12,8.850600e+07,8.850600e+07,8.318300e+07,9.550900e+07,4.786600e+07,4.794100e+07
11,19575.0,302.0,USA,XNYS,LSI,Life Storage Inc,Real Estate,REIT - Industrial,Hard Asset,Mid Core,...,2017-12,2016-12,2015-12,2014-12,2.065900e+08,2.065900e+08,9.636500e+07,8.522500e+07,1.125240e+08,8.853100e+07
12,19013.0,302.0,USA,XNYS,DRE,Duke Realty Corp,Real Estate,REIT - Industrial,Hard Asset,Mid Core,...,2017-12,2016-12,2015-12,2014-12,3.837290e+08,3.837290e+08,1.634431e+09,3.121430e+08,6.153100e+08,2.435880e+08
14,19322.0,302.0,USA,XNYS,MPW,Medical Properties Trust Inc,Real Estate,REIT - Healthcare Facilities,Hard Asset,Mid Core,...,2017-12,2016-12,2015-12,2014-12,1.016685e+09,1.016685e+09,2.897930e+08,2.250480e+08,1.395980e+08,5.052200e+07
15,20144.0,302.0,USA,XNYS,HTA,Healthcare Trust of America Inc,Real Estate,REIT - Healthcare Facilities,Hard Asset,Mid Core,...,2017-12,2016-12,2015-12,2014-12,2.134630e+08,2.134630e+08,6.391600e+07,4.591200e+07,3.293100e+07,4.537100e+07
20,20145.0,302.0,USA,XNYS,EQM,EQM Midstream Partners LP,Energy,Oil & Gas Midstream,Hard Asset,Mid Core,...,2017-12,2016-12,2015-12,2014-12,6.680020e+08,6.680020e+08,5.719040e+08,5.379540e+08,3.934500e+08,2.327730e+08
21,19949.0,302.0,USA,XNYS,WES,Western Midstream Partners LP,Energy,Oil & Gas Midstream,Hard Asset,Mid Core,...,2017-12,2016-12,2015-12,2014-12,3.694290e+08,3.694290e+08,3.766070e+08,3.457720e+08,2.635890e+08,6.657330e+08
22,20219.0,302.0,USA,XNYS,PSXP,Phillips 66 Partners LP,Energy,Oil & Gas Midstream,Hard Asset,Mid Core,...,2017-12,2016-12,2015-12,2014-12,7.960000e+08,7.960000e+08,4.610000e+08,3.010000e+08,1.942000e+08,1.160000e+08
24,19898.0,302.0,USA,XNYS,CVI,CVR Energy Inc,Energy,Oil & Gas Refining & Marketing,Hard Asset,Mid Core,...,2017-12,2016-12,2015-12,2014-12,2.890000e+08,2.890000e+08,2.344000e+08,2.470000e+07,1.696000e+08,1.739000e+08
25,4489405.0,552.0,GBR,LTS,0LA6,STORE Capital Corp,Real Estate,REIT - Diversified,Hard Asset,Mid Core,...,2017-12,2016-12,2015-12,2014-12,2.169700e+08,2.169700e+08,1.620380e+08,1.233250e+08,8.377000e+07,4.813900e+07
26,3216204.0,552.0,GBR,LTS,0IL1,Federal Realty Investment Trust,Real Estate,REIT - Retail,Hard Asset,Mid Core,...,2017-12,2016-12,2015-12,2014-12,2.419070e+08,2.419070e+08,2.899140e+08,2.499100e+08,2.102190e+08,1.645350e+08
27,2292121.0,552.0,GBR,LTS,0IJV,Extra Space Storage Inc,Real Estate,REIT - Industrial,Hard Asset,Mid Core,...,2017-12,2016-12,2015-12,2014-12,4.152890e+08,4.152890e+08,4.790130e+08,3.661270e+08,1.894740e+08,1.783550e+08
31,1965.0,1.0,USA,GREY,UTGPF,UNITE Group PLC,Real Estate,REIT - Diversified,—,Mid Core,...,2017-12,2016-12,2015-12,2014-12,2.357000e+08,2.357000e+08,2.216000e+08,2.240000e+08,3.519000e+08,1.026000e+08
32,11338.0,25.0,USA,PINX,JPRRF,Japan Prime Realty Investment Corp,Real Estate,REIT - Diversified,—,Mid Core,...,2017-12,2016-12,2015-12,2014-12,1.344708e+10,1.344708e+10,1.353322e+10,1.204952e+10,1.135275e+10,1.031164e+10
33,3830.0,1.0,USA,GREY,IGUEF,Iguatemi Empresa de Shopping Centers SA,Real Estate,Real Estate Services,—,Mid Core,...,2017-12,2016-12,2015-12,2014-12,2.563640e+08,2.563640e+08,2.157260e+08,1.615830e+08,1.910910e+08,2.292460e+08
34,4621.0,1.0,USA,GREY,TLMMF,TLG Immobilien AG,Real Estate,Real Estate Services,—,Mid Core,...,2017-12,2016-12,2015-12,2014-12,3.079280e+08,3.079280e+08,2.837970e+08,9.399800e+07,1.306200e+08,8.858800e+07
35,15469.0,25.0,USA,PINX,ENTOF,Entra ASA,Real Estate,Real Estate Services,—,Mid Core,...,2017-12,2016-12,2015-12,2014-12,2.537000e+09,2.537000e+09,4.464000e+09,2.619000e+09,2.648000e+09,1.026800e+09
36,925.0,1.0,USA,GREY,CAOYF,China Aoyuan Group Ltd,Real Estate,Real Estate - General,—,Mid Core,...,2017-12,2016-12,2015-12,2014-12,2.408877e+09,2.408877e+09,1.639928e+09,8.809620e+08,8.121600e+08,8.093920e+08
37,3226.0,1.0,USA,GREY,BSPDF,PT Bumi Serpong Damai Tbk,Real Estate,Real Estate - General,—,Mid Core,...,2017-12,2016-12,2015-12,2014-12,1.293850e+12,1.293850e+12,4.920228e+12,1.796156e+12,2.139497e+12,3.820552e+12
39,2199.0,1.0,USA,GREY,GECFF,Gecina Nom,Real Estate,REIT - Office,—,Mid Core,...,2017-12,2016-12,2015-12,2014-12,1.004985e+09,1.004985e+09,1.895562e+09,8.134720e+08,1.609262e+09,2.813500e+08
41,1226.0,1.0,USA,GREY,BSMAF,Bursa Malaysia Bhd,Financial Services,Financial Exchanges,—,Mid Core,...,2017-12,2016-12,2015-12,2014-12,2.240420e+08,2.240420e+08,2.230400e+08,1.936210e+08,1.986130e+08,1.982260e+08
43,20252.0,302.0,USA,XNYS,ESNT,Essent Group Ltd,Financial Services,Specialty Finance,—,Mid Core,...,2017-12,2016-12,2015-12,2014-12,4.673630e+08,4.673630e+08,3.797470e+08,2.226060e+08,1.573310e+08,8.849700e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50598,514517.0,143.0,DEU,XHAN,KWS,KWS SAAT SE,Consumer Defensive,Farm Products,—,Small Core,...,2017-06,2016-06,2015-06,2014-06,5.081000e+07,5.081000e+07,4.478000e+07,4.555700e+07,4.532500e+07,2.739700e+07
50599,128479.0,16.0,DEU,XFRA,MGE,Australian Vintage Ltd,Consumer Defensive,Beverages - Wineries & Distilleries,—,Small Core,...,2017-06,2016-06,2015-06,2014-06,1.511590e+08,1.497740e+08,1.070450e+08,6.119800e+07,4.931100e+07,4.363500e+07
50600,128479.0,144.0,DEU,XSTU,MGE,Australian Vintage Ltd,Consumer Defensive,Beverages - Wineries & Distilleries,—,Small Core,...,2017-06,2016-06,2015-06,2014-06,1.012560e+08,8.086600e+07,8.592200e+07,7.925200e+07,7.077300e+07,5.505600e+07
50601,128479.0,142.0,DEU,XDUS,MGE,Australian Vintage Ltd,Consumer Defensive,Beverages - Wineries & Distilleries,—,Small Core,...,2017-06,2016-06,2015-06,2014-06,1.012560e+08,8.086600e+07,8.592200e+07,7.925200e+07,7.077300e+07,5.505600e+07
50602,128479.0,145.0,DEU,XHAM,MGE,Australian Vintage Ltd,Consumer Defensive,Beverages - Wineries & Distilleries,—,Small Core,...,2017-06,2016-06,2015-06,2014-06,1.511590e+08,1.497740e+08,1.070450e+08,6.119800e+07,4.931100e+07,4.363500e+07
50603,1186308.0,552.0,GBR,LTS,0RNS,Rapid Nutrition PLC,Healthcare,Drug Manufacturers - Specialty & Generic,—,Small Core,...,2017-06,2016-06,2015-06,2014-06,1.511590e+08,1.497740e+08,1.070450e+08,6.119800e+07,4.931100e+07,4.363500e+07
50604,218224.0,552.0,GBR,LTS,0OD6,Ramsay Generale de Sante SA,Healthcare,Health Care Plans,—,Small Core,...,2017-06,2016-06,2014-12,2013-12,1.511590e+08,1.497740e+08,1.070450e+08,6.119800e+07,4.931100e+07,4.363500e+07
50605,676196.0,552.0,GBR,LTS,0MS9,Societa Sportiva Lazio SPA,Consumer Cyclical,Leisure,—,Small Core,...,2017-06,2016-06,2015-06,2014-06,6.300000e+07,5.070000e+07,6.600000e+07,4.120000e+07,4.540000e+07,2.740000e+07
50606,283941.0,138.0,IRL,XETR,K1R,KROMI Logistik AG,Industrials,Industrial Distribution,—,Small Core,...,2017-06,2016-06,2015-06,2014-06,6.300000e+07,5.070000e+07,6.600000e+07,4.120000e+07,4.540000e+07,2.740000e+07
50614,121473.0,17.0,DEU,XBER,MEZ,Meredith Corp,Consumer Cyclical,Publishing,Distressed,Small Core,...,2017-06,2016-06,2015-06,2014-06,4.609000e+06,3.386000e+06,1.498000e+06,1.584000e+06,1.353000e+06,2.574000e+06
50617,284990.0,16.0,DEU,XFRA,MX2,Matrix Service Co,Energy,Oil & Gas Equipment & Services,Distressed,Small Core,...,2017-06,2016-06,2015-06,2014-06,6.305600e+07,6.305600e+07,3.642600e+07,5.466100e+07,1.149700e+07,2.794700e+07
50618,284990.0,144.0,DEU,XSTU,MX2,Matrix Service Co,Energy,Oil & Gas Equipment & Services,Distressed,Small Core,...,2017-06,2016-06,2015-06,2014-06,3.106130e+08,4.248580e+08,6.851080e+08,8.414890e+08,9.574740e+08,1.022290e+09
50619,46655.0,16.0,DEU,XFRA,9SI,Standex International Corp,Industrials,Diversified Industrials,Cyclical,Small Core,...,2017-06,2016-06,2015-06,2014-06,8.010700e+07,7.948800e+07,8.579000e+07,6.534200e+07,5.051600e+07,2.798600e+07
50620,283917.0,16.0,DEU,XFRA,3GT,Radiant Logistics Inc,Industrials,Integrated Shipping & Logistics,Cyclical,Small Core,...,2017-06,2016-06,2015-06,2014-06,8.010700e+07,7.948800e+07,8.579000e+07,6.534200e+07,5.051600e+07,2.798600e+07
50621,895866.0,16.0,DEU,XFRA,M05,Malibu Boats Inc Class A,Consumer Cyclical,Recreational Vehicles,Cyclical,Small Core,...,2017-06,2016-06,2015-06,2014-06,3.106130e+08,4.248580e+08,6.851080e+08,8.414890e+08,9.574740e+08,1.022290e+09
50622,681724.0,16.0,DEU,XFRA,1SG,MasterCraft Boat Holdings Inc,Consumer Cyclical,Recreational Vehicles,Cyclical,Small Core,...,2017-06,2016-06,2015-06,2014-06,3.106130e+08,4.248580e+08,6.851080e+08,8.414890e+08,9.574740e+08,1.022290e+09
50623,681724.0,17.0,DEU,XBER,1SG,MasterCraft Boat Holdings Inc,Consumer Cyclical,Recreational Vehicles,Cyclical,Small Core,...,2017-06,2016-06,2015-06,2014-06,3.106130e+08,4.248580e+08,6.851080e+08,8.414890e+08,9.574740e+08,1.022290e+09
50624,681724.0,141.0,DEU,XMUN,1SG,MasterCraft Boat Holdings Inc,Consumer Cyclical,Recreational Vehicles,Cyclical,Small Core,...,2017-06,2016-06,2015-06,2014-06,3.106130e+08,4.248580e+08,6.851080e+08,8.414890e+08,9.574740e+08,1.022290e+09
50625,1057452.0,16.0,DEU,XFRA,LA8N,Lantronix Inc,Technology,Communication Equipment,Cyclical,Small Core,...,2017-06,2016-06,2015-06,2014-06,3.106130e+08,4.248580e+08,6.851080e+08,8.414890e+08,9.574740e+08,1.022290e+09
50626,780497.0,16.0,DEU,XFRA,PDXN,Pro-Dex Inc,Healthcare,Medical Instruments & Supplies,Speculative Growth,Small Core,...,2017-06,2016-06,2015-06,2014-06,3.106130e+08,4.248580e+08,6.851080e+08,8.414890e+08,9.574740e+08,1.022290e+09
50630,279091.0,143.0,DEU,XHAN,HF1,The Hain Celestial Group Inc,Consumer Defensive,Packaged Foods,Slow Growth,Small Core,...,2017-06,2016-06,2015-06,2014-06,5.339100e+07,5.339100e+07,6.499600e+07,3.790200e+07,2.399500e+07,2.500100e+07
50647,739038.0,17.0,DEU,XBER,TU9,Transurban Group,Industrials,Infrastructure Operations,—,Large Growth,...,2017-06,2016-06,2015-06,2014-06,4.270000e+05,4.270000e+05,1.721000e+06,5.914000e+06,2.990000e+05,1.199000e+06
50650,739038.0,145.0,DEU,XHAM,TU9,Transurban Group,Industrials,Infrastructure Operations,—,Large Growth,...,2017-06,2016-06,2015-06,2014-06,1.995400e+07,1.959000e+07,1.664400e+07,1.829800e+07,1.693900e+07,1.179700e+07
50671,36965.0,16.0,DEU,XFRA,14L,The a2 Milk Co Ltd,Consumer Defensive,Farm Products,—,Large Growth,...,2017-06,2016-06,2015-06,2014-06,1.519120e+08,1.519120e+08,1.653050e+08,1.613640e+08,1.422490e+08,1.149930e+08
50674,36965.0,144.0,DEU,XSTU,14L,The a2 Milk Co Ltd,Consumer Defensive,Farm Products,—,Large Growth,...,2017-06,2016-06,2015-06,2014-06,5.944600e+04,5.040500e+04,2.116030e+05,2.735020e+05,3.152370e+05,4.156960e+05
50682,505180.0,144.0,DEU,XSTU,T7W,Treasury Wine Estates Ltd,Consumer Defensive,Beverages - Wineries & Distilleries,—,Large Growth,...,2017-06,2016-06,2015-06,2014-06,2.204340e+08,2.204340e+08,3.966070e+08,5.513800e+08,4.518380e+08,4.159300e+08
50683,20099.0,145.0,DEU,XHAM,PER,Pernod Ricard SA,Consumer Defensive,Beverages - Wineries & Distilleries,—,Large Growth,...,2017-06,2016-06,2015-06,2014-06,2.204340e+08,2.204340e+08,3.966070e+08,5.513800e+08,4.518380e+08,4.159300e+08
50684,821545.0,553.0,FRA,XPAR,RI,Pernod Ricard SA,Consumer Defensive,Beverages - Wineries & Distilleries,—,Large Growth,...,2017-06,2016-06,2015-06,2014-06,2.204340e+08,2.204340e+08,3.966070e+08,5.513800e+08,4.518380e+08,4.159300e+08
50685,590174.0,16.0,DEU,XFRA,ELAA,The Estee Lauder Companies Inc Class A,Consumer Defensive,Household & Personal Products,Slow Growth,Large Growth,...,2017-06,2016-06,2015-06,2014-06,2.204340e+08,2.204340e+08,3.966070e+08,5.513800e+08,4.518380e+08,4.159300e+08
50686,590174.0,17.0,DEU,XBER,ELAA,The Estee Lauder Companies Inc Class A,Consumer Defensive,Household & Personal Products,Slow Growth,Large Growth,...,2017-06,2016-06,2015-06,2014-06,2.204340e+08,2.204340e+08,3.966070e+08,5.513800e+08,4.518380e+08,4.159300e+08

#### 7 Years:

In [112]:
cols = ['country_c3', 'exchange_sym', 'ticker', 'company', 'sector', 'industry'] + \
        [col for col in df_keyratios.columns if col.startswith('i4_') or col.startswith('Y')]

df_rule1_7 = (df_keyratios
              .where((df_keyratios['security_type'] == 'Stock') & 
                     (df_keyratios['Y9'] >= pd.to_datetime('2018-01')) & (df_keyratios['i4_Y10'] > 0) & 
                     ((df_keyratios['i4_Y9'] > 0) | (df_keyratios['i4_Y9'].isna())) & 
                     ((df_keyratios['i4_Y8'] > 0) | (df_keyratios['i4_Y8'].isna())) & 
                     ((df_keyratios['i4_Y7'] > 0) | (df_keyratios['i4_Y7'].isna())) & 
                     ((df_keyratios['i4_Y6'] > 0) | (df_keyratios['i4_Y6'].isna())) & 
                     ((df_keyratios['i4_Y5'] > 0) | (df_keyratios['i4_Y5'].isna())) & 
                     ((df_keyratios['i4_Y4'] > 0) | (df_keyratios['i4_Y4'].isna())) & 
                     ((df_keyratios['i4_Y3'] > 0) | (df_keyratios['i4_Y3'].isna())))
              .dropna(axis=0, how='all'))[cols]

In [113]:
df_rule1_7

,country_c3,exchange_sym,ticker,company,sector,industry,i4_Y0,i4_Y1,i4_Y2,i4_Y3,...,Y1,Y2,Y3,Y4,Y5,Y6,Y7,Y8,Y9,Y10
0,USA,ARCX,OGCP,Empire State Realty OP LP Operating Partnershi...,Real Estate,REIT - Diversified,NaN,NaN,57.0,49.0,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
1,USA,ARCX,FISK,Empire State Realty OP LP Operating Partnershi...,Real Estate,REIT - Diversified,NaN,NaN,57.0,49.0,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
2,USA,ARCX,ESBA,Empire State Realty OP LP Operating Partnershi...,Real Estate,REIT - Diversified,NaN,NaN,57.0,49.0,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
4,USA,XNYS,LPT,Liberty Property Trust,Real Estate,REIT - Office,56.0,128.0,184.0,137.0,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
5,USA,XNYS,VNO,Vornado Realty Trust,Real Estate,REIT - Office,721.0,636.0,395.0,106.0,...,2007-12-01,2008-12-01,2009-12-01,2010-12-01,2011-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
7,USA,XNYS,DEI,Douglas Emmett Inc,Real Estate,REIT - Office,-27.0,-26.0,1.0,23.0,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
8,USA,XNYS,MAA,Mid-America Apartment Communities Inc,Real Estate,REIT - Residential,37.0,30.0,49.0,105.0,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
9,USA,XNYS,UDR,UDR Inc,Real Estate,REIT - Residential,-88.0,-103.0,20.0,212.0,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
10,USA,XNYS,EGP,EastGroup Properties Inc,Real Estate,REIT - Industrial,27.0,18.0,22.0,32.0,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
11,USA,XNYS,LSI,Life Storage Inc,Real Estate,REIT - Industrial,20.0,41.0,31.0,55.0,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
20,USA,XNYS,EQM,EQM Midstream Partners LP,Energy,Oil & Gas Midstream,14.0,19.0,33.0,55.0,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
21,USA,XNYS,WES,Western Midstream Partners LP,Energy,Oil & Gas Midstream,77.0,126.0,76.0,34.0,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
22,USA,XNYS,PSXP,Phillips 66 Partners LP,Energy,Oil & Gas Midstream,NaN,NaN,39.0,NaN,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
24,USA,XNYS,CVI,CVR Energy Inc,Energy,Oil & Gas Refining & Marketing,69.0,14.0,346.0,379.0,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
25,GBR,LTS,0LA6,STORE Capital Corp,Real Estate,REIT - Diversified,NaN,NaN,NaN,8.0,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
26,GBR,LTS,0IL1,Federal Realty Investment Trust,Real Estate,REIT - Retail,98.0,123.0,144.0,152.0,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
27,GBR,LTS,0IJV,Extra Space Storage Inc,Real Estate,REIT - Industrial,32.0,26.0,50.0,117.0,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
29,GBR,LTS,0HGC,Apache Corp,Energy,Oil & Gas E&P,-284.0,NaN,NaN,NaN,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
31,USA,GREY,UTGPF,UNITE Group PLC,Real Estate,REIT - Diversified,-34.0,20.0,2.0,125.0,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
33,USA,GREY,IGUEF,Iguatemi Empresa de Shopping Centers SA,Real Estate,Real Estate Services,86.0,152.0,152.0,268.0,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
34,USA,GREY,TLMMF,TLG Immobilien AG,Real Estate,Real Estate Services,NaN,NaN,NaN,NaN,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
41,USA,GREY,BSMAF,Bursa Malaysia Bhd,Financial Services,Financial Exchanges,178.0,116.0,151.0,151.0,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
46,USA,XNAS,ACGL,Arch Capital Group Ltd,Financial Services,Insurance - Diversified,877.0,843.0,436.0,593.0,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
52,USA,PINX,PCDVF,Pacific Century Regional Developments Ltd,Financial Services,Asset Management,270.0,133.0,54.0,40.0,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
53,USA,PINX,VPGLF,Value Partners Group Ltd,Financial Services,Asset Management,319.0,653.0,167.0,376.0,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
54,USA,GREY,HCXLF,Hiscox Ltd,Financial Services,Insurance - Property & Casualty,454.0,276.0,33.0,336.0,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
56,USA,PINX,ELFIF,E-L Financial Corp Ltd,Financial Services,Insurance - Property & Casualty,-185.0,145.0,-45.0,473.0,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
57,USA,PINX,ITCXF,Intercorp Financial Services Inc,Financial Services,Banks - Regional - Latin America,505.0,499.0,698.0,706.0,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
75,USA,PINX,FUPBY,Fuchs Petrolub SE ADR,Basic Materials,Chemicals,120.0,170.0,182.0,206.0,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
76,USA,PINX,FUPEF,Fuchs Petrolub SE,Basic Materials,Chemicals,120.0,170.0,182.0,206.0,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68278,DEU,XFRA,LAZ,La-Z-Boy Inc,Consumer Cyclical,Home Furnishings & Fixtures,-121.0,33.0,24.0,88.0,...,2010-04-01,2011-04-01,2012-04-01,2013-04-01,2014-04-01,2015-04-01,2016-04-01,2017-04-01,2018-04-01,TTM
68279,DEU,XSTU,LAZ,La-Z-Boy Inc,Consumer Cyclical,Home Furnishings & Fixtures,-121.0,33.0,24.0,88.0,...,2010-04-01,2011-04-01,2012-04-01,2013-04-01,2014-04-01,2015-04-01,2016-04-01,2017-04-01,2018-04-01,TTM
68280,DEU,XFRA,20V,National Beverage Corp,Consumer Defensive,Beverages - Soft Drinks,25.0,33.0,41.0,44.0,...,2010-04-01,2011-04-01,2012-04-01,2013-04-01,2014-04-01,2015-04-01,2016-04-01,2017-04-01,2018-04-01,TTM
68281,DEU,XMUN,20V,National Beverage Corp,Consumer Defensive,Beverages - Soft Drinks,25.0,33.0,41.0,44.0,...,2010-04-01,2011-04-01,2012-04-01,2013-04-01,2014-04-01,2015-04-01,2016-04-01,2017-04-01,2018-04-01,TTM
68282,DEU,XSTU,20V,National Beverage Corp,Consumer Defensive,Beverages - Soft Drinks,25.0,33.0,41.0,44.0,...,2010-04-01,2011-04-01,2012-04-01,2013-04-01,2014-04-01,2015-04-01,2016-04-01,2017-04-01,2018-04-01,TTM
68283,DEU,XFRA,49S,Superdry PLC,Consumer Cyclical,Apparel Manufacturing,8.0,72.0,30.0,36.0,...,2010-04-01,2011-04-01,2012-04-01,2013-04-01,2014-04-01,2015-04-01,2016-04-01,2017-04-01,2018-04-01,TTM
68284,DEU,XSTU,49S,Superdry PLC,Consumer Cyclical,Apparel Manufacturing,8.0,72.0,30.0,36.0,...,2010-04-01,2011-04-01,2012-04-01,2013-04-01,2014-04-01,2015-04-01,2016-04-01,2017-04-01,2018-04-01,TTM
68292,GBR,XLON,MSI,MS International PLC,Industrials,Aerospace & Defense,4.0,2.0,6.0,6.0,...,2010-04-01,2011-04-01,2012-04-01,2013-04-01,2014-04-01,2015-04-01,2016-04-01,2017-04-01,2018-04-01,TTM
68296,USA,XNAS,BBBY,Bed Bath & Beyond Inc,Consumer Cyclical,Specialty Retail,425.0,600.0,791.0,990.0,...,2010-02-01,2011-02-01,2012-02-01,2013-02-01,2014-02-01,2015-02-01,2016-02-01,2017-02-01,2018-02-01,TTM
68297,DEU,XFRA,ANP,Apogee Enterprises Inc,Basic Materials,Building Materials,51.0,32.0,-10.0,5.0,...,2010-02-01,2011-02-01,2012-02-01,2013-02-01,2014-02-01,2015-02-01,2016-02-01,2017-02-01,2018-02-01,TTM
68298,DEU,XBER,ANP,Apogee Enterprises Inc,Basic Materials,Building Materials,51.0,32.0,-10.0,5.0,...,2010-02-01,2011-02-01,2012-02-01,2013-02-01,2014-02-01,2015-02-01,2016-02-01,2017-02-01,2018-02-01,TTM
68299,DEU,XFRA,BBY,Bed Bath & Beyond Inc,Consumer Cyclical,Specialty Retail,425.0,600.0,791.0,990.0,...,2010-02-01,2011-02-01,2012-02-01,2013-02-01,2014-02-01,2015-02-01,2016-02-01,2017-02-01,2018-02-01,TTM
68300,DEU,XBER,BBY,Bed Bath & Beyond Inc,Consumer Cyclical,Specialty Retail,425.0,600.0,791.0,990.0,...,2010-02-01,2011-02-01,2012-02-01,2013-02-01,2014-02-01,2015-02-01,2016-02-01,2017-02-01,2018-02-01,TTM
68301,DEU,XMUN,BBY,Bed Bath & Beyond Inc,Consumer Cyclical,Specialty Retail,425.0,600.0,791.0,990.0,...,2010-02-01,2011-02-01,2012-02-01,2013-02-01,2014-02-01,2015-02-01,2016-02-01,2017-02-01,2018-02-01,TTM
68302,DEU,XSTU,BBY,Bed Bath & Beyond Inc,Consumer Cyclical,Specialty Retail,425.0,600.0,791.0,990.0,...,2010-02-01,2011-02-01,2012-02-01,2013-02-01,2014-02-01,2015-02-01,2016-02-01,2017-02-01,2018-02-01,TTM
68303,DEU,XDUS,BBY,Bed Bath & Beyond Inc,Consumer Cyclical,Specialty Retail,425.0,600.0,791.0,990.0,...,2010-02-01,2011-02-01,2012-02-01,2013-02-01,2014-02-01,2015-02-01,2016-02-01,2017-02-01,2018-02-01,TTM
68304,DEU,XHAM,BBY,Bed Bath & Beyond Inc,Consumer Cyclical,Specialty Retail,425.0,600.0,791.0,990.0,...,2010-02-01,2011-02-01,2012-02-01,2013-02-01,2014-02-01,2015-02-01,2016-02-01,2017-02-01,2018-02-01,TTM
68308,DEU,XFRA,3L1,Marcus Corp,Consumer Cyclical,Media - Diversified,17.0,16.0,14.0,23.0,...,2010-05-01,2011-05-01,2012-05-01,2013-05-01,2014-05-01,2015-05-01,2016-12-01,2017-12-01,2018-12-01,TTM
68335,AUS,XASX,BLX,Beacon Lighting Group Ltd,Consumer Cyclical,Specialty Retail,NaN,NaN,NaN,NaN,...,2010-06-01,2011-06-01,2012-06-01,2013-06-01,2014-06-01,2015-06-01,2016-06-01,2017-06-01,2018-06-01,TTM
68340,DEU,XFRA,APA,Apache Corp,Energy,Oil & Gas E&P,-284.0,NaN,NaN,NaN,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
68341,DEU,XBER,APA,Apache Corp,Energy,Oil & Gas E&P,-284.0,NaN,NaN,NaN,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
68342,DEU,XMUN,APA,Apache Corp,Energy,Oil & Gas E&P,-284.0,NaN,NaN,NaN,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
68343,DEU,XSTU,APA,Apache Corp,Energy,Oil & Gas E&P,-284.0,NaN,NaN,NaN,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
68344,DEU,XDUS,APA,Apache Corp,Energy,Oil & Gas E&P,-284.0,NaN,NaN,NaN,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
68356,DEU,XFRA,HI8H,HiQ International AB,Technology,Information Technology Services,106.0,111.0,136.0,137.0,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
68383,DEU,XFRA,HAS,Hasbro Inc,Consumer Cyclical,Leisure,375.0,398.0,385.0,336.0,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
68384,DEU,XBER,HAS,Hasbro Inc,Consumer Cyclical,Leisure,375.0,398.0,385.0,336.0,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
68385,DEU,XMUN,HAS,Hasbro Inc,Consumer Cyclical,Leisure,375.0,398.0,385.0,336.0,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
68386,DEU,XSTU,HAS,Hasbro Inc,Consumer Cyclical,Leisure,375.0,398.0,385.0,336.0,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM
68387,DEU,XDUS,HAS,Hasbro Inc,Consumer Cyclical,Leisure,375.0,398.0,385.0,336.0,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,TTM

[return to top of this section](#value),
[return to the top](#top)
<a id="rule2"></a>
### Rule 2. Uniterrupted and increasing *Dividends* for past 7 yrs

**a. Identify *Dividends* column label in** `df_keyratios`

In [114]:
icol = df_labels_kratios[df_labels_kratios == 'Dividends'].index[0]
icol

'i6'

**b. Get column headers for *Dividends* for the past 5 yrs**

In [115]:
main_cols2 = ['ticker_id', 'exchange_id', 
             #'country_c3', 'exchange_sym', 'ticker', 'company', 
             #'sector', 'industry', 'stock_type', 'style', 
             'Y10', 'Y9', 'Y8', 'Y7', 'Y6', 'Y5']
icols = sorted([col for col in df_keyratios.columns if icol + '_' in col], 
               key=lambda col: int(col[4:]), reverse=True)[:8]
icols

['i6_Y10', 'i6_Y9', 'i6_Y8', 'i6_Y7', 'i6_Y6', 'i6_Y5', 'i6_Y4', 'i6_Y3']

**c. Create 'Net Income' DataFrame**

In [116]:
df_rule2 = (df_keyratios
            .where((df_keyratios['security_type'] == 'Stock') & 
                   (df_keyratios['Y9'] >= pd.to_datetime('2018-01')) & 
                   (df_keyratios['i6_Y10'].notna()) & (df_keyratios['i6_Y9'].notna()) &
                   (df_keyratios['i6_Y8'].notna()) & (df_keyratios['i6_Y7'].notna()) &
                   (df_keyratios['i6_Y6'].notna()) & (df_keyratios['i6_Y5'].notna()) & 
                   (df_keyratios['i6_Y4'].notna()) & (df_keyratios['i6_Y3'].notna()) & 
                   (df_keyratios['i6_Y10'] >= df_keyratios['i6_Y9']) & 
                   (df_keyratios['i6_Y9'] >= df_keyratios['i6_Y8']) & 
                   (df_keyratios['i6_Y8'] >= df_keyratios['i6_Y7']) & 
                   (df_keyratios['i6_Y7'] >= df_keyratios['i6_Y6']) & 
                   (df_keyratios['i6_Y6'] >= df_keyratios['i6_Y5']) & 
                   (df_keyratios['i6_Y5'] >= df_keyratios['i6_Y4']) & 
                   (df_keyratios['i6_Y4'] >= df_keyratios['i6_Y3']))
            .dropna(axis=0, how='all').sort_values(by='Y9', ascending=False))[main_cols2 + icols]

df_rule2.columns = main_cols2 + [col.replace('i6', 'Dividend') for col in icols]

In [117]:
df_rule2

,ticker_id,exchange_id,Y10,Y9,Y8,Y7,Y6,Y5,Dividend_Y10,Dividend_Y9,Dividend_Y8,Dividend_Y7,Dividend_Y6,Dividend_Y5,Dividend_Y4,Dividend_Y3
30977,19768.0,302.0,TTM,2019-01-01,2018-01-01,2017-01-01,2016-01-01,2015-01-01,1.72,1.72,1.56,1.48,1.40,1.32,1.24,0.88
31125,19325.0,302.0,TTM,2019-01-01,2018-01-01,2017-01-01,2016-01-01,2015-01-01,0.72,0.72,0.72,0.72,0.72,0.72,0.72,0.72
31114,19143.0,302.0,TTM,2019-01-01,2018-01-01,2017-01-01,2016-01-01,2015-01-01,0.90,0.90,0.90,0.90,0.90,0.90,0.80,0.80
31115,19428.0,302.0,TTM,2019-01-01,2018-01-01,2017-01-01,2016-01-01,2015-01-01,1.36,1.36,1.08,1.08,1.00,0.84,0.72,0.60
31116,16616.0,44.0,TTM,2019-01-01,2018-01-01,2017-01-01,2016-01-01,2015-01-01,0.24,0.24,0.24,0.24,0.24,0.24,0.24,0.18
31118,16890.0,44.0,TTM,2019-01-01,2018-01-01,2017-01-01,2016-01-01,2015-01-01,0.90,0.90,0.64,0.54,0.47,0.40,0.34,0.28
31121,19104.0,302.0,TTM,2019-01-01,2018-01-01,2017-01-01,2016-01-01,2015-01-01,1.52,1.52,1.52,1.48,1.44,1.32,1.10,0.80
31122,18997.0,302.0,TTM,2019-01-01,2018-01-01,2017-01-01,2016-01-01,2015-01-01,0.40,0.40,0.34,0.28,0.26,0.24,0.22,0.20
31128,19393.0,302.0,TTM,2019-01-01,2018-01-01,2017-01-01,2016-01-01,2015-01-01,1.48,1.48,1.48,1.48,1.48,1.32,1.20,1.08
55497,700189.0,16.0,TTM,2019-01-01,2018-01-01,2017-01-01,2016-01-01,2015-01-01,0.54,0.54,0.50,0.46,0.40,0.38,0.38,0.32
31129,18994.0,302.0,TTM,2019-01-01,2018-01-01,2017-01-01,2016-01-01,2015-01-01,0.90,0.90,0.68,0.60,0.55,0.50,0.50,0.50
31133,18794.0,302.0,TTM,2019-01-01,2018-01-01,2017-01-01,2016-01-01,2015-01-01,1.80,1.80,1.36,1.12,0.92,0.72,0.68,0.62
31134,19619.0,302.0,TTM,2019-01-01,2018-01-01,2017-01-01,2016-01-01,2015-01-01,2.52,2.52,2.44,2.32,2.16,1.90,1.58,1.32
31135,19253.0,302.0,TTM,2019-01-01,2018-01-01,2017-01-01,2016-01-01,2015-01-01,0.53,0.53,0.49,0.45,0.40,0.34,0.31,0.25
31139,234350.0,16.0,TTM,2019-01-01,2018-01-01,2017-01-01,2016-01-01,2015-01-01,1.48,1.48,1.24,1.04,0.88,0.72,0.60,0.36
31146,1497673.0,16.0,TTM,2019-01-01,2018-01-01,2017-01-01,2016-01-01,2015-01-01,0.90,0.90,0.90,0.90,0.90,0.90,0.80,0.80
55477,16865.0,44.0,TTM,2019-01-01,2018-01-01,2017-01-01,2016-01-01,2015-01-01,0.52,0.52,0.52,0.52,0.52,0.50,0.48,0.42
55498,700189.0,17.0,TTM,2019-01-01,2018-01-01,2017-01-01,2016-01-01,2015-01-01,0.54,0.54,0.50,0.46,0.40,0.38,0.38,0.14
31148,1497673.0,144.0,TTM,2019-01-01,2018-01-01,2017-01-01,2016-01-01,2015-01-01,0.90,0.90,0.90,0.90,0.90,0.90,0.80,0.80
57049,19276.0,302.0,TTM,2019-01-01,2018-01-01,2017-01-01,2016-01-01,2015-01-01,2.40,2.40,2.40,2.40,2.00,1.36,1.20,1.00
57038,18662.0,302.0,TTM,2019-01-01,2018-01-01,2017-01-01,2016-01-01,2015-01-01,0.80,0.80,0.80,0.80,0.80,0.80,0.80,0.70
57039,18891.0,302.0,TTM,2019-01-01,2018-01-01,2017-01-01,2016-01-01,2015-01-01,0.34,0.34,0.33,0.32,0.31,0.30,0.24,0.21
57043,16940.0,44.0,TTM,2019-01-01,2018-01-01,2017-01-01,2016-01-01,2015-01-01,0.32,0.32,0.29,0.28,0.26,0.24,0.24,0.15
57044,248426.0,302.0,TTM,2019-01-01,2018-01-01,2017-01-01,2016-01-01,2015-01-01,1.00,1.00,0.80,0.80,0.80,0.75,0.38,0.34
57045,18825.0,302.0,TTM,2019-01-01,2018-01-01,2017-01-01,2016-01-01,2015-01-01,1.00,1.00,1.00,1.00,0.94,0.89,0.82,0.80
57048,19249.0,302.0,TTM,2019-01-01,2018-01-01,2017-01-01,2016-01-01,2015-01-01,2.44,2.44,2.20,2.00,1.80,1.56,1.40,1.28
57050,19091.0,302.0,TTM,2019-01-01,2018-01-01,2017-01-01,2016-01-01,2015-01-01,1.38,1.38,1.24,1.10,1.00,0.88,0.80,0.72
55501,700189.0,145.0,TTM,2019-01-01,2018-01-01,2017-01-01,2016-01-01,2015-01-01,0.54,0.54,0.50,0.46,0.40,0.38,0.38,0.14
57052,19073.0,302.0,TTM,2019-01-01,2018-01-01,2017-01-01,2016-01-01,2015-01-01,1.51,1.51,1.51,1.49,1.39,1.19,0.95,0.80
58835,18820.0,302.0,TTM,2019-01-01,2018-01-01,2017-01-01,2016-01-01,2015-01-01,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54218,806893.0,18.0,TTM,2018-02-01,2017-02-01,2016-02-01,2015-02-01,2014-02-01,0.18,0.17,0.10,0.06,0.06,0.06,0.06,0.06
58811,595768.0,18.0,TTM,2018-02-01,2017-02-01,2016-02-01,2015-02-01,2014-02-01,0.14,0.14,0.14,0.14,0.14,0.14,0.13,0.13
27711,18660.0,302.0,TTM,2018-02-01,2017-02-01,2016-02-01,2015-02-01,2014-02-01,0.68,0.68,0.64,0.60,0.58,0.56,0.53,0.50
58767,19441.0,302.0,TTM,2018-02-01,2017-02-01,2016-02-01,2015-02-01,2014-02-01,0.40,0.40,0.40,0.40,0.40,0.40,0.40,0.40
58809,16004.0,44.0,TTM,2018-02-01,2017-02-01,2016-02-01,2015-02-01,2014-02-01,0.63,0.58,0.52,0.46,0.41,0.37,0.36,0.33
32896,527706.0,18.0,TTM,2018-01-01,2017-01-01,2016-01-01,2015-01-01,2014-01-01,0.02,0.02,0.01,0.01,0.01,0.01,0.01,0.01
58481,300054.0,16.0,TTM,2018-01-01,2017-01-01,2016-01-01,2015-01-01,2014-01-01,79.00,77.00,64.00,54.00,50.00,36.00,28.00,20.00
58396,7467.0,25.0,TTM,2018-01-01,2017-01-01,2016-01-01,2015-01-01,2014-01-01,0.21,0.20,0.20,0.20,0.18,0.18,0.18,0.15
58516,20675.0,18.0,TTM,2018-01-01,2017-01-01,2016-01-01,2013-07-01,2012-07-01,0.06,0.06,0.04,0.03,0.02,0.02,0.02,0.02
33035,35797.0,649.0,TTM,2018-01-01,2017-01-01,2016-01-01,2015-01-01,2014-01-01,0.16,0.15,0.13,0.12,0.11,0.09,0.07,0.04
68163,65166.0,17.0,TTM,2018-01-01,2017-01-01,2016-01-01,2015-01-01,2014-01-01,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02
68162,65166.0,16.0,TTM,2018-01-01,2017-01-01,2016-01-01,2015-01-01,2014-01-01,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02
58511,732943.0,18.0,TTM,2018-01-01,2017-01-01,2016-01-01,2015-01-01,2014-01-01,1.05,0.95,0.80,0.69,0.57,0.48,0.42,0.37
58505,26270.0,649.0,TTM,2018-01-01,2017-01-01,2016-01-01,2015-01-01,2014-01-01,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02
58485,300054.0,142.0,TTM,2018-01-01,2017-01-01,2016-01-01,2015-01-01,2014-01-01,79.00,77.00,64.00,54.00,50.00,36.00,28.00,20.00
58482,300054.0,17.0,TTM,2018-01-01,2017-01-01,2016-01-01,2015-01-01,2014-01-01,79.00,77.00,64.00,54.00,50.00,36.00,28.00,20.00
32696,232250.0,18.0,TTM,2018-01-01,2017-01-01,2016-01-01,2015-01-01,2014-01-01,0.11,0.10,0.10,0.10,0.10,0.09,0.09,0.08
32695,757740.0,18.0,TTM,2018-01-01,2017-01-01,2016-01-01,2015-01-01,2014-01-01,0.04,0.04,0.03,0.02,0.02,0.02,0.01,0.01
32676,35953.0,649.0,TTM,2018-01-01,2017-01-01,2016-01-01,2015-01-01,2014-01-01,1.28,1.28,1.24,1.20,1.16,1.12,1.04,0.96
32671,18093.0,649.0,TTM,2018-01-01,2016-12-01,2015-12-01,2014-12-01,2013-12-01,0.24,0.24,0.24,0.24,0.24,0.24,0.24,0.24
32609,612704.0,16.0,TTM,2018-01-01,2017-01-01,2016-01-01,2015-01-01,2014-01-01,50.00,50.00,50.00,50.00,50.00,50.00,50.00,50.00
32589,16028.0,44.0,TTM,2018-01-01,2017-01-01,2016-01-01,2015-01-01,2014-01-01,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28
55087,531363.0,142.0,TTM,2018-01-01,2017-01-01,2016-01-01,2015-01-01,2014-01-01,1.58,1.58,1.58,1.53,1.43,1.22,1.04,0.31
28919,141566.0,18.0,TTM,2018-01-01,2017-01-01,2016-01-01,2015-01-01,2014-01-01,0.60,0.55,0.49,0.42,0.35,0.28,0.24,0.21
28918,121576.0,18.0,TTM,2018-01-01,2017-01-01,2016-01-01,2015-01-01,2014-01-01,1.58,1.58,1.58,1.53,1.43,1.10,0.94,0.81
55086,531363.0,144.0,TTM,2018-01-01,2017-01-01,2016-01-01,2015-01-01,2014-01-01,1.58,1.58,1.58,1.53,1.43,1.22,1.04,0.89
55085,531363.0,17.0,TTM,2018-01-01,2017-01-01,2016-01-01,2015-01-01,2014-01-01,1.58,1.58,1.58,1.53,1.43,1.22,1.04,0.89
55084,531363.0,16.0,TTM,2018-01-01,2017-01-01,2016-01-01,2015-01-01,2014-01-01,1.58,1.58,1.58,1.53,1.43,1.22,0.94,0.89
55082,10994.0,25.0,TTM,2018-01-01,2017-01-01,2016-01-01,2015-01-01,2014-01-01,1.58,1.58,1.58,1.53,1.43,1.22,1.04,0.31
32570,15749.0,547.0,TTM,2018-01-01,2017-01-01,2016-01-01,2015-01-01,2014-01-01,0.02,0.02,0.01,0.01,0.01,0.01,0.01,0.01

[return to top of this section](#value),
[return to the top](#top)
<a id="rule3"></a>
### Rule 3. P/E Ratio of 25 or less for the past 7 yrs and less then 20 for TTM

In [134]:
pe_cols = [col for col in df_vals.columns if 'PE_' in col]
pe_cols = ['ticker_id', 'exchange_id'] + [pe_cols[len(pe_cols)-i-1] for i in range(len(pe_cols))][:8]
pe_cols

['ticker_id',
 'exchange_id',
 'PE_TTM',
 'PE_2018',
 'PE_2017',
 'PE_2016',
 'PE_2015',
 'PE_2014',
 'PE_2013',
 'PE_2012']

In [136]:
df_rule3 = (df_vals[pe_cols]
            .where((df_vals['PE_TTM'] <= 20) & (df_vals['PE_2018'] <= 25) &
                   (df_vals['PE_2017'] <= 25) & (df_vals['PE_2016'] <= 25) &
                   (df_vals['PE_2015'] <= 25) & (df_vals['PE_2014'] <= 25) &
                   (df_vals['PE_2013'] <= 25) & (df_vals['PE_2012'] <= 25)).dropna(axis=0, how='all'))

In [137]:
df_rule3

,ticker_id,exchange_id,PE_TTM,PE_2018,PE_2017,PE_2016,PE_2015,PE_2014,PE_2013,PE_2012
643,644.0,1.0,14.3,15.0,15.2,15.1,13.6,17.7,11.8,10.4
700,704.0,1.0,6.4,5.4,9.0,15.5,14.5,14.7,17.1,16.2
878,885.0,1.0,15.9,16.2,20.4,21.4,18.3,15.2,14.1,14.5
888,895.0,1.0,7.5,7.3,8.2,7.2,11.7,14.9,24.3,17.8
946,954.0,1.0,5.9,4.4,14.3,9.1,3.5,6.4,4.5,5.2
1054,1063.0,17.0,5.7,4.3,9.4,11.0,6.6,6.4,6.0,12.4
1055,1063.0,141.0,5.5,4.2,8.8,10.6,6.3,6.9,6.7,13.6
1080,1087.0,1.0,4.3,4.1,7.4,5.8,4.7,5.0,6.4,6.0
1144,1152.0,1.0,11.1,12.2,12.9,13.3,18.9,8.5,4.4,4.7
1149,1158.0,1.0,15.1,10.9,16.5,15.9,16.1,15.3,13.6,8.0
1170,1180.0,1.0,13.0,10.0,14.6,5.8,14.9,14.1,20.7,18.0
1185,1195.0,1.0,12.2,12.5,16.0,5.5,8.1,8.7,6.3,7.9
2039,2064.0,1.0,13.2,12.2,12.9,14.3,13.8,10.8,13.3,8.7
2104,2130.0,1.0,14.9,13.0,15.2,14.5,16.6,20.6,15.6,10.8
2164,2191.0,1.0,13.7,12.2,10.6,12.7,14.0,13.2,13.6,7.4
2280,2308.0,1.0,14.9,15.2,11.2,22.1,9.7,21.7,10.8,7.0
5649,5737.0,25.0,11.9,11.3,11.7,11.9,11.4,10.0,11.6,9.2
5695,5782.0,25.0,11.1,10.3,13.6,15.9,10.8,12.4,14.4,12.3
5708,5795.0,25.0,16.2,9.3,16.2,21.7,12.6,12.7,15.1,13.5
5710,5797.0,25.0,16.1,10.4,19.6,17.7,11.4,14.1,19.2,13.2
5759,5839.0,25.0,11.6,12.2,12.5,13.3,11.5,10.7,10.1,10.2
5798,5873.0,25.0,12.9,13.2,12.7,13.9,12.9,13.9,11.7,11.2
5802,5877.0,25.0,12.0,12.1,16.2,14.6,11.8,12.3,12.0,8.8
5819,5894.0,25.0,11.0,11.0,15.4,15.2,14.2,13.8,13.7,12.4
5831,5906.0,25.0,9.2,10.7,19.4,18.8,16.4,16.0,14.7,11.4
5846,5921.0,25.0,9.9,9.7,11.6,11.9,9.8,13.7,11.8,10.5
5855,5930.0,25.0,8.1,5.4,8.0,9.2,10.6,9.7,9.2,7.3
5864,5939.0,25.0,18.5,14.9,18.0,15.8,15.8,14.7,10.9,5.4
5879,5954.0,25.0,10.3,9.2,8.4,8.1,7.4,6.9,6.7,5.5
5924,5997.0,25.0,12.2,13.6,12.4,10.5,10.9,10.5,9.7,7.8
...,...,...,...,...,...,...,...,...,...,...
79499,3880745.0,16.0,8.0,7.4,6.5,15.9,6.2,5.1,5.7,5.2
79500,3880745.0,17.0,9.1,8.3,7.3,17.5,7.0,5.9,5.7,5.2
79501,3880745.0,144.0,8.3,7.5,6.6,15.9,6.2,5.2,5.9,5.2
79513,3881256.0,26.0,9.2,8.5,7.5,17.7,7.0,5.9,6.7,7.9
79540,3884141.0,552.0,7.8,7.0,7.3,7.1,8.6,11.7,8.0,8.7
79573,3893045.0,141.0,10.7,10.2,11.9,13.7,19.8,18.2,14.1,10.9
79586,3896591.0,26.0,8.1,9.6,5.1,6.2,6.4,5.5,8.1,8.5
79596,3899016.0,552.0,17.6,12.8,24.4,19.1,19.0,15.2,15.7,9.3
79597,3899018.0,552.0,12.7,13.4,13.4,16.7,11.8,12.1,19.3,6.9
79622,3901116.0,141.0,8.4,6.7,8.9,6.8,11.1,11.5,10.8,11.2
79625,3903028.0,18.0,9.2,7.5,5.5,8.4,15.1,11.5,15.2,10.8
79626,3903029.0,16.0,9.1,7.3,5.5,8.4,14.9,11.3,15.4,10.7
79627,3903029.0,17.0,8.9,7.1,5.4,8.2,14.6,11.1,15.1,10.4
79628,3903029.0,141.0,9.3,7.5,5.5,8.5,14.9,11.5,15.5,11.0
79632,3903098.0,552.0,15.6,13.5,19.3,16.8,19.3,20.0,15.0,12.1
79672,3916198.0,141.0,15.2,15.1,14.8,13.0,12.8,14.5,12.8,10.6
79818,3948107.0,17.0,9.6,8.4,9.2,10.8,17.1,21.1,11.5,7.8
79820,3948107.0,141.0,9.8,8.6,9.2,10.8,16.9,21.0,11.5,7.9
79821,3948107.0,143.0,9.6,8.6,9.2,10.9,17.1,20.8,11.3,7.8
79823,3948107.0,145.0,9.6,8.6,9.2,10.9,16.9,20.8,11.4,7.8
79830,3949048.0,17.0,18.5,17.7,24.8,22.6,22.1,19.0,16.2,11.3
79834,3950177.0,16.0,15.8,15.3,18.1,16.1,17.1,13.8,12.6,11.8
79835,3950177.0,17.0,15.8,15.2,18.4,15.9,17.0,13.8,12.9,11.8
79836,3950177.0,138.0,15.8,14.7,18.2,16.1,16.8,13.9,12.5,11.8
79837,3950177.0,142.0,15.5,14.5,18.6,15.8,16.8,13.7,12.4,11.8
79838,3950177.0,144.0,15.6,14.5,18.3,15.8,16.8,13.7,12.6,11.8
79852,3954135.0,26.0,1.6,1.3,3.7,3.8,1.4,6.0,12.0,12.2
79883,3960575.0,26.0,11.2,7.9,24.9,9.1,8.4,11.7,11.6,12.0
79889,3962595.0,26.0,8.8,12.5,11.8,11.7,7.8,5.2,11.4,2.7
79910,3964921.0,26.0,4.2,3.3,6.1,9.7,5.3,9.6,6.8,6.6

[return to top of this section](#value),
[return to the top](#top)
<a id="rule4"></a>
### Rule 4. P/B Ratio of 1 or less for TTM

In [138]:
pb_cols = [col for col in df_vals.columns if 'PB_' in col]
pb_cols = [pb_cols[len(pb_cols)-i-1] for i in range(len(pb_cols))][:6]
pb_cols

['PB_TTM', 'PB_2018', 'PB_2017', 'PB_2016', 'PB_2015', 'PB_2014']

In [139]:
df_rule4 = (df_vals[['ticker_id', 'exchange_id'] + pb_cols]
            .where(df_vals['PB_TTM'] <= 1).dropna(axis=0))

In [140]:
df_rule4

,ticker_id,exchange_id,PB_TTM,PB_2018,PB_2017,PB_2016,PB_2015,PB_2014
144,139.0,1.0,0.7,0.6,0.7,0.2,0.6,0.8
148,143.0,1.0,0.1,0.1,0.3,0.6,0.2,0.5
308,302.0,1.0,0.9,1.0,3.6,-14.1,0.9,0.1
340,335.0,1.0,0.8,0.6,1.8,0.3,0.2,0.8
366,361.0,1.0,0.5,0.5,1.2,0.9,2.1,8.5
400,396.0,1.0,0.6,0.6,1.4,2.8,5.1,4.5
513,511.0,1.0,1.0,0.9,1.9,2.1,1.0,1.0
601,602.0,1.0,0.3,0.4,0.9,2.4,0.2,0.2
672,675.0,1.0,0.8,0.6,1.5,2.1,1.7,3.1
686,689.0,1.0,0.2,0.1,0.8,0.9,0.7,1.0
688,691.0,1.0,0.3,0.3,0.7,0.9,1.4,1.1
700,704.0,1.0,0.7,0.6,0.9,0.7,0.9,1.0
707,711.0,1.0,0.8,0.9,1.0,1.2,1.7,1.0
738,742.0,1.0,0.0,0.0,0.0,0.2,0.4,1.7
754,758.0,1.0,0.3,0.2,0.2,0.4,0.2,0.4
761,765.0,1.0,0.9,0.6,1.2,1.9,0.1,0.5
766,770.0,1.0,0.4,0.3,0.5,0.6,0.1,0.0
771,775.0,1.0,1.0,0.8,1.6,0.7,0.4,0.7
782,786.0,1.0,0.9,0.7,0.9,0.7,0.9,0.8
786,790.0,1.0,0.3,0.4,6.2,-113.6,6.5,0.4
818,824.0,1.0,0.1,0.0,0.0,0.5,0.3,0.0
829,835.0,1.0,0.3,0.3,0.3,0.3,0.3,0.5
861,868.0,1.0,0.6,0.4,0.7,0.5,0.2,0.6
865,872.0,1.0,0.4,0.5,0.6,1.2,0.6,0.6
885,892.0,1.0,0.0,0.0,0.0,0.0,0.1,0.1
887,894.0,1.0,0.9,0.8,2.9,1.7,2.0,2.2
888,895.0,1.0,0.8,0.8,0.9,0.7,1.0,1.4
903,910.0,1.0,0.3,0.3,0.4,0.4,0.3,0.4
908,915.0,1.0,0.1,0.1,1.0,120.5,0.0,0.0
938,945.0,1.0,0.9,0.6,0.6,0.8,0.5,0.5
...,...,...,...,...,...,...,...,...
79898,3963372.0,17.0,0.9,0.9,1.4,1.3,1.2,2.0
79899,3963464.0,17.0,0.0,0.0,0.5,0.6,0.6,0.5
79908,3964915.0,26.0,0.6,0.6,1.3,0.6,0.5,0.5
79910,3964921.0,26.0,0.7,0.6,1.1,0.6,0.5,0.5
79911,3964925.0,26.0,0.9,0.4,1.0,1.1,2.7,10.8
79914,3964932.0,26.0,0.5,1.5,2.2,2.6,6.1,10.5
79928,3966803.0,26.0,0.6,0.4,1.1,2.3,4.2,2.6
79934,7938.0,25.0,0.0,0.3,1.2,0.7,1.2,3.5
79938,7250.0,25.0,0.8,0.5,0.8,1.0,0.5,0.8
79946,17740.0,25.0,0.6,0.8,0.9,0.7,0.7,1.5
80003,560123.0,575.0,0.9,0.9,0.8,0.8,20.7,2.2
80086,2219032.0,17.0,0.8,0.7,0.8,0.9,1.0,1.0
80091,3368562.0,17.0,0.0,0.2,0.2,0.2,0.3,0.5
80116,4010794.0,44.0,1.0,0.7,2.3,1.3,2.4,2.3
80162,4022827.0,25.0,0.0,0.4,0.8,2.1,3.0,2.7
80163,4023410.0,25.0,0.0,0.1,1.1,2.0,2.4,2.5
80164,4023419.0,25.0,0.1,0.1,0.3,0.5,0.4,0.9
80168,4025654.0,25.0,0.0,0.1,0.3,0.5,0.4,1.0
80176,4028966.0,25.0,0.0,0.0,0.3,0.4,0.1,0.5
80177,4029204.0,25.0,0.6,0.5,0.8,0.9,0.7,1.0
80180,4030918.0,25.0,0.3,0.2,-9.5,0.0,-0.1,555.6
80194,4034514.0,44.0,0.7,0.7,0.7,0.7,0.6,1.0
80297,4387320.0,16.0,0.2,0.3,0.4,0.4,0.6,0.9
80345,4516379.0,16.0,1.0,0.3,1.1,1.0,1.1,1.1
80347,4516379.0,141.0,1.0,0.7,1.1,1.0,1.1,1.1
80359,4586917.0,16.0,0.8,0.0,2.1,3.4,3.9,9.3
80360,4586917.0,17.0,0.8,0.4,2.2,3.4,4.0,8.9
80363,4588766.0,16.0,0.3,0.2,0.5,0.4,4.1,-120.5
80372,4737566.0,26.0,0.4,0.3,0.3,0.6,0.1,0.6
80477,6778021.0,141.0,0.5,9.5,5.6,9.9,-8.2,0.6

[return to top of this section](#value),
[return to the top](#top)
<a id="rule5"></a>
### Rule 5. Filtering for *bargain issues* as described by Benjamin Graham in *The Intelligent Investor*:

In his book, Graham defines bargain issues as common stocks where:

- $stock\ price\ < \frac{2}{3}\ net\ current\ asset\ value\ per\ share\ (NCAVPS)\$

- $net\ current\ asset\ value\ (NCAV)\ = current\ assets\ - total\ liabilities\ - preferred\ stocks\$

In [141]:
# df_master columns
cols1 = ['ticker_id', 'exchange_id', 'country_c3', 'exchange_sym', 'ticker', 'company',
       'industry', 'sector', 'security_type', 'lastprice']

# df_quarterlyBS columns
cols2 = ['ticker_id', 'exchange_id', 'Year_Y_5', 
         'label_i81', 'data_i81_Y_5', # Preferred stock
         #'label_g1', 'data_g1_Y_5', # Assets / Current assets
         'label_s1', 'data_s1_Y_5', # Assets /
         #'label_ttg1', 'data_ttg1_Y_5', # Total assets / Total current assets
         #'label_tts1', 'data_tts1_Y_5', # Total assets
         #'label_gg5', 'data_gg5_Y_5', # Current liabilities
         #'label_ttgg5', 'data_ttgg5_Y_5', # Total current liabilit...
         'label_g5', 'data_g5_Y_5', # Liabilities
         #'label_ttg5', 'data_ttg5_Y_5' # Total liabilities
         'currency_id'
        ]

# df_finhealth columns
cols3 = ['ticker_id', 'exchange_id', 
        #'i53_fh_Y5', # Total Assets
        'i49_fh_Y10'#,  Total Current Assets
        #'i62_fh_Y5', # Total Assets
        #'i59_fh_Y5' # Total Current Liabilities
       ]

# df_quarterlyIS columns
cols4 = ['ticker_id', 'exchange_id', 
         'data_i85_Y_5' # Basic Outstanding Shares
        ]


df_bs0 = (df_master[cols1]
          .where(df_master['security_type'] == 'Stock')
          .merge(df_quarterlyBS[cols2], on=['ticker_id', 'exchange_id'])
          .merge(df_finhealth[cols3], on=['ticker_id', 'exchange_id'])
          .merge(df_quarterlyIS[cols4], on=['ticker_id', 'exchange_id'])
          #.rename(columns={'data_g1_Y_5':'current_assets'})
        )

# Map Column Headers
for col in [col for col in df_bs0.columns if 'label_' in col]:
    df_bs0[col] = df_bs0[col].map(df.colheaders['header'])
    
# Map Currency Name
df_bs0['currency'] = df_bs0['currency_id'].map(df.currencies.set_index('id')['currency'])

In [142]:
df_bs = (df_bs0.where((df_bs0['label_i81'] == 'Preferred stock') & 
                     ((df_bs0['label_s1'] == 'Assets') & (df_bs0['data_s1_Y_5'].notna())) & 
                     ((df_bs0['label_g5'] == 'Liabilities') & (df_bs0['data_g5_Y_5'].notna()))
                    ).dropna(axis=0, how='all'))

In [143]:
df_bs['current_assets'] = df_bs['data_s1_Y_5'] * df_bs['i49_fh_Y10'] / 100

df_bs['data_i81_Y_5'] = df_bs['data_i81_Y_5'].fillna(0)

df_bs['NCAV'] = df_bs['current_assets'] - df_bs['data_g5_Y_5'] - df_bs['data_i81_Y_5']

df_bs['NCAVPS'] = df_bs['NCAV'] / df_bs['data_i85_Y_5']

In [144]:
df_bs[df_bs['NCAV'] > 0]

,ticker_id,exchange_id,country_c3,exchange_sym,ticker,company,industry,sector,security_type,lastprice,...,data_s1_Y_5,label_g5,data_g5_Y_5,currency_id,i49_fh_Y10,data_i85_Y_5,currency,current_assets,NCAV,NCAVPS
16,19367.0,302.0,USA,XNYS,NOV,National Oilwell Varco Inc,Oil & Gas Equipment & Services,Energy,Stock,28.32,...,1.979600e+10,Liabilities,5.977000e+09,104.0,36.77,3.780000e+08,United States Dollar,7.278989e+09,1.301989e+09,3.444416
36,1226.0,1.0,USA,GREY,BSMAF,Bursa Malaysia Bhd,Financial Exchanges,Financial Services,Stock,1.84,...,2.434560e+09,Liabilities,1.559402e+09,62.0,74.91,8.074820e+08,Malaysia Ringgit,1.823729e+09,2.643269e+08,0.327347
45,10933.0,25.0,USA,PINX,PCDVF,Pacific Century Regional Developments Ltd,Asset Management,Financial Services,Stock,0.31,...,1.424342e+09,Liabilities,1.900800e+07,88.0,2.04,2.649740e+09,Singapore Dollar,2.905658e+07,1.004858e+07,0.003792
62,13351.0,25.0,USA,PINX,FUPBY,Fuchs Petrolub SE ADR,Chemicals,Basic Materials,Stock,10.55,...,1.891000e+09,Liabilities,4.360000e+08,34.0,53.83,5.501146e+08,Euro Member Countries,1.017925e+09,5.819253e+08,1.057825
63,8275.0,25.0,USA,PINX,FUPEF,Fuchs Petrolub SE,Chemicals,Basic Materials,Stock,44.20,...,1.891000e+09,Liabilities,4.360000e+08,34.0,53.83,1.375287e+08,Euro Member Countries,1.017925e+09,5.819253e+08,4.231302
64,10782.0,25.0,USA,PINX,KURRF,Kuraray Co Ltd,Chemicals,Basic Materials,Stock,12.60,...,9.471100e+11,Liabilities,3.910900e+11,52.0,42.10,3.486830e+08,Japan Yen,3.987333e+11,7.643310e+09,21.920512
65,12178.0,25.0,USA,PINX,KURRY,Kuraray Co Ltd ADR,Chemicals,Basic Materials,Stock,40.23,...,9.471100e+11,Liabilities,3.910900e+11,52.0,42.10,1.162277e+08,Japan Yen,3.987333e+11,7.643310e+09,65.761537
67,16781.0,44.0,USA,XNAS,PAAS,Pan American Silver Corp,Silver,Basic Materials,Stock,13.43,...,1.937476e+09,Liabilities,4.292640e+08,104.0,28.30,1.533540e+08,United States Dollar,5.483057e+08,1.190417e+08,0.776254
75,709.0,1.0,USA,GREY,GDMOF,DMG Mori Aktiengesellschaft,Tools & Accessories,Industrials,Stock,54.45,...,2.440499e+09,Liabilities,1.247264e+09,34.0,68.94,7.881799e+07,Euro Member Countries,1.682480e+09,4.352160e+08,5.521785
79,2541259.0,25.0,USA,PINX,SAABY,Saab AB ADR,Aerospace & Defense,Industrials,Stock,17.00,...,5.612800e+10,Liabilities,3.671600e+10,93.0,69.46,2.378995e+08,Sweden Krona,3.898651e+10,2.270509e+09,9.543983
81,10678.0,25.0,USA,PINX,WRTBF,Wartsila Corp,Diversified Industrials,Industrials,Stock,15.43,...,6.059000e+09,Liabilities,3.641000e+09,34.0,60.90,6.080000e+08,Euro Member Countries,3.689931e+09,4.893100e+07,0.080479
82,12659.0,25.0,USA,PINX,WRTBY,Wartsila Corp ADR,Diversified Industrials,Industrials,Stock,3.63,...,6.059000e+09,Liabilities,3.641000e+09,34.0,60.90,3.040000e+09,Euro Member Countries,3.689931e+09,4.893100e+07,0.016096
88,8474.0,25.0,USA,PINX,FINGF,Finning International Inc,Industrial Distribution,Industrials,Stock,18.21,...,5.696000e+09,Liabilities,3.587000e+09,19.0,68.89,1.670488e+08,Canada Dollar,3.923974e+09,3.369744e+08,2.017222
90,2148.0,1.0,USA,GREY,SFZGF,Shanghai Fudan-Zhangjiang Bio-Pharmaceutical C...,Drug Manufacturers - Major,Healthcare,Stock,0.47,...,1.459363e+09,Liabilities,4.772920e+08,22.0,69.90,9.158421e+08,China Yuan Renminbi,1.020095e+09,5.428027e+08,0.592682
93,8175.0,25.0,USA,PINX,HLUYY,H. Lundbeck A/S ADR,Drug Manufacturers - Specialty & Generic,Healthcare,Stock,44.40,...,2.301100e+10,Liabilities,8.760000e+09,29.0,50.62,1.986000e+08,Denmark Krone,1.164817e+10,2.888168e+09,14.542639
94,10947.0,25.0,USA,PINX,HLUKF,H. Lundbeck A/S,Drug Manufacturers - Specialty & Generic,Healthcare,Stock,44.10,...,2.301100e+10,Liabilities,8.760000e+09,29.0,50.62,1.986000e+08,Denmark Krone,1.164817e+10,2.888168e+09,14.542639
95,15203.0,25.0,USA,PINX,LVZPF,Livzon Pharmaceutical Group Inc Class H,Drug Manufacturers - Specialty & Generic,Healthcare,Stock,2.92,...,1.743735e+10,Liabilities,6.785369e+09,22.0,71.52,7.137770e+08,China Yuan Renminbi,1.247119e+10,5.685821e+09,7.965823
106,3835.0,1.0,USA,GREY,SRDDF,Alpargatas SA Pfd Shs,Footwear & Accessories,Consumer Cyclical,Stock,4.29,...,3.980105e+09,Liabilities,1.599292e+09,16.0,60.03,5.788167e+08,Brazil Real,2.389257e+09,7.899650e+08,1.364793
107,9238.0,25.0,USA,PINX,NKRKF,Nokian Tyres PLC,Rubber & Plastics,Consumer Cyclical,Stock,34.59,...,2.092800e+09,Liabilities,6.068000e+08,34.0,62.64,1.377700e+08,Euro Member Countries,1.310930e+09,7.041299e+08,5.110909
108,13290.0,25.0,USA,PINX,NKRKY,Nokian Tyres PLC ADR,Rubber & Plastics,Consumer Cyclical,Stock,18.00,...,2.092800e+09,Liabilities,6.068000e+08,34.0,62.64,2.755400e+08,Euro Member Countries,1.310930e+09,7.041299e+08,2.555454
113,13263.0,25.0,USA,PINX,AGTEF,AGTech Holdings Ltd,Software - Application,Technology,Stock,0.07,...,3.721541e+09,Liabilities,7.375590e+08,43.0,67.35,1.081340e+10,Hong Kong Dollar,2.506458e+09,1.768899e+09,0.163584
114,10795.0,25.0,USA,PINX,NPEGF,Nippon Electric Glass Co Ltd,Electronic Components,Technology,Stock,27.20,...,7.255720e+11,Liabilities,2.091230e+11,52.0,34.85,9.680059e+07,Japan Yen,2.528618e+11,4.373884e+10,451.844778
115,3080.0,1.0,USA,GREY,GUNGF,GungHo Online Entertainment Inc,Electronic Gaming & Multimedia,Technology,Stock,2.03,...,9.603000e+10,Liabilities,2.144400e+10,52.0,92.03,7.114875e+08,Japan Yen,8.837641e+10,6.693241e+10,94.073907
116,14265.0,25.0,USA,PINX,IGGGF,IGG Inc,Electronic Gaming & Multimedia,Technology,Stock,1.38,...,3.994130e+08,Liabilities,1.168100e+08,104.0,84.61,1.386584e+09,United States Dollar,3.379433e+08,2.211333e+08,0.159481
122,4603.0,1.0,USA,GREY,THPFF,Thai President Foods PCL DR,Packaged Foods,Consumer Defensive,Stock,4.67,...,3.084157e+10,Liabilities,9.941772e+09,98.0,43.43,3.297041e+08,Thailand Baht,1.339450e+10,3.452723e+09,10.472190
124,9376.0,25.0,USA,PINX,MNHVF,Mowi ASA,Farm Products,Consumer Defensive,Stock,22.30,...,5.145100e+09,Liabilities,2.267900e+09,34.0,50.28,5.113831e+08,Euro Member Countries,2.586956e+09,3.190563e+08,0.623908
125,12727.0,25.0,USA,PINX,MHGVY,Mowi ASA ADR,Farm Products,Consumer Defensive,Stock,22.38,...,5.145100e+09,Liabilities,2.267900e+09,34.0,50.28,5.113831e+08,Euro Member Countries,2.586956e+09,3.190563e+08,0.623908
138,251163.0,18.0,GBR,XLON,MMK,Magnitogorsk Iron & Steel Works PJSC GDR,Steel,Basic Materials,Stock,8.97,...,7.205000e+09,Liabilities,2.217000e+09,104.0,38.03,8.595638e+08,United States Dollar,2.740062e+09,5.230615e+08,0.608520
143,16476.0,44.0,USA,XNAS,IMMU,Immunomedics Inc,Biotechnology,Healthcare,Stock,18.29,...,6.126620e+08,Liabilities,2.689090e+08,104.0,96.96,1.869370e+08,United States Dollar,5.940371e+08,3.251281e+08,1.739239
162,18646.0,302.0,USA,XNYS,AOS,A.O. Smith Corp,Diversified Industrials,Industrials,Stock,55.22,...,3.071500e+09,Liabilities,1.354500e+09,104.0,53.35,1.692651e+08,United States Dollar,1.638645e+09,2.841452e+08,1.678699
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50566,17434.0,44.0,USA,XNAS,CCNI,Command Center Inc,Staffing & Outsourcing Services,Industrials,Stock,3.92,...,2.272836e+07,Liabilities,4.845670e+06,104.0,74.00,4.808698e+06,United States Dollar,1.681899e+07,1.197332e+07,2.489930
50571,16991.0,44.0,USA,XNAS,STRT,Strattec Security Corp,Auto Parts,Consumer Cyclical,Stock,30.50,...,2.988380e+08,Liabilities,1.368700e+08,104.0,48.96,3.675000e+06,United States Dollar,1.463111e+08,9.441085e+06,2.569003
50572,16223.0,44.0,USA,XNAS,CRWS,Crown Crafts Inc,Apparel Manufacturing,Consumer Cyclical,Stock,5.12,...,5.495400e+07,Liabilities,1.424400e+07,104.0,70.61,1.009800e+07,United States Dollar,3.880302e+07,2.455902e+07,2.432068
50575,16675.0,44.0,USA,XNAS,FIZZ,National Beverage Corp,Beverages - Soft Drinks,Consumer Defensive,Stock,57.91,...,5.526730e+08,Liabilities,2.471790e+08,104.0,77.77,4.663800e+07,United States Dollar,4.298138e+08,1.824848e+08,3.912792
50576,19267.0,16.0,DEU,XFRA,LAZ,La-Z-Boy Inc,Home Furnishings & Fixtures,Consumer Cyclical,Stock,29.19,...,1.061456e+09,Liabilities,4.041930e+08,104.0,51.57,4.682000e+07,United States Dollar,5.473929e+08,1.431999e+08,3.058519
50577,19267.0,144.0,DEU,XSTU,LAZ,La-Z-Boy Inc,Home Furnishings & Fixtures,Consumer Cyclical,Stock,29.36,...,1.061456e+09,Liabilities,4.041930e+08,104.0,51.57,4.682000e+07,United States Dollar,5.473929e+08,1.431999e+08,3.058519
50578,38371.0,16.0,DEU,XFRA,20V,National Beverage Corp,Beverages - Soft Drinks,Consumer Defensive,Stock,50.93,...,5.526730e+08,Liabilities,2.471790e+08,104.0,77.77,4.663800e+07,United States Dollar,4.298138e+08,1.824848e+08,3.912792
50579,38371.0,141.0,DEU,XMUN,20V,National Beverage Corp,Beverages - Soft Drinks,Consumer Defensive,Stock,51.16,...,5.526730e+08,Liabilities,2.471790e+08,104.0,77.77,4.663800e+07,United States Dollar,4.298138e+08,1.824848e+08,3.912792
50580,38371.0,144.0,DEU,XSTU,20V,National Beverage Corp,Beverages - Soft Drinks,Consumer Defensive,Stock,50.17,...,5.526730e+08,Liabilities,2.471790e+08,104.0,77.77,4.663800e+07,United States Dollar,4.298138e+08,1.824848e+08,3.912792
50581,150900.0,16.0,DEU,XFRA,2BN,Barnes & Noble Education Inc,Specialty Retail,Consumer Cyclical,Stock,4.28,...,1.316056e+09,Liabilities,8.213690e+08,104.0,68.69,4.756100e+07,United States Dollar,9.039989e+08,8.262987e+07,1.737345
50582,150900.0,141.0,DEU,XMUN,2BN,Barnes & Noble Education Inc,Specialty Retail,Consumer Cyclical,Stock,4.15,...,1.316056e+09,Liabilities,8.213690e+08,104.0,68.69,4.756100e+07,United States Dollar,9.039989e+08,8.262987e+07,1.737345
50590,16932.0,44.0,USA,XNAS,SMTC,Semtech Corp,Semiconductors,Technology,Stock,52.57,...,1.062881e+09,Liabilities,3.802000e+08,104.0,45.66,6.552600e+07,United States Dollar,4.853115e+08,1.051115e+08,1.604118
50610,18490.0,44.0,USA,XNAS,APTX,Aptinyx Inc,Biotechnology,Healthcare,Stock,4.11,...,1.556140e+08,Liabilities,6.303000e+06,104.0,98.48,3.334100e+07,United States Dollar,1.532487e+08,1.469457e+08,4.407356
50617,114161.0,17.0,DEU,XBER,HQ1N,ARCA biopharma Inc,Biotechnology,Healthcare,Stock,4.80,...,6.825000e+06,Liabilities,7.930000e+05,104.0,99.30,7.736100e+05,United States Dollar,6.777225e+06,5.984225e+06,7.735455
50618,114161.0,141.0,DEU,XMUN,HQ1N,ARCA biopharma Inc,Biotechnology,Healthcare,Stock,4.86,...,6.825000e+06,Liabilities,7.930000e+05,104.0,99.30,7.736100e+05,United States Dollar,6.777225e+06,5.984225e+06,7.735455
50619,114161.0,144.0,DEU,XSTU,HQ1N,ARCA biopharma Inc,Biotechnology,Healthcare,Stock,0.28,...,6.825000e+06,Liabilities,7.930000e+05,104.0,99.30,7.736100e+05,United States Dollar,6.777225e+06,5.984225e+06,7.735455
50620,18452.0,16.0,DEU,XFRA,MOR,MorphoSys AG,Biotechnology,Healthcare,Stock,88.15,...,5.387638e+08,Liabilities,5.039112e+07,34.0,72.18,3.155716e+07,Euro Member Countries,3.888797e+08,3.384886e+08,10.726206
50621,18452.0,17.0,DEU,XBER,MOR,MorphoSys AG,Biotechnology,Healthcare,Stock,90.35,...,5.387638e+08,Liabilities,5.039112e+07,34.0,72.18,3.155716e+07,Euro Member Countries,3.888797e+08,3.384886e+08,10.726206
50622,18452.0,141.0,DEU,XMUN,MOR,MorphoSys AG,Biotechnology,Healthcare,Stock,90.35,...,5.387638e+08,Liabilities,5.039112e+07,34.0,72.18,3.155716e+07,Euro Member Countries,3.888797e+08,3.384886e+08,10.726206
50623,18452.0,144.0,DEU,XSTU,MOR,MorphoSys AG,Biotechnology,Healthcare,Stock,88.15,...,5.387638e+08,Liabilities,5.039112e+07,34.0,72.18,3.155716e+07,Euro Member Countries,3.888797e+08,3.384886e+08,10.726206
50624,18452.0,142.0,DEU,XDUS,MOR,MorphoSys AG,Biotechnology,Healthcare,Stock,88.80,...,5.387638e+08,Liabilities,5.039112e+07,34.0,72.18,3.155716e+07,Euro Member Countries,3.888797e+08,3.384886e+08,10.726206
50625,18452.0,145.0,DEU,XHAM,MOR,MorphoSys AG,Biotechnology,Healthcare,Stock,90.35,...,5.387638e+08,Liabilities,5.039112e+07,34.0,72.18,3.155716e+07,Euro Member Countries,3.888797e+08,3.384886e+08,10.726206
50626,18452.0,143.0,DEU,XHAN,MOR,MorphoSys AG,Biotechnology,Healthcare,Stock,90.65,...,5.387638e+08,Liabilities,5.039112e+07,34.0,72.18,3.155716e+07,Euro Member Countries,3.888797e+08,3.384886e+08,10.726206
50627,794216.0,16.0,DEU,XFRA,HI8H,HiQ International AB,Information Technology Services,Technology,Stock,5.56,...,1.185755e+09,Liabilities,3.673040e+08,93.0,60.24,5.581100e+07,Sweden Krona,7.142988e+08,3.469948e+08,6.217319
50628,33605.0,669.0,CAN,XTSX,GFL.H,Gulfstream Acquisition 1 Corp,Conglomerates,Industrials,Stock,0.11,...,3.817920e+05,Liabilities,3.240000e+03,19.0,100.00,8.055159e+06,Canada Dollar,3.817920e+05,3.785520e+05,0.046995
50629,26301.0,669.0,CAN,XTSX,SGW,Shoal Games Ltd,Electronic Gaming & Multimedia,Technology,Stock,0.50,...,7.696330e+05,Liabilities,9.080500e+04,104.0,97.89,7.369188e+07,United States Dollar,7.533937e+05,6.625887e+05,0.008991
50631,6816.0,25.0,USA,PINX,EQUR,E-Qure Corp,Medical Devices,Healthcare,Stock,0.08,...,5.568900e+05,Liabilities,2.711850e+05,104.0,96.65,2.491195e+07,United States Dollar,5.382342e+05,2.670492e+05,0.010720
50635,1701240.0,1.0,USA,GREY,ECMXD,Universal Copper Ltd,Industrial Metals & Minerals,Basic Materials,Stock,0.07,...,2.809435e+06,Liabilities,1.521800e+04,19.0,26.15,1.991272e+07,Canada Dollar,7.346673e+05,7.194493e+05,0.036130
50636,1075551.0,16.0,DEU,XFRA,CKC1,Volcanic Gold Mines Inc,Industrial Metals & Minerals,Basic Materials,Stock,0.02,...,2.913420e+05,Liabilities,1.666750e+05,19.0,73.65,4.588654e+07,Canada Dollar,2.145734e+05,4.789838e+04,0.001044
50652,7075.0,25.0,USA,PINX,CYIO,CYIOS Corp,Aerospace & Defense,Industrials,Stock,0.01,...,3.808250e+05,Liabilities,6.961500e+04,104.0,42.42,3.631164e+07,United States Dollar,1.615460e+05,9.190096e+04,0.002531

[return to top of this section](#value),
[return to the top](#top)
<a id="rule6"></a>
### Rule 6. Operating Cash Flow growth for the past 7 yrs

[return to top of this section](#value),
[return to the top](#top)
<a id="rule7"></a>
### Rule 7. *Owner earnings* growth rate > 6% over past 7 years

$owner\ earning's = net\ income + amortization\ and\ depreciation\ - normal\ capital\ expenditures$

Benjamin Graham mentions in *Intelligent Investor* that, because it adjusts for entries like amortization and depreciation that do not affect the company's cash balances, *owner earnings* is a better measure to reported net income.

[return to top of this section](#value),
[return to the top](#top)
<a id="rule8"></a>
### Rule 8. Long-term debt < 50% of total capital

[return to top of this section](#value),
[return to the top](#top)
<a id="rule9"></a>
### Rule 9. NAV per share > Stock Price

The definition of NAV as described by Graham in the Intelligent Investor

$net\ asset\ value\ (NAV)\ = total\ assets\ - intangible\ assets\ (patents,\ goodwill)\ - total\ liabilities\$

[return to top of this section](#value),
[return to the top](#top)
<a id="rule10"></a>
### Rule 10. Growth Stocks as defined in *The Intelligent Investor*

*'The term “growth stock” is applied to one which has increased its per-share earnings in the past at well above the rate for common stocks generally and is expected to continue to do so in the future. (Some authorities would say that a true growth stock should be expected at least to double its per-share earnings in ten years—i.e., to increase them at a __compounded annual rate of over 7.1%__.)'* - Benjamin Graham, *The Intelligent Investor*

$$Compounded\ Annual\ Growth\ Rate\ (CAGR)\ = \left(\frac{EV}{BV}\right)^{\frac{1}{n}}-1 > 7.1\%$$

$$EV = Ending\ value\$$

$$BV = Beginning\ value\$$

$$n = Number\ of\ periods\ (months,\ years,\ etc.)\$$

[return to top of this section](#value),
[return to the top](#top)
<a id="rule11"></a>
### Rule 11. Positive ratio of earnings to fixed charges

[return to top of this section](#value),
[return to the top](#top)
<a id="rule12"></a>
### Rule 12. CAN SLIM

CAN SLIM refers to the acronym developed by the American stock research and education company Investor's Business Daily (IBD). IBD claims CANSLIM represents the seven characteristics that top-performing stocks often share before making their biggest price gains. It was developed in the 1950s by Investor's Business Daily founder William O'Neil. The method was named the top-performing investment strategy from 1998-2009 by the American Association of Individual Investors. In 2015, an exchange-traded fund (ETF) was launched focusing on the companies listed on the IBD 50, a computer generated list published by Investors Business Daily that highlights stocks based on the CAN SLIM investment criteria. [(Source)](https://en.m.wikipedia.org/wiki/CAN_SLIM?wprov=sfla1)

[return to top of this section](#value),
[return to the top](#top)
<a id="rule13"></a>
### Rule 13.

In [39]:
df_growth_cols

gr_revenue               Revenue %
i28                 Year over Year
i29                 3-Year Average
i30                 5-Year Average
i31                10-Year Average
gr_operating    Operating Income %
i32                 Year over Year
i33                 3-Year Average
i34                 5-Year Average
i35                10-Year Average
gr_ni                 Net Income %
i81                 Year over Year
i82                 3-Year Average
i83                 5-Year Average
i84                10-Year Average
gr_eps                       EPS %
i36                 Year over Year
i37                 3-Year Average
i38                 5-Year Average
i39                10-Year Average
Name: 0, dtype: object

In [54]:
cols = ['ticker_id', 'exchange_id'] + [col for col in df_growth 
                                       if col.startswith('i28_') or col.startswith('gr_Y')]

(df_growth[cols]
 .where((df_growth['gr_Y9'] > pd.to_datetime('2018-01-01')) & 
        (df_growth['i28_gr_Y10'] > 0.0) & (df_growth['i28_gr_Y9'] > 0.0) &
        (df_growth['i28_gr_Y8'] > 0.0) & (df_growth['i28_gr_Y7'] > 0.0) & (df_growth['i28_gr_Y6'] > 0.0)
       )
 .dropna(axis=0, how='all')
)

,ticker_id,exchange_id,i28_gr_Y0,i28_gr_Y1,i28_gr_Y2,i28_gr_Y3,i28_gr_Y4,i28_gr_Y5,i28_gr_Y6,i28_gr_Y7,...,gr_Y1,gr_Y2,gr_Y3,gr_Y4,gr_Y5,gr_Y6,gr_Y7,gr_Y8,gr_Y9,gr_Y10
0,1.0,374.0,NaN,NaN,NaN,-11.70,19.81,103.73,3.51,3.10,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,Latest Qtr
1,2.0,374.0,NaN,NaN,NaN,-11.70,19.81,103.73,3.51,3.10,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,Latest Qtr
2,3.0,374.0,NaN,NaN,NaN,-11.70,19.81,103.73,3.51,3.10,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,Latest Qtr
3,4.0,482.0,2.23,2.59,16.25,0.83,11.65,7.90,2.81,3.53,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,Latest Qtr
25,506.0,1.0,6.83,36.47,14.10,12.08,35.21,28.79,24.80,17.89,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,Latest Qtr
27,568.0,1.0,26.87,9.52,-0.15,10.17,9.30,7.92,17.10,17.09,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,Latest Qtr
28,615.0,1.0,-4.54,-41.80,33.62,6.32,-5.73,4.71,2.62,24.94,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,Latest Qtr
30,618.0,1.0,-16.75,-12.27,83.95,54.87,50.96,6.04,40.07,46.81,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,Latest Qtr
43,703.0,1.0,2.43,7.77,16.85,2.32,-2.12,7.52,16.06,9.59,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,Latest Qtr
56,796.0,1.0,32.72,33.27,27.12,0.10,2.65,9.42,0.33,20.15,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,Latest Qtr
63,820.0,1.0,-13.62,1.09,13.48,7.68,2.61,-1.68,13.29,2.41,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,Latest Qtr
71,862.0,1.0,19.02,1.47,-10.27,30.04,20.00,6.57,6.45,18.37,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,Latest Qtr
73,865.0,1.0,71.69,9.41,9.36,7.68,18.04,17.82,11.46,6.44,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,Latest Qtr
76,869.0,1.0,-0.01,-2.45,9258.02,-96.98,4.01,11.77,10.83,7.26,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,Latest Qtr
82,896.0,1.0,6.62,14.36,23.81,21.23,25.51,15.40,12.34,4.85,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,Latest Qtr
87,905.0,1.0,2.29,8.83,-0.12,8.06,-3.95,10.29,24.50,9.40,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,Latest Qtr
94,938.0,1.0,-8.76,18.06,39.30,5.26,4.20,12.82,17.89,12.94,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,Latest Qtr
103,1004.0,1.0,50.09,1.16,-1.71,8.05,4.80,4.42,6.72,9.37,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,Latest Qtr
108,1035.0,1.0,18.79,29.00,10.89,-2.47,-0.30,3.04,6.03,11.39,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,Latest Qtr
124,1089.0,1.0,-19.22,23.91,11.15,11.62,5.56,20.75,33.17,3.12,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,Latest Qtr
128,1108.0,1.0,-10.53,14.39,17.72,11.59,6.85,8.58,1.33,2.32,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,Latest Qtr
130,1117.0,1.0,-33.60,-1.81,13.07,-23.73,1.36,-37.69,26.32,15.72,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,Latest Qtr
141,1158.0,1.0,-22.14,30.19,16.67,10.69,12.78,15.15,14.97,9.93,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,Latest Qtr
145,1179.0,1.0,-25.89,26.08,10.13,-0.04,-5.03,2.55,10.05,3.17,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,Latest Qtr
151,1196.0,1.0,-15.72,3.73,0.78,4.04,-11.82,5.84,5.01,10.28,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,Latest Qtr
152,1202.0,1.0,-25.51,3.53,16.37,33.07,21.28,22.76,25.43,38.09,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,Latest Qtr
160,1229.0,1.0,-13.66,-2.47,16.12,16.29,-5.61,1.98,10.85,0.06,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,Latest Qtr
163,1243.0,1.0,-25.27,-3.97,15.99,16.40,13.05,6.44,4.86,0.05,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,Latest Qtr
167,1256.0,1.0,2.45,3.32,7.31,1.94,5.20,5.68,5.90,5.07,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,Latest Qtr
168,1331.0,1.0,1.36,5.79,5.16,3.45,-1.71,-13.12,4.40,3.53,...,2010-12-01,2011-12-01,2012-12-01,2013-12-01,2014-12-01,2015-12-01,2016-12-01,2017-12-01,2018-12-01,Latest Qtr
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73403,19252.0,302.0,-19.09,-11.31,29.45,6.51,2.77,17.17,7.08,26.33,...,2010-04-01,2011-04-01,2012-04-01,2013-04-01,2014-04-01,2015-04-01,2016-04-01,2017-04-01,2018-04-01,Latest Qtr
73416,20254.0,649.0,4.76,-10.35,-3.04,10.79,10.78,6.40,23.04,17.77,...,2010-04-01,2011-04-01,2012-04-01,2013-04-01,2014-04-01,2015-04-01,2016-04-01,2017-04-01,2018-04-01,Latest Qtr
73438,38149.0,16.0,8.02,8.34,0.73,1.58,2.51,2.50,19.15,42.31,...,2010-04-01,2011-04-01,2012-04-01,2013-04-01,2014-04-01,2015-04-01,2016-04-01,2017-04-01,2018-04-01,Latest Qtr
73439,38149.0,17.0,8.02,8.34,0.73,1.58,2.51,2.50,19.15,42.31,...,2010-04-01,2011-04-01,2012-04-01,2013-04-01,2014-04-01,2015-04-01,2016-04-01,2017-04-01,2018-04-01,Latest Qtr
73440,38149.0,138.0,8.02,8.34,0.73,1.58,2.51,2.50,19.15,42.31,...,2010-04-01,2011-04-01,2012-04-01,2013-04-01,2014-04-01,2015-04-01,2016-04-01,2017-04-01,2018-04-01,Latest Qtr
73441,38149.0,141.0,8.02,8.34,0.73,1.58,2.51,2.50,19.15,42.31,...,2010-04-01,2011-04-01,2012-04-01,2013-04-01,2014-04-01,2015-04-01,2016-04-01,2017-04-01,2018-04-01,Latest Qtr
73442,38149.0,142.0,8.02,8.34,0.73,1.58,2.51,2.50,19.15,42.31,...,2010-04-01,2011-04-01,2012-04-01,2013-04-01,2014-04-01,2015-04-01,2016-04-01,2017-04-01,2018-04-01,Latest Qtr
73443,38149.0,144.0,8.02,8.34,0.73,1.58,2.51,2.50,19.15,42.31,...,2010-04-01,2011-04-01,2012-04-01,2013-04-01,2014-04-01,2015-04-01,2016-04-01,2017-04-01,2018-04-01,Latest Qtr
73444,38149.0,145.0,8.02,8.34,0.73,1.58,2.51,2.50,19.15,42.31,...,2010-04-01,2011-04-01,2012-04-01,2013-04-01,2014-04-01,2015-04-01,2016-04-01,2017-04-01,2018-04-01,Latest Qtr
73465,42154.0,16.0,7.81,-3.44,7.73,15.27,13.86,16.37,11.07,3.92,...,2010-04-01,2011-04-01,2012-04-01,2013-04-01,2014-04-01,2015-04-01,2016-04-01,2017-04-01,2018-04-01,Latest Qtr
73466,42154.0,17.0,7.81,-3.44,7.73,15.27,13.86,16.37,11.07,3.92,...,2010-04-01,2011-04-01,2012-04-01,2013-04-01,2014-04-01,2015-04-01,2016-04-01,2017-04-01,2018-04-01,Latest Qtr
73467,42154.0,144.0,7.81,-3.44,7.73,15.27,13.86,16.37,11.07,3.92,...,2010-04-01,2011-04-01,2012-04-01,2013-04-01,2014-04-01,2015-04-01,2016-04-01,2017-04-01,2018-04-01,Latest Qtr
73479,46777.0,16.0,4.76,-10.35,-3.04,10.79,10.78,6.40,23.04,17.77,...,2010-04-01,2011-04-01,2012-04-01,2013-04-01,2014-04-01,2015-04-01,2016-04-01,2017-04-01,2018-04-01,Latest Qtr
73489,80339.0,16.0,-9.38,-25.53,11.33,13.97,22.22,15.24,13.62,14.73,...,2010-04-01,2011-04-01,2012-04-01,2013-04-01,2014-04-01,2015-04-01,2016-04-01,2017-04-01,2018-04-01,Latest Qtr
73490,80339.0,144.0,-9.38,-25.53,11.33,13.97,22.22,15.24,13.62,14.73,...,2010-04-01,2011-04-01,2012-04-01,2013-04-01,2014-04-01,2015-04-01,2016-04-01,2017-04-01,2018-04-01,Latest Qtr
73497,93457.0,16.0,8.86,13.37,0.86,13.16,20.12,5.27,8.41,7.09,...,2010-04-01,2011-04-01,2012-04-01,2013-04-01,2014-04-01,2015-04-01,2016-04-01,2017-04-01,2018-04-01,Latest Qtr
73498,93457.0,144.0,8.86,13.37,0.86,13.16,20.12,5.27,8.41,7.09,...,2010-04-01,2011-04-01,2012-04-01,2013-04-01,2014-04-01,2015-04-01,2016-04-01,2017-04-01,2018-04-01,Latest Qtr
73516,122472.0,16.0,7.27,-25.41,13.13,19.62,20.03,20.03,24.73,24.86,...,2010-04-01,2011-04-01,2012-04-01,2013-04-01,2014-04-01,2015-04-01,2016-04-01,2017-04-01,2018-04-01,Latest Qtr
73517,122472.0,141.0,7.27,-25.41,13.13,19.62,20.03,20.03,24.73,24.86,...,2010-04-01,2011-04-01,2012-04-01,2013-04-01,2014-04-01,2015-04-01,2016-04-01,2017-04-01,2018-04-01,Latest Qtr
73518,122472.0,144.0,7.27,-25.41,13.13,19.62,20.03,20.03,24.73,24.86,...,2010-04-01,2011-04-01,2012-04-01,2013-04-01,2014-04-01,2015-04-01,2016-04-01,2017-04-01,2018-04-01,Latest Qtr
73572,231673.0,552.0,8.02,8.34,0.73,1.58,2.51,2.50,19.15,42.31,...,2010-04-01,2011-04-01,2012-04-01,2013-04-01,2014-04-01,2015-04-01,2016-04-01,2017-04-01,2018-04-01,Latest Qtr
73600,242703.0,141.0,-3.15,-34.75,-33.88,34.95,-24.20,31.33,36.03,2.87,...,2010-04-01,2011-04-01,2012-04-01,2013-04-01,2014-04-01,2015-04-01,2016-04-01,2017-04-01,2018-04-01,Latest Qtr
73601,242703.0,144.0,-3.15,-34.75,-33.88,34.95,-24.20,31.33,36.03,2.87,...,2010-04-01,2011-04-01,2012-04-01,2013-04-01,2014-04-01,2015-04-01,2016-04-01,2017-04-01,2018-04-01,Latest Qtr
73723,614192.0,16.0,5.76,12.69,4.90,7.41,4.14,4.43,7.67,3.71,...,2010-04-01,2011-04-01,2012-04-01,2013-04-01,2014-04-01,2015-04-01,2016-04-01,2017-04-01,2018-04-01,Latest Qtr
73724,614192.0,17.0,5.76,12.69,4.90,7.41,4.14,4.43,7.67,3.71,...,2010-04-01,2011-04-01,2012-04-01,2013-04-01,2014-04-01,2015-04-01,2016-04-01,2017-04-01,2018-04-01,Latest Qtr
73725,614192.0,144.0,5.76,12.69,4.90,7.41,4.14,4.43,7.67,3.71,...,2010-04-01,2011-04-01,2012-04-01,2013-04-01,2014-04-01,2015-04-01,2016-04-01,2017-04-01,2018-04-01,Latest Qtr
73726,614195.0,552.0,5.76,12.69,4.90,7.41,4.14,4.43,7.67,3.71,...,2010-04-01,2011-04-01,2012-04-01,2013-04-01,2014-04-01,2015-04-01,2016-04-01,2017-04-01,2018-04-01,Latest Qtr
73807,865705.0,552.0,7.81,0.14,5.37,-9.64,-0.75,4.51,12.60,11.67,...,2010-04-01,2011-04-01,2012-04-01,2013-04-01,2014-04-01,2015-04-01,2016-04-01,2017-04-01,2018-04-01,Latest Qtr
73841,1175904.0,552.0,7.81,-3.44,7.73,15.27,13.86,16.37,11.07,3.92,...,2010-04-01,2011-04-01,2012-04-01,2013-04-01,2014-04-01,2015-04-01,2016-04-01,2017-04-01,2018-04-01,Latest Qtr
73912,17590.0,44.0,NaN,NaN,NaN,NaN,NaN,NaN,31.24,61.77,...,2010-02-01,2011-02-01,2012-02-01,2012-12-01,2014-04-01,2015-04-01,2016-04-01,2017-04-01,2018-04-01,Latest Qtr

[return to top of this section](#value),
[return to the top](#top)
<a id="rule14"></a>
### Rule 14.

[return to top of this section](#value),
[return to the top](#top)
<a id="rule15"></a>
### Rule 15.

[return to top of this section](#value),
[return to the top](#top)
<a id="mergerules"></a>
### Merging DataFrames

In [145]:
df_rules = (df_rule1
            .merge(df_rule2, on=['ticker_id', 'exchange_id'])
            .merge(df_rule3, on=['ticker_id', 'exchange_id'])
            .merge(df_rule4, on=['ticker_id', 'exchange_id'])
           )

In [146]:
df_rules.columns.values

array(['ticker_id', 'exchange_id', 'country', 'exchange_sym', 'ticker',
       'company', 'sector', 'industry', 'stock_type', 'style', 'Year_Y_6',
       'Year_Y_5', 'Year_Y_4', 'Year_Y_3', 'Year_Y_2', 'Year_Y_1',
       'Net_Income_Y6', 'Net_Income_Y5', 'Net_Income_Y4', 'Net_Income_Y3',
       'Net_Income_Y2', 'Net_Income_Y1', 'Y10', 'Y9', 'Y8', 'Y7', 'Y6',
       'Y5', 'Dividend_Y10', 'Dividend_Y9', 'Dividend_Y8', 'Dividend_Y7',
       'Dividend_Y6', 'Dividend_Y5', 'Dividend_Y4', 'Dividend_Y3',
       'PE_TTM', 'PE_2018', 'PE_2017', 'PE_2016', 'PE_2015', 'PE_2014',
       'PE_2013', 'PE_2012', 'PB_TTM', 'PB_2018', 'PB_2017', 'PB_2016',
       'PB_2015', 'PB_2014'], dtype=object)

In [160]:
dfr = (df_rules
       .where(df_rules['country'] == 'USA')
       .groupby(['country', 'exchange_sym', 'ticker', 'company', 'sector', 'industry'])
       .mean()
       .sort_values(by='exchange_sym', ascending=True)
      )

In [161]:
dfr

                                                                                                                              ticker_id  \
country exchange_sym ticker company                                            sector             industry
USA     PINX         BMWYY  Bayerische Motoren Werke AG ADR                    Consumer Cyclical  Auto Manufacturers            11637.0
                     CCOHF  China State Construction International Holdings... Industrials        Engineering & Construction     9413.0
                     CLLDY  CapitaLand Ltd ADR                                 Real Estate        Real Estate - General          7082.0
                     CWYCY  China Railway Construction Corp Ltd ADR            Industrials        Engineering & Construction    11682.0
                     HNGKY  Hongkong Land Holdings Ltd ADR                     Real Estate        Real Estate - General          8462.0
                     ISBA   Isabella Bank Corp                                 Financial Services Banks - Regional - US          6100.0
                     NBNKF  Nordea Bank Abp                                    Financial Services Banks - Regional - Europe      9351.0
                     NSANY  Nissan Motor Co Ltd ADR                            Consumer Cyclical  Auto Manufacturers             6268.0
                     QNTO   Quaint Oak Bancorp Inc                             Financial Services Banks - Regional - US          9752.0
        XASE         DIT    Amcon Distributing Co                              Consumer Defensive Food Distribution             15692.0
        XNAS         UMPQ   Umpqua Holdings Corp                               Financial Services Banks - Regional - US         17076.0
                     LCNB   LCNB Corp                                          Financial Services Banks - Regional - US         16548.0
                     HOPE   Hope Bancorp Inc                                   Financial Services Banks - Regional - US         16671.0
                     FBIZ   First Business Financial Services Inc              Financial Services Banks - Regional - US         16337.0
                     ARCC   Ares Capital Corp                                  Financial Services Asset Management              16012.0
                     HNNA   Hennessy Advisors Inc                              Financial Services Asset Management              16436.0
        XNYS         IVZ    Invesco Ltd                                        Financial Services Asset Management              18718.0
                     AGO    Assured Guaranty Ltd                               Financial Services Insurance - Specialty         18744.0
                     BHLB   Berkshire Hills Bancorp Inc                        Financial Services Banks - Regional - US         18793.0
                     COF    Capital One Financial Corp                         Financial Services Credit Services               18860.0
                     F      Ford Motor Co                                      Consumer Cyclical  Auto Manufacturers            19092.0
                     FNB    F N B Corp                                         Financial Services Banks - Regional - US         19062.0
                     GS     Goldman Sachs Group Inc                            Financial Services Capital Markets               19127.0
                     NNI    Nelnet Inc Class A                                 Financial Services Credit Services               19376.0

                                                                                                                              exchange_id  \
country exchange_sym ticker company                                            sector             industry
USA     PINX         BMWYY  Bayerische Motoren Werke AG ADR                    Consumer Cyclical  Auto Manufacturers                 25.0
                     CCOHF  China State Construction International Holdings... Industrials        Engineering & Construction         25.0
                     CLLDY  CapitaLand Ltd ADR                                 Real Estate        Real Estate - General              25.0
                     CWYCY  China Railway Construction Corp Ltd ADR            Industrials        Engineering & Construction         25.0
                     HNGKY  Hongkong Land Holdings Ltd ADR                     Real Estate        Real Estate - General              25.0
                     ISBA   Isabella Bank Corp                                 Financial Services Banks - Regional - US              25.0
                     NBNKF  Nordea Bank Abp                                    Financial Services Banks - Regional - Europe          25.0
                     NSANY  Nissan Motor Co Ltd ADR                            Consumer Cyclical  Auto Manufacturers                 25.0
                     QNTO   Quaint Oak Bancorp Inc                             Financial Services Banks - Regional - US              25.0
        XASE         DIT    Amcon Distributing Co                              Consumer Defensive Food Distribution                 547.0
        XNAS         UMPQ   Umpqua Holdings Corp                               Financial Services Banks - Regional - US              44.0
                     LCNB   LCNB Corp                                          Financial Services Banks - Regional - US              44.0
                     HOPE   Hope Bancorp Inc                                   Financial Services Banks - Regional - US              44.0
                     FBIZ   First Business Financial Services Inc              Financial Services Banks - Regional - US              44.0
                     ARCC   Ares Capital Corp                                  Financial Services Asset Management                   44.0
                     HNNA   Hennessy Advisors Inc                              Financial Services Asset Management                   44.0
        XNYS         IVZ    Invesco Ltd                                        Financial Services Asset Management                  302.0
                     AGO    Assured Guaranty Ltd                               Financial Services Insurance - Specialty             302.0
                     BHLB   Berkshire Hills Bancorp Inc                        Financial Services Banks - Regional - US             302.0
                     COF    Capital One Financial Corp                         Financial Services Credit Services                   302.0
                     F      Ford Motor Co                                      Consumer Cyclical  Auto Manufacturers                302.0
                     FNB    F N B Corp                                         Financial Services Banks - Regional - US             302.0
                     GS     Goldman Sachs Group Inc                            Financial Services Capital Markets                   302.0
                     NNI    Nelnet Inc Class A                                 Financial Services Credit Services                   302.0

                                                                                                                              Net_Income_Y6  \
country exchange_sym ticker company                                            sector             industry
USA     PINX         BMWYY  Bayerische Motoren Werke AG ADR                    Consumer Cyclical  Auto Manufacturers           4.165809e+09
                     CCOHF  China State Construction International Holdings... Industrials        Engineering & Construction   3.881063e+09
                     CLLDY  CapitaLand Ltd ADR                                 Real Estate        Real Estate - General        4.302000e+09
                     CWYCY  China Railway Construction Corp Ltd ADR            Industrials        Engineering & Construction   2.897300e+09
                     HNGKY  Hongkong Land Holdings Ltd ADR                     Real Estate        Real Estate - General        5.211093e+09
                     ISBA   Isabella Bank Corp                                 Financial Services Banks - Regional - US        3.190058e+06
                     NBNKF  Nordea Bank Abp                                    Financial Services Banks - Regional - Europe    3.845912e+10
                     NSANY  Nissan Motor Co Ltd ADR                            Consumer Cyclical  Auto Manufacturers           2.194720e+08
                     QNTO   Quaint Oak Bancorp Inc                             Financial Services Banks - Regional - US        1.217400e+07
        XASE         DIT    Amcon Distributing Co                              Consumer Defensive Food Distribution            6.999300e+07
        XNAS         UMPQ   Umpqua Holdings Corp                               Financial Services Banks - Regional - US        8.617000e+07
                     LCNB   LCNB Corp                                          Financial Services Banks - Regional - US        2.850800e+07
                     HOPE   Hope Bancorp Inc                                   Financial Services Banks - Regional - US        1.243100e+07
                     FBIZ   First Business Financial Services Inc              Financial Services Banks - Regional - US        2.492000e+07
                     ARCC   Ares Capital Corp                                  Financial Services Asset Management             8.150000e+08
                     HNNA   Hennessy Advisors Inc                              Financial Services Asset Management             1.909580e+08
        XNYS         IVZ    Invesco Ltd                                        Financial Services Asset Management             8.240000e+08
                     AGO    Assured Guaranty Ltd                               Financial Services Insurance - Specialty        5.596000e+08
                     BHLB   Berkshire Hills Bancorp Inc                        Financial Services Banks - Regional - US        4.211000e+06
                     COF    Capital One Financial Corp                         Financial Services Credit Services              7.911000e+09
                     F      Ford Motor Co                                      Consumer Cyclical  Auto Manufacturers           1.160860e+08
                     FNB    F N B Corp                                         Financial Services Banks - Regional - US        1.591390e+08
                     GS     Goldman Sachs Group Inc                            Financial Services Capital Markets              1.827000e+09
                     NNI    Nelnet Inc Class A                                 Financial Services Credit Services              3.248660e+08

                                                                                                                              Net_Income_Y5  \
country exchange_sym ticker company                                            sector             industry
USA     PINX         BMWYY  Bayerische Motoren Werke AG ADR                    Consumer Cyclical  Auto Manufacturers           4.165809e+09
                     CCOHF  China State Construction International Holdings... Industrials        Engineering & Construction   3.881063e+09
                     CLLDY  CapitaLand Ltd ADR                                 Real Estate        Real Estate - General        4.302000e+09
                     CWYCY  China Railway Construction Corp Ltd ADR            Industrials        Engineering & Construction   2.897300e+09
                     HNGKY  Hongkong Land Holdings Ltd ADR                     Real Estate        Real Estate - General        5.211093e+09
                     ISBA   Isabella Bank Corp                                 Financial Services Banks - Regional - US        3.190058e+06
                     NBNKF  Nordea Bank Abp                                    Financial Services Banks - Regional - Europe    3.845912e+10
                     NSANY  Nissan Motor Co Ltd ADR                            Consumer Cyclical  Auto Manufacturers           2.022700e+08
                     QNTO   Quaint Oak Bancorp Inc                             Financial Services Banks - Regional - US        1.217400e+07
        XASE         DIT    Amcon Distributing Co                              Consumer Defensive Food Distribution            6.999300e+07
        XNAS         UMPQ   Umpqua Holdings Corp                               Financial Services Banks - Regional - US        8.617000e+07
                     LCNB   LCNB Corp                                          Financial Services Banks - Regional - US        2.850800e+07
                     HOPE   Hope Bancorp Inc                                   Financial Services Banks - Regional - US        1.243100e+07
                     FBIZ   First Business Financial Services Inc              Financial Services Banks - Regional - US        2.492000e+07
                     ARCC   Ares Capital Corp                                  Financial Services Asset Management             8.150000e+08
                     HNNA   Hennessy Advisors Inc                              Financial Services Asset Management             1.909580e+08
        XNYS         IVZ    Invesco Ltd                                        Financial Services Asset Management             8.240000e+08
                     AGO    Assured Guaranty Ltd                               Financial Services Insurance - Specialty        5.596000e+08
                     BHLB   Berkshire Hills Bancorp Inc                        Financial Services Banks - Regional - US        4.211000e+06
                     COF    Capital One Financial Corp                         Financial Services Credit Services              7.911000e+09
                     F      Ford Motor Co                                      Consumer Cyclical  Auto Manufacturers           1.160860e+08
                     FNB    F N B Corp                                         Financial Services Banks - Regional - US        1.591390e+08
                     GS     Goldman Sachs Group Inc                            Financial Services Capital Markets              1.827000e+09
                     NNI    Nelnet Inc Class A                                 Financial Services Credit Services              3.248660e+08

                                                                                                                              Net_Income_Y4  \
country exchange_sym ticker company                                            sector             industry
USA     PINX         BMWYY  Bayerische Motoren Werke AG ADR                    Consumer Cyclical  Auto Manufacturers           3.845990e+09
                     CCOHF  China State Construction International Holdings... Industrials        Engineering & Construction   3.520646e+09
                     CLLDY  CapitaLand Ltd ADR                                 Real Estate        Real Estate - General        3.807000e+09
                     CWYCY  China Railway Construction Corp Ltd ADR            Industrials        Engineering & Construction   2.984600e+09
                     HNGKY  Hongkong Land Holdings Ltd ADR                     Real Estate        Real Estate - General        8.618423e+09
                     ISBA   Isabella Bank Corp                                 Financial Services Banks - Regional - US        1.937088e+06
                     NBNKF  Nordea Bank Abp                                    Financial Services Banks - Regional - Europe    3.433825e+10
                     NSANY  Nissan Motor Co Ltd ADR                            Consumer Cyclical  Auto Manufacturers           1.793280e+08
                     QNTO   Quaint Oak Bancorp Inc                             Financial Services Banks - Regional - US        8.984000e+06
        XASE         DIT    Amcon Distributing Co                              Consumer Defensive Food Distribution            3.012780e+08
        XNAS         UMPQ   Umpqua Holdings Corp                               Financial Services Banks - Regional - US        8.040200e+07
                     LCNB   LCNB Corp                                          Financial Services Banks - Regional - US        2.307000e+07
                     HOPE   Hope Bancorp Inc                                   Financial Services Banks - Regional - US        9.455000e+06
                     FBIZ   First Business Financial Services Inc              Financial Services Banks - Regional - US        1.845700e+07
                     ARCC   Ares Capital Corp                                  Financial Services Asset Management             5.230000e+08
                     HNNA   Hennessy Advisors Inc                              Financial Services Asset Management             1.474550e+08
        XNYS         IVZ    Invesco Ltd                                        Financial Services Asset Management             6.710000e+08
                     AGO    Assured Guaranty Ltd                               Financial Services Insurance - Specialty        3.682000e+08
                     BHLB   Berkshire Hills Bancorp Inc                        Financial Services Banks - Regional - US        4.277000e+06
                     COF    Capital One Financial Corp                         Financial Services Credit Services              6.035000e+09
                     F      Ford Motor Co                                      Consumer Cyclical  Auto Manufacturers           9.444300e+07
                     FNB    F N B Corp                                         Financial Services Banks - Regional - US        9.607000e+07
                     GS     Goldman Sachs Group Inc                            Financial Services Capital Markets              1.128000e+09
                     NNI    Nelnet Inc Class A                                 Financial Services Credit Services              6.142730e+08

                                                                                                                              Net_Income_Y3  \
country exchange_sym ticker company                                            sector             industry
USA     PINX         BMWYY  Bayerische Motoren Werke AG ADR                    Consumer Cyclical  Auto Manufacturers           3.548578e+09
                     CCOHF  China State Construction International Holdings... Industrials        Engineering & Construction   3.196395e+09
                     CLLDY  CapitaLand Ltd ADR                                 Real Estate        Real Estate - General        2.063000e+09
                     CWYCY  China Railway Construction Corp Ltd ADR            Industrials        Engineering & Construction   2.802500e+09
                     HNGKY  Hongkong Land Holdings Ltd ADR                     Real Estate        Real Estate - General        8.043335e+09
                     ISBA   Isabella Bank Corp                                 Financial Services Banks - Regional - US        1.851480e+06
                     NBNKF  Nordea Bank Abp                                    Financial Services Banks - Regional - Europe    4.017410e+10
                     NSANY  Nissan Motor Co Ltd ADR                            Consumer Cyclical  Auto Manufacturers           1.456100e+08
                     QNTO   Quaint Oak Bancorp Inc                             Financial Services Banks - Regional - US        8.301000e+06
        XASE         DIT    Amcon Distributing Co                              Consumer Defensive Food Distribution            1.702160e+08
        XNAS         UMPQ   Umpqua Holdings Corp                               Financial Services Banks - Regional - US        1.173770e+08
                     LCNB   LCNB Corp                                          Financial Services Banks - Regional - US        2.301600e+07
                     HOPE   Hope Bancorp Inc                                   Financial Services Banks - Regional - US        6.416000e+06

In [154]:
dfr.columns

Index(['ticker_id', 'exchange_id', 'Net_Income_Y6', 'Net_Income_Y5',
       'Net_Income_Y4', 'Net_Income_Y3', 'Net_Income_Y2', 'Net_Income_Y1',
       'Dividend_Y10', 'Dividend_Y9', 'Dividend_Y8', 'Dividend_Y7',
       'Dividend_Y6', 'Dividend_Y5', 'Dividend_Y4', 'Dividend_Y3', 'PE_TTM',
       'PE_2018', 'PE_2017', 'PE_2016', 'PE_2015', 'PE_2014', 'PE_2013',
       'PE_2012', 'PB_TTM', 'PB_2018', 'PB_2017', 'PB_2016', 'PB_2015',
       'PB_2014'],
      dtype='object')

<a id="additional"></a>
[return to the top](#top)

## Additional sample / test code

In [164]:
(df_master
 .where(df_master['avevol'] > 1000000).dropna(axis=0, how='all')
)

,ticker_id,exchange_id,ticker,company,exchange,exchange_sym,industry,sector,country,country_c2,...,aprvol,avevol,Forward_PE,pb,ps,pc,currency,currency_code,fy_end,updated_date
4,20371.0,302.0,STOR,STORE Capital Corp,"NEW YORK STOCK EXCHANGE, INC.",XNYS,REIT - Diversified,Real Estate,United States,US,...,1.500000e+07,1.700000e+07,NaN,1.9,12.7,17.5,United States Dollar,USD,2019-12-31,2019-04-08
14,19993.0,302.0,PEB,Pebblebrook Hotel Trust,"NEW YORK STOCK EXCHANGE, INC.",XNYS,REIT - Hotel & Motel,Real Estate,United States,US,...,1.100000e+07,1.200000e+07,36.8,1.1,2.9,17.5,United States Dollar,USD,2019-12-31,2019-04-08
15,18925.0,302.0,NNN,National Retail Properties Inc,"NEW YORK STOCK EXCHANGE, INC.",XNYS,REIT - Retail,Real Estate,United States,US,...,6.255050e+05,1.100000e+07,NaN,2.5,13.5,17.8,United States Dollar,USD,2019-12-31,2019-04-08
20,18726.0,302.0,AIV,Apartment Investment & Management Co,"NEW YORK STOCK EXCHANGE, INC.",XNYS,REIT - Residential,Real Estate,United States,US,...,6.082250e+05,1.300000e+07,181.8,4.8,7.9,19.4,United States Dollar,USD,2019-12-31,2019-04-08
24,19694.0,302.0,UDR,UDR Inc,"NEW YORK STOCK EXCHANGE, INC.",XNYS,REIT - Residential,Real Estate,United States,US,...,1.100000e+07,1.500000e+07,NaN,4.5,11.7,21.9,United States Dollar,USD,2019-12-31,2019-04-08
25,20221.0,302.0,AMH,American Homes 4 Rent Class A,"NEW YORK STOCK EXCHANGE, INC.",XNYS,REIT - Residential,Real Estate,United States,US,...,9.166240e+05,2.000000e+07,20.6,1.3,6.3,16.5,United States Dollar,USD,2019-12-31,2019-04-08
26,20509.0,302.0,INVH,Invitation Homes Inc,"NEW YORK STOCK EXCHANGE, INC.",XNYS,REIT - Residential,Real Estate,United States,US,...,2.700000e+07,3.400000e+07,19.8,1.6,7.4,22.7,United States Dollar,USD,2019-12-31,2019-04-08
31,19677.0,302.0,CUBE,CubeSmart,"NEW YORK STOCK EXCHANGE, INC.",XNYS,REIT - Industrial,Real Estate,United States,US,...,8.983220e+05,1.400000e+07,NaN,3.5,10.0,19.6,United States Dollar,USD,2019-12-31,2019-04-08
32,19013.0,302.0,DRE,Duke Realty Corp,"NEW YORK STOCK EXCHANGE, INC.",XNYS,REIT - Industrial,Real Estate,United States,US,...,1.700000e+07,2.100000e+07,57.1,2.4,11.7,22.9,United States Dollar,USD,2019-12-31,2019-04-08
34,19162.0,302.0,HCP,HCP Inc,"NEW YORK STOCK EXCHANGE, INC.",XNYS,REIT - Healthcare Facilities,Real Estate,United States,US,...,2.600000e+07,3.200000e+07,69.4,2.5,8.3,17.5,United States Dollar,USD,2019-12-31,2019-04-08
35,19322.0,302.0,MPW,Medical Properties Trust Inc,"NEW YORK STOCK EXCHANGE, INC.",XNYS,REIT - Healthcare Facilities,Real Estate,United States,US,...,1.600000e+07,3.600000e+07,NaN,1.6,8.8,15.3,United States Dollar,USD,2019-12-31,2019-04-08
36,20144.0,302.0,HTA,Healthcare Trust of America Inc,"NEW YORK STOCK EXCHANGE, INC.",XNYS,REIT - Healthcare Facilities,Real Estate,United States,US,...,9.589930e+05,1.400000e+07,NaN,1.8,8.6,17.8,United States Dollar,USD,2019-12-31,2019-04-08
38,19367.0,302.0,NOV,National Oilwell Varco Inc,"NEW YORK STOCK EXCHANGE, INC.",XNYS,Oil & Gas Equipment & Services,Energy,United States,US,...,2.900000e+07,3.700000e+07,112.4,0.8,1.3,20.5,United States Dollar,USD,2019-12-31,2019-04-08
39,18725.0,302.0,APA,Apache Corp,"NEW YORK STOCK EXCHANGE, INC.",XNYS,Oil & Gas E&P,Energy,United States,US,...,5.500000e+07,4.400000e+07,50.8,1.9,1.9,3.6,United States Dollar,USD,2019-12-31,2019-04-08
40,18989.0,302.0,DVN,Devon Energy Corp,"NEW YORK STOCK EXCHANGE, INC.",XNYS,Oil & Gas E&P,Energy,United States,US,...,7.200000e+07,8.100000e+07,22.8,1.5,1.5,6.0,United States Dollar,USD,2019-12-31,2019-04-08
41,19051.0,302.0,EQT,EQT Corp,"NEW YORK STOCK EXCHANGE, INC.",XNYS,Oil & Gas E&P,Energy,United States,US,...,2.600000e+07,4.400000e+07,13.7,0.5,1.2,1.9,United States Dollar,USD,2019-12-31,2019-04-08
42,19305.0,302.0,MRO,Marathon Oil Corp,"NEW YORK STOCK EXCHANGE, INC.",XNYS,Oil & Gas E&P,Energy,United States,US,...,9.200000e+07,1.200000e+08,47.8,1.2,2.5,4.6,United States Dollar,USD,2019-12-31,2019-04-08
43,19389.0,302.0,NBL,Noble Energy Inc,"NEW YORK STOCK EXCHANGE, INC.",XNYS,Oil & Gas E&P,Energy,United States,US,...,5.500000e+07,6.000000e+07,285.7,1.3,2.5,5.3,United States Dollar,USD,2019-12-31,2019-04-08
44,18962.0,302.0,ENLC,EnLink Midstream LLC,"NEW YORK STOCK EXCHANGE, INC.",XNYS,Oil & Gas Midstream,Energy,United States,US,...,2.000000e+07,3.100000e+07,38.3,4.0,0.3,2.7,United States Dollar,USD,2019-12-31,2019-04-08
48,20705.0,302.0,ETRN,Equitrans Midstream Corp,"NEW YORK STOCK EXCHANGE, INC.",XNYS,Oil & Gas Midstream,Energy,United States,US,...,2.900000e+07,2.000000e+07,3.7,12.0,3.7,7.6,United States Dollar,USD,2019-12-31,2019-04-08
49,20245.0,302.0,PAGP,Plains GP Holdings LP Class A,"NEW YORK STOCK EXCHANGE, INC.",XNYS,Oil & Gas Midstream,Energy,United States,US,...,1.300000e+07,1.400000e+07,20.5,2.2,0.2,2.7,United States Dollar,USD,2019-12-31,2019-04-08
59,4025.0,1.0,PTPKF,Pakuwon Jati Tbk,OTC GREY MARKET,GREY,Real Estate Services,Real Estate,United States,US,...,1.028000e+09,1.500000e+07,NaN,4.8,6.9,13.9,United States Dollar,USD,2019-12-31,2019-04-08
91,16010.0,44.0,ACGL,Arch Capital Group Ltd,NASDAQ,XNAS,Insurance - Diversified,Financial Services,United States,US,...,8.424270e+05,1.100000e+07,13.1,1.5,2.5,8.6,United States Dollar,USD,2019-12-31,2019-04-08
121,19079.0,302.0,FBP,First BanCorp,"NEW YORK STOCK EXCHANGE, INC.",XNYS,Banks - Regional - US,Financial Services,United States,US,...,1.500000e+07,1.500000e+07,NaN,1.3,4.4,8.7,United States Dollar,USD,2019-12-31,2019-04-08
130,20368.0,302.0,AXTA,Axalta Coating Systems Ltd,"NEW YORK STOCK EXCHANGE, INC.",XNYS,Specialty Chemicals,Basic Materials,United States,US,...,2.400000e+07,1.900000e+07,19.3,5.2,1.4,13.1,United States Dollar,USD,2019-12-31,2019-04-08
137,18677.0,302.0,AEM,Agnico Eagle Mines Ltd,"NEW YORK STOCK EXCHANGE, INC.",XNYS,Gold,Basic Materials,United States,US,...,9.789010e+05,1.200000e+07,97.1,2.2,4.6,16.7,United States Dollar,USD,2019-12-31,2019-04-08
138,18720.0,302.0,AU,Anglogold Ashanti Ltd ADR,"NEW YORK STOCK EXCHANGE, INC.",XNYS,Gold,Basic Materials,United States,US,...,2.300000e+07,3.900000e+07,19.6,2.1,1.4,6.5,United States Dollar,USD,2019-12-31,2019-04-08
139,19779.0,302.0,AUY,Yamana Gold Inc,"NEW YORK STOCK EXCHANGE, INC.",XNYS,Gold,Basic Materials,United States,US,...,1.140000e+08,1.280000e+08,32.4,0.6,1.4,6.1,United States Dollar,USD,2019-12-31,2019-04-08
140,19125.0,302.0,GFI,Gold Fields Ltd ADR,"NEW YORK STOCK EXCHANGE, INC.",XNYS,Gold,Basic Materials,United States,US,...,1.800000e+07,5.000000e+07,14.8,1.2,1.2,5.7,United States Dollar,USD,2019-12-31,2019-04-08
141,15837.0,547.0,BTG,B2Gold Corp,NYSE MKT LLC,XASE,Gold,Basic Materials,United States,US,...,2.900000e+07,4.800000e+07,17.0,1.7,2.4,6.5,United States Dollar,USD,2019-12-31,2019-04-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111703,1294365.0,563.0,399107,Shenzhen SE A Share PR CNY,SHENZHEN STOCK EXCHANGE,XSHE,—,—,China,CN,...,3.770000e+08,3.590000e+08,NaN,NaN,NaN,NaN,China Yuan Renminbi,RMB,2012-07-31,2019-04-07
111705,1294367.0,563.0,399002,Shenzhen SE Component A Share PR CNY,SHENZHEN STOCK EXCHANGE,XSHE,—,—,China,CN,...,1.620000e+08,1.630000e+08,NaN,NaN,NaN,NaN,China Yuan Renminbi,RMB,2012-07-31,2019-04-07
111706,1294368.0,563.0,399001,Shenzhen SE Component PR CNY,SHENZHEN STOCK EXCHANGE,XSHE,—,—,China,CN,...,1.620000e+08,1.630000e+08,NaN,NaN,NaN,NaN,China Yuan Renminbi,RMB,2012-07-31,2019-04-07
111707,1294369.0,563.0,399106,Shenzhen SE Composite PR CNY,SHENZHEN STOCK EXCHANGE,XSHE,—,—,China,CN,...,3.770000e+08,3.590000e+08,NaN,NaN,NaN,NaN,China Yuan Renminbi,RMB,2012-07-31,2019-04-07
111708,1294370.0,563.0,399100,Shenzhen SE New PR CNY,SHENZHEN STOCK EXCHANGE,XSHE,—,—,China,CN,...,3.680000e+08,3.530000e+08,NaN,NaN,NaN,NaN,China Yuan Renminbi,RMB,2012-07-31,2019-04-07
111709,1294371.0,563.0,399101,Shenzhen SE SME Composite PR CNY,SHENZHEN STOCK EXCHANGE,XSHE,—,—,China,CN,...,1.640000e+08,1.540000e+08,NaN,NaN,NaN,NaN,China Yuan Renminbi,RMB,2012-07-31,2019-04-07
111710,153390.0,569.0,000001,SSE Composite PR CNY,SHANGHAI STOCK EXCHANGE,XSHG,—,—,China,CN,...,4.691000e+09,3.161000e+09,NaN,NaN,NaN,NaN,China Yuan Renminbi,RMB,2012-07-31,2019-04-07
111711,298292.0,569.0,000017,SSE New Composite PR CNY,SHANGHAI STOCK EXCHANGE,XSHG,—,—,China,CN,...,4.683000e+09,3.145000e+09,NaN,NaN,NaN,NaN,China Yuan Renminbi,RMB,2012-07-31,2019-04-07
111712,298331.0,569.0,000002,SSE A Share PR CNY,SHANGHAI STOCK EXCHANGE,XSHG,—,—,China,CN,...,4.683000e+09,3.156000e+09,NaN,NaN,NaN,NaN,China Yuan Renminbi,RMB,2012-07-31,2019-04-07
111713,612154.0,569.0,000016,SSE 50 A Share PR CNY,SHANGHAI STOCK EXCHANGE,XSHG,—,—,China,CN,...,7.300000e+08,4.380000e+08,NaN,NaN,NaN,NaN,China Yuan Renminbi,RMB,2012-07-31,2019-04-07
111715,1303744.0,569.0,601595,Shanghai Film Co Ltd A,SHANGHAI STOCK EXCHANGE,XSHG,Media - Diversified,Consumer Cyclical,China,CN,...,1.600000e+07,2.500000e+07,NaN,2.6,4.9,46.1,China Yuan Renminbi,RMB,2012-07-31,2019-04-07
111716,1315017.0,563.0,002725,Zhejiang Yueling Co Ltd Class A,SHENZHEN STOCK EXCHANGE,XSHE,Auto Parts,Consumer Cyclical,China,CN,...,5.300000e+07,1.230000e+08,NaN,2.8,3.0,141.7,China Yuan Renminbi,RMB,2012-07-31,2019-04-07
111717,164599.0,569.0,603009,Shanghai Beite Technology Co Ltd,SHANGHAI STOCK EXCHANGE,XSHG,Auto Parts,Consumer Cyclical,China,CN,...,2.650000e+08,7.000000e+07,NaN,1.9,3.6,58.0,China Yuan Renminbi,RMB,2012-07-31,2019-04-07
111718,1166517.0,569.0,603003,Shanghai Lonyer Fuels Co Ltd Class A,SHANGHAI STOCK EXCHANGE,XSHG,Oil & Gas Integrated,Energy,China,CN,...,4.400000e+07,5.500000e+07,NaN,0.9,0.2,NaN,China Yuan Renminbi,RMB,2012-07-31,2019-04-07
111719,216688.0,569.0,603189,Shanghai Wondertek Software Corp Ltd A,SHANGHAI STOCK EXCHANGE,XSHG,Software - Application,Technology,China,CN,...,1.390000e+08,4.500000e+07,NaN,4.3,19.1,94.6,China Yuan Renminbi,RMB,2012-07-31,2019-04-07
111721,1085718.0,563.0,002825,Shanghai Nar Industrial Co Ltd A,SHENZHEN STOCK EXCHANGE,XSHE,Publishing,Consumer Cyclical,China,CN,...,1.500000e+07,2.200000e+07,NaN,3.7,2.9,27.7,China Yuan Renminbi,RMB,2012-07-31,2019-04-07
111722,1304101.0,569.0,603733,Xianhe Co Ltd,SHANGHAI STOCK EXCHANGE,XSHG,Paper & Paper Products,Basic Materials,China,CN,...,2.610000e+08,6.600000e+07,NaN,3.7,2.8,NaN,China Yuan Renminbi,RMB,2012-07-31,2019-04-07
111730,7271.0,25.0,INKW,Greene Concepts Inc,OTC MARKETS,PINX,Computer Systems,Technology,United States,US,...,1.700000e+07,1.200000e+07,NaN,NaN,NaN,NaN,United States Dollar,USD,2015-07-31,2019-04-07
111844,143738.0,433.0,MAY,Melbana Energy Ltd,ASX - ALL MARKETS,XASX,Oil & Gas E&P,Energy,Australia,AU,...,2.300000e+07,2.100000e+07,NaN,3.1,NaN,NaN,Australia Dollar,AUD,2018-06-30,2019-04-07
111848,282012.0,433.0,INP,IncentiaPay Ltd,ASX - ALL MARKETS,XASX,Software - Infrastructure,Technology,Australia,AU,...,2.200000e+07,2.800000e+07,NaN,0.5,0.2,NaN,Australia Dollar,AUD,2018-06-30,2019-04-07
111850,789366.0,433.0,SHH,Shree Minerals Ltd,ASX - ALL MARKETS,XASX,Industrial Metals & Minerals,Basic Materials,Australia,AU,...,5.999000e+04,1.200000e+07,NaN,1.8,1.0,NaN,Australia Dollar,AUD,2018-06-30,2019-04-07
111854,281530.0,433.0,IMU,Imugene Ltd,ASX - ALL MARKETS,XASX,Biotechnology,Healthcare,Australia,AU,...,3.400000e+07,3.900000e+07,NaN,2.1,NaN,NaN,Australia Dollar,AUD,2018-06-30,2019-04-07
111855,215024.0,433.0,IVX,Invion Ltd,ASX - ALL MARKETS,XASX,Drug Manufacturers - Specialty & Generic,Healthcare,Australia,AU,...,1.300000e+07,1.500000e+07,NaN,13.4,123.0,NaN,Australia Dollar,AUD,2018-06-30,2019-04-07
111856,561749.0,433.0,XTD,XTD Ltd,ASX - ALL MARKETS,XASX,Marketing Services,Consumer Cyclical,Australia,AU,...,2.500000e+04,1.000000e+07,NaN,0.9,1.1,119.1,Australia Dollar,AUD,2018-06-30,2019-04-07
111858,648642.0,433.0,PCK,Painchek Ltd,ASX - ALL MARKETS,XASX,Health Information Services,Technology,Australia,AU,...,2.000000e+05,1.000000e+07,NaN,13.0,423.1,NaN,Australia Dollar,AUD,2018-06-30,2019-04-07
111862,675692.0,433.0,SYA,Sayona Mining Ltd,ASX - ALL MARKETS,XASX,Industrial Metals & Minerals,Basic Materials,Australia,AU,...,1.000000e+07,2.000000e+07,NaN,1.2,NaN,NaN,Australia Dollar,AUD,2018-06-30,2019-04-07
112019,18975.0,302.0,DSW,Designer Brands Inc,"NEW YORK STOCK EXCHANGE, INC.",XNYS,Apparel Stores,Consumer Cyclical,United States,US,...,9.062420e+05,1.700000e+07,12.2,2.1,0.6,10.1,United States Dollar,USD,2020-02-02,2019-03-26
112091,16494.0,44.0,IDTI,Integrated Device Technology Inc,NASDAQ,XNAS,Semiconductors,Technology,United States,US,...,3.100000e+07,2.500000e+07,22.7,10.4,7.1,21.3,United States Dollar,USD,2019-04-01,2019-03-26
112092,16018.0,44.0,ARRS,ARRIS International PLC,NASDAQ,XNAS,Communication Equipment,Technology,United States,US,...,5.100000e+07,2.100000e+07,NaN,1.9,0.9,8.9,United States Dollar,USD,2019-12-31,2019-04-04
112116,15942.0,44.0,ACET,Aceto Corp,NASDAQ,XNAS,Drug Manufacturers - Specialty & Generic,Healthcare,United States,US,...,1.200000e+07,3.300000e+07,NaN,0.1,0.0,14.5,United States Dollar,USD,2019-06-30,2019-03-25

In [16]:
df = None # Set df variable to none to close db connection

Database connection for file db/mstables2.sqlite closed.